// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumipostmark

import (
	"context"
	"reflect"

	"errors"
	"github.com/hummingbird-me/pulumi-postmark/sdk/go/pulumi-postmark/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type DomainVerification struct {
	pulumi.CustomResourceState

	DkimHost      pulumi.StringOutput `pulumi:"dkimHost"`
	DkimTextValue pulumi.StringOutput `pulumi:"dkimTextValue"`
	DkimVerified  pulumi.BoolOutput   `pulumi:"dkimVerified"`
	// ID of the Domain to verify (wire from `domain.domainId`). Immutable.
	DomainId pulumi.IntOutput `pulumi:"domainId"`
	// Maximum seconds to poll for verification to succeed while DNS propagates. Defaults to 0 (a single, non-blocking attempt).
	PollTimeoutSeconds       pulumi.IntPtrOutput `pulumi:"pollTimeoutSeconds"`
	ReturnPathDomainVerified pulumi.BoolOutput   `pulumi:"returnPathDomainVerified"`
	// Arbitrary value; change it to force re-verification on the next update.
	Trigger pulumi.StringPtrOutput `pulumi:"trigger"`
	// Whether to verify DKIM. Defaults to true.
	VerifyDkim pulumi.BoolPtrOutput `pulumi:"verifyDkim"`
	// Whether to verify the Return-Path CNAME. Defaults to true.
	VerifyReturnPath pulumi.BoolPtrOutput `pulumi:"verifyReturnPath"`
}

// NewDomainVerification registers a new resource with the given unique name, arguments, and options.
func NewDomainVerification(ctx *pulumi.Context,
	name string, args *DomainVerificationArgs, opts ...pulumi.ResourceOption) (*DomainVerification, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DomainId == nil {
		return nil, errors.New("invalid value for required argument 'DomainId'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"domainId",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DomainVerification
	err := ctx.RegisterResource("postmark:index:DomainVerification", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDomainVerification gets an existing DomainVerification resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDomainVerification(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DomainVerificationState, opts ...pulumi.ResourceOption) (*DomainVerification, error) {
	var resource DomainVerification
	err := ctx.ReadResource("postmark:index:DomainVerification", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DomainVerification resources.
type domainVerificationState struct {
}

type DomainVerificationState struct {
}

func (DomainVerificationState) ElementType() reflect.Type {
	return reflect.TypeOf((*domainVerificationState)(nil)).Elem()
}

type domainVerificationArgs struct {
	// ID of the Domain to verify (wire from `domain.domainId`). Immutable.
	DomainId int `pulumi:"domainId"`
	// Maximum seconds to poll for verification to succeed while DNS propagates. Defaults to 0 (a single, non-blocking attempt).
	PollTimeoutSeconds *int `pulumi:"pollTimeoutSeconds"`
	// Arbitrary value; change it to force re-verification on the next update.
	Trigger *string `pulumi:"trigger"`
	// Whether to verify DKIM. Defaults to true.
	VerifyDkim *bool `pulumi:"verifyDkim"`
	// Whether to verify the Return-Path CNAME. Defaults to true.
	VerifyReturnPath *bool `pulumi:"verifyReturnPath"`
}

// The set of arguments for constructing a DomainVerification resource.
type DomainVerificationArgs struct {
	// ID of the Domain to verify (wire from `domain.domainId`). Immutable.
	DomainId pulumi.IntInput
	// Maximum seconds to poll for verification to succeed while DNS propagates. Defaults to 0 (a single, non-blocking attempt).
	PollTimeoutSeconds pulumi.IntPtrInput
	// Arbitrary value; change it to force re-verification on the next update.
	Trigger pulumi.StringPtrInput
	// Whether to verify DKIM. Defaults to true.
	VerifyDkim pulumi.BoolPtrInput
	// Whether to verify the Return-Path CNAME. Defaults to true.
	VerifyReturnPath pulumi.BoolPtrInput
}

func (DomainVerificationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*domainVerificationArgs)(nil)).Elem()
}

type DomainVerificationInput interface {
	pulumi.Input

	ToDomainVerificationOutput() DomainVerificationOutput
	ToDomainVerificationOutputWithContext(ctx context.Context) DomainVerificationOutput
}

func (*DomainVerification) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainVerification)(nil)).Elem()
}

func (i *DomainVerification) ToDomainVerificationOutput() DomainVerificationOutput {
	return i.ToDomainVerificationOutputWithContext(context.Background())
}

func (i *DomainVerification) ToDomainVerificationOutputWithContext(ctx context.Context) DomainVerificationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainVerificationOutput)
}

// DomainVerificationArrayInput is an input type that accepts DomainVerificationArray and DomainVerificationArrayOutput values.
// You can construct a concrete instance of `DomainVerificationArrayInput` via:
//
//	DomainVerificationArray{ DomainVerificationArgs{...} }
type DomainVerificationArrayInput interface {
	pulumi.Input

	ToDomainVerificationArrayOutput() DomainVerificationArrayOutput
	ToDomainVerificationArrayOutputWithContext(context.Context) DomainVerificationArrayOutput
}

type DomainVerificationArray []DomainVerificationInput

func (DomainVerificationArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DomainVerification)(nil)).Elem()
}

func (i DomainVerificationArray) ToDomainVerificationArrayOutput() DomainVerificationArrayOutput {
	return i.ToDomainVerificationArrayOutputWithContext(context.Background())
}

func (i DomainVerificationArray) ToDomainVerificationArrayOutputWithContext(ctx context.Context) DomainVerificationArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainVerificationArrayOutput)
}

// DomainVerificationMapInput is an input type that accepts DomainVerificationMap and DomainVerificationMapOutput values.
// You can construct a concrete instance of `DomainVerificationMapInput` via:
//
//	DomainVerificationMap{ "key": DomainVerificationArgs{...} }
type DomainVerificationMapInput interface {
	pulumi.Input

	ToDomainVerificationMapOutput() DomainVerificationMapOutput
	ToDomainVerificationMapOutputWithContext(context.Context) DomainVerificationMapOutput
}

type DomainVerificationMap map[string]DomainVerificationInput

func (DomainVerificationMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DomainVerification)(nil)).Elem()
}

func (i DomainVerificationMap) ToDomainVerificationMapOutput() DomainVerificationMapOutput {
	return i.ToDomainVerificationMapOutputWithContext(context.Background())
}

func (i DomainVerificationMap) ToDomainVerificationMapOutputWithContext(ctx context.Context) DomainVerificationMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainVerificationMapOutput)
}

type DomainVerificationOutput struct{ *pulumi.OutputState }

func (DomainVerificationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DomainVerification)(nil)).Elem()
}

func (o DomainVerificationOutput) ToDomainVerificationOutput() DomainVerificationOutput {
	return o
}

func (o DomainVerificationOutput) ToDomainVerificationOutputWithContext(ctx context.Context) DomainVerificationOutput {
	return o
}

func (o DomainVerificationOutput) DkimHost() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainVerification) pulumi.StringOutput { return v.DkimHost }).(pulumi.StringOutput)
}

func (o DomainVerificationOutput) DkimTextValue() pulumi.StringOutput {
	return o.ApplyT(func(v *DomainVerification) pulumi.StringOutput { return v.DkimTextValue }).(pulumi.StringOutput)
}

func (o DomainVerificationOutput) DkimVerified() pulumi.BoolOutput {
	return o.ApplyT(func(v *DomainVerification) pulumi.BoolOutput { return v.DkimVerified }).(pulumi.BoolOutput)
}

// ID of the Domain to verify (wire from `domain.domainId`). Immutable.
func (o DomainVerificationOutput) DomainId() pulumi.IntOutput {
	return o.ApplyT(func(v *DomainVerification) pulumi.IntOutput { return v.DomainId }).(pulumi.IntOutput)
}

// Maximum seconds to poll for verification to succeed while DNS propagates. Defaults to 0 (a single, non-blocking attempt).
func (o DomainVerificationOutput) PollTimeoutSeconds() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *DomainVerification) pulumi.IntPtrOutput { return v.PollTimeoutSeconds }).(pulumi.IntPtrOutput)
}

func (o DomainVerificationOutput) ReturnPathDomainVerified() pulumi.BoolOutput {
	return o.ApplyT(func(v *DomainVerification) pulumi.BoolOutput { return v.ReturnPathDomainVerified }).(pulumi.BoolOutput)
}

// Arbitrary value; change it to force re-verification on the next update.
func (o DomainVerificationOutput) Trigger() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DomainVerification) pulumi.StringPtrOutput { return v.Trigger }).(pulumi.StringPtrOutput)
}

// Whether to verify DKIM. Defaults to true.
func (o DomainVerificationOutput) VerifyDkim() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DomainVerification) pulumi.BoolPtrOutput { return v.VerifyDkim }).(pulumi.BoolPtrOutput)
}

// Whether to verify the Return-Path CNAME. Defaults to true.
func (o DomainVerificationOutput) VerifyReturnPath() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DomainVerification) pulumi.BoolPtrOutput { return v.VerifyReturnPath }).(pulumi.BoolPtrOutput)
}

type DomainVerificationArrayOutput struct{ *pulumi.OutputState }

func (DomainVerificationArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DomainVerification)(nil)).Elem()
}

func (o DomainVerificationArrayOutput) ToDomainVerificationArrayOutput() DomainVerificationArrayOutput {
	return o
}

func (o DomainVerificationArrayOutput) ToDomainVerificationArrayOutputWithContext(ctx context.Context) DomainVerificationArrayOutput {
	return o
}

func (o DomainVerificationArrayOutput) Index(i pulumi.IntInput) DomainVerificationOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DomainVerification {
		return vs[0].([]*DomainVerification)[vs[1].(int)]
	}).(DomainVerificationOutput)
}

type DomainVerificationMapOutput struct{ *pulumi.OutputState }

func (DomainVerificationMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DomainVerification)(nil)).Elem()
}

func (o DomainVerificationMapOutput) ToDomainVerificationMapOutput() DomainVerificationMapOutput {
	return o
}

func (o DomainVerificationMapOutput) ToDomainVerificationMapOutputWithContext(ctx context.Context) DomainVerificationMapOutput {
	return o
}

func (o DomainVerificationMapOutput) MapIndex(k pulumi.StringInput) DomainVerificationOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DomainVerification {
		return vs[0].(map[string]*DomainVerification)[vs[1].(string)]
	}).(DomainVerificationOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DomainVerificationInput)(nil)).Elem(), &DomainVerification{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainVerificationArrayInput)(nil)).Elem(), DomainVerificationArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainVerificationMapInput)(nil)).Elem(), DomainVerificationMap{})
	pulumi.RegisterOutputType(DomainVerificationOutput{})
	pulumi.RegisterOutputType(DomainVerificationArrayOutput{})
	pulumi.RegisterOutputType(DomainVerificationMapOutput{})
}
