// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumipostmark

import (
	"context"
	"reflect"

	"github.com/hummingbird-me/pulumi-postmark/sdk/go/pulumi-postmark/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Provider struct {
	pulumi.ProviderResourceState

	// Postmark Account API token (X-Postmark-Account-Token). Required to manage Servers, Domains and Sender Signatures. May also be set via the POSTMARK_ACCOUNT_TOKEN environment variable.
	AccountToken pulumi.StringPtrOutput `pulumi:"accountToken"`
	// Base URL of the Postmark API. Defaults to https://api.postmarkapp.com. May also be set via the POSTMARK_BASE_URL environment variable (useful for testing).
	BaseUrl pulumi.StringPtrOutput `pulumi:"baseUrl"`
	// Default Postmark Server API token (X-Postmark-Server-Token) used for Template operations when a Template does not set its own `serverToken`/`serverId`. Only useful when all Templates live on a single server. May also be set via the POSTMARK_SERVER_TOKEN environment variable.
	ServerToken pulumi.StringPtrOutput `pulumi:"serverToken"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.AccountToken == nil {
		if d := internal.GetEnvOrDefault("", nil, "POSTMARK_ACCOUNT_TOKEN"); d != nil {
			args.AccountToken = pulumi.StringPtr(d.(string))
		}
	}
	if args.BaseUrl == nil {
		if d := internal.GetEnvOrDefault("https://api.postmarkapp.com", nil, "POSTMARK_BASE_URL"); d != nil {
			args.BaseUrl = pulumi.StringPtr(d.(string))
		}
	}
	if args.ServerToken == nil {
		if d := internal.GetEnvOrDefault("", nil, "POSTMARK_SERVER_TOKEN"); d != nil {
			args.ServerToken = pulumi.StringPtr(d.(string))
		}
	}
	if args.AccountToken != nil {
		args.AccountToken = pulumi.ToSecret(args.AccountToken).(pulumi.StringPtrInput)
	}
	if args.ServerToken != nil {
		args.ServerToken = pulumi.ToSecret(args.ServerToken).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"accountToken",
		"serverToken",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:postmark", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// Postmark Account API token (X-Postmark-Account-Token). Required to manage Servers, Domains and Sender Signatures. May also be set via the POSTMARK_ACCOUNT_TOKEN environment variable.
	AccountToken *string `pulumi:"accountToken"`
	// Base URL of the Postmark API. Defaults to https://api.postmarkapp.com. May also be set via the POSTMARK_BASE_URL environment variable (useful for testing).
	BaseUrl *string `pulumi:"baseUrl"`
	// Default Postmark Server API token (X-Postmark-Server-Token) used for Template operations when a Template does not set its own `serverToken`/`serverId`. Only useful when all Templates live on a single server. May also be set via the POSTMARK_SERVER_TOKEN environment variable.
	ServerToken *string `pulumi:"serverToken"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// Postmark Account API token (X-Postmark-Account-Token). Required to manage Servers, Domains and Sender Signatures. May also be set via the POSTMARK_ACCOUNT_TOKEN environment variable.
	AccountToken pulumi.StringPtrInput
	// Base URL of the Postmark API. Defaults to https://api.postmarkapp.com. May also be set via the POSTMARK_BASE_URL environment variable (useful for testing).
	BaseUrl pulumi.StringPtrInput
	// Default Postmark Server API token (X-Postmark-Server-Token) used for Template operations when a Template does not set its own `serverToken`/`serverId`. Only useful when all Templates live on a single server. May also be set via the POSTMARK_SERVER_TOKEN environment variable.
	ServerToken pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// Postmark Account API token (X-Postmark-Account-Token). Required to manage Servers, Domains and Sender Signatures. May also be set via the POSTMARK_ACCOUNT_TOKEN environment variable.
func (o ProviderOutput) AccountToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.AccountToken }).(pulumi.StringPtrOutput)
}

// Base URL of the Postmark API. Defaults to https://api.postmarkapp.com. May also be set via the POSTMARK_BASE_URL environment variable (useful for testing).
func (o ProviderOutput) BaseUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.BaseUrl }).(pulumi.StringPtrOutput)
}

// Default Postmark Server API token (X-Postmark-Server-Token) used for Template operations when a Template does not set its own `serverToken`/`serverId`. Only useful when all Templates live on a single server. May also be set via the POSTMARK_SERVER_TOKEN environment variable.
func (o ProviderOutput) ServerToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ServerToken }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
