// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumipostmark

import (
	"context"
	"reflect"

	"errors"
	"github.com/hummingbird-me/pulumi-postmark/sdk/go/pulumi-postmark/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type SenderSignature struct {
	pulumi.CustomResourceState

	// Optional note (max 400 chars) included in the confirmation email.
	ConfirmationPersonalNote pulumi.StringPtrOutput `pulumi:"confirmationPersonalNote"`
	// Whether the signature has been confirmed. Postmark requires a human to click the confirmation email; run `pulumi refresh` to observe this flipping to true.
	Confirmed            pulumi.BoolOutput   `pulumi:"confirmed"`
	DkimHost             pulumi.StringOutput `pulumi:"dkimHost"`
	DkimPendingHost      pulumi.StringOutput `pulumi:"dkimPendingHost"`
	DkimPendingTextValue pulumi.StringOutput `pulumi:"dkimPendingTextValue"`
	DkimTextValue        pulumi.StringOutput `pulumi:"dkimTextValue"`
	DkimVerified         pulumi.BoolOutput   `pulumi:"dkimVerified"`
	Domain               pulumi.StringOutput `pulumi:"domain"`
	EmailAddress         pulumi.StringOutput `pulumi:"emailAddress"`
	// The email address to sign. Immutable — changing it replaces the signature.
	FromEmail pulumi.StringOutput `pulumi:"fromEmail"`
	// From name associated with the signature.
	Name pulumi.StringOutput `pulumi:"name"`
	// Optional Reply-To email address.
	ReplyToEmail pulumi.StringPtrOutput `pulumi:"replyToEmail"`
	// Optional custom Return-Path subdomain of the From address's domain.
	ReturnPathDomain           pulumi.StringPtrOutput `pulumi:"returnPathDomain"`
	ReturnPathDomainCnameValue pulumi.StringOutput    `pulumi:"returnPathDomainCnameValue"`
	ReturnPathDomainVerified   pulumi.BoolOutput      `pulumi:"returnPathDomainVerified"`
	SignatureId                pulumi.IntOutput       `pulumi:"signatureId"`
	// Arbitrary value; change it to resend the confirmation email on the next update.
	TriggerResend pulumi.StringPtrOutput `pulumi:"triggerResend"`
}

// NewSenderSignature registers a new resource with the given unique name, arguments, and options.
func NewSenderSignature(ctx *pulumi.Context,
	name string, args *SenderSignatureArgs, opts ...pulumi.ResourceOption) (*SenderSignature, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.FromEmail == nil {
		return nil, errors.New("invalid value for required argument 'FromEmail'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"fromEmail",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SenderSignature
	err := ctx.RegisterResource("postmark:index:SenderSignature", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSenderSignature gets an existing SenderSignature resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSenderSignature(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SenderSignatureState, opts ...pulumi.ResourceOption) (*SenderSignature, error) {
	var resource SenderSignature
	err := ctx.ReadResource("postmark:index:SenderSignature", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SenderSignature resources.
type senderSignatureState struct {
}

type SenderSignatureState struct {
}

func (SenderSignatureState) ElementType() reflect.Type {
	return reflect.TypeOf((*senderSignatureState)(nil)).Elem()
}

type senderSignatureArgs struct {
	// Optional note (max 400 chars) included in the confirmation email.
	ConfirmationPersonalNote *string `pulumi:"confirmationPersonalNote"`
	// The email address to sign. Immutable — changing it replaces the signature.
	FromEmail string `pulumi:"fromEmail"`
	// From name associated with the signature.
	Name string `pulumi:"name"`
	// Optional Reply-To email address.
	ReplyToEmail *string `pulumi:"replyToEmail"`
	// Optional custom Return-Path subdomain of the From address's domain.
	ReturnPathDomain *string `pulumi:"returnPathDomain"`
	// Arbitrary value; change it to resend the confirmation email on the next update.
	TriggerResend *string `pulumi:"triggerResend"`
}

// The set of arguments for constructing a SenderSignature resource.
type SenderSignatureArgs struct {
	// Optional note (max 400 chars) included in the confirmation email.
	ConfirmationPersonalNote pulumi.StringPtrInput
	// The email address to sign. Immutable — changing it replaces the signature.
	FromEmail pulumi.StringInput
	// From name associated with the signature.
	Name pulumi.StringInput
	// Optional Reply-To email address.
	ReplyToEmail pulumi.StringPtrInput
	// Optional custom Return-Path subdomain of the From address's domain.
	ReturnPathDomain pulumi.StringPtrInput
	// Arbitrary value; change it to resend the confirmation email on the next update.
	TriggerResend pulumi.StringPtrInput
}

func (SenderSignatureArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*senderSignatureArgs)(nil)).Elem()
}

type SenderSignatureInput interface {
	pulumi.Input

	ToSenderSignatureOutput() SenderSignatureOutput
	ToSenderSignatureOutputWithContext(ctx context.Context) SenderSignatureOutput
}

func (*SenderSignature) ElementType() reflect.Type {
	return reflect.TypeOf((**SenderSignature)(nil)).Elem()
}

func (i *SenderSignature) ToSenderSignatureOutput() SenderSignatureOutput {
	return i.ToSenderSignatureOutputWithContext(context.Background())
}

func (i *SenderSignature) ToSenderSignatureOutputWithContext(ctx context.Context) SenderSignatureOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SenderSignatureOutput)
}

// SenderSignatureArrayInput is an input type that accepts SenderSignatureArray and SenderSignatureArrayOutput values.
// You can construct a concrete instance of `SenderSignatureArrayInput` via:
//
//	SenderSignatureArray{ SenderSignatureArgs{...} }
type SenderSignatureArrayInput interface {
	pulumi.Input

	ToSenderSignatureArrayOutput() SenderSignatureArrayOutput
	ToSenderSignatureArrayOutputWithContext(context.Context) SenderSignatureArrayOutput
}

type SenderSignatureArray []SenderSignatureInput

func (SenderSignatureArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SenderSignature)(nil)).Elem()
}

func (i SenderSignatureArray) ToSenderSignatureArrayOutput() SenderSignatureArrayOutput {
	return i.ToSenderSignatureArrayOutputWithContext(context.Background())
}

func (i SenderSignatureArray) ToSenderSignatureArrayOutputWithContext(ctx context.Context) SenderSignatureArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SenderSignatureArrayOutput)
}

// SenderSignatureMapInput is an input type that accepts SenderSignatureMap and SenderSignatureMapOutput values.
// You can construct a concrete instance of `SenderSignatureMapInput` via:
//
//	SenderSignatureMap{ "key": SenderSignatureArgs{...} }
type SenderSignatureMapInput interface {
	pulumi.Input

	ToSenderSignatureMapOutput() SenderSignatureMapOutput
	ToSenderSignatureMapOutputWithContext(context.Context) SenderSignatureMapOutput
}

type SenderSignatureMap map[string]SenderSignatureInput

func (SenderSignatureMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SenderSignature)(nil)).Elem()
}

func (i SenderSignatureMap) ToSenderSignatureMapOutput() SenderSignatureMapOutput {
	return i.ToSenderSignatureMapOutputWithContext(context.Background())
}

func (i SenderSignatureMap) ToSenderSignatureMapOutputWithContext(ctx context.Context) SenderSignatureMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SenderSignatureMapOutput)
}

type SenderSignatureOutput struct{ *pulumi.OutputState }

func (SenderSignatureOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SenderSignature)(nil)).Elem()
}

func (o SenderSignatureOutput) ToSenderSignatureOutput() SenderSignatureOutput {
	return o
}

func (o SenderSignatureOutput) ToSenderSignatureOutputWithContext(ctx context.Context) SenderSignatureOutput {
	return o
}

// Optional note (max 400 chars) included in the confirmation email.
func (o SenderSignatureOutput) ConfirmationPersonalNote() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SenderSignature) pulumi.StringPtrOutput { return v.ConfirmationPersonalNote }).(pulumi.StringPtrOutput)
}

// Whether the signature has been confirmed. Postmark requires a human to click the confirmation email; run `pulumi refresh` to observe this flipping to true.
func (o SenderSignatureOutput) Confirmed() pulumi.BoolOutput {
	return o.ApplyT(func(v *SenderSignature) pulumi.BoolOutput { return v.Confirmed }).(pulumi.BoolOutput)
}

func (o SenderSignatureOutput) DkimHost() pulumi.StringOutput {
	return o.ApplyT(func(v *SenderSignature) pulumi.StringOutput { return v.DkimHost }).(pulumi.StringOutput)
}

func (o SenderSignatureOutput) DkimPendingHost() pulumi.StringOutput {
	return o.ApplyT(func(v *SenderSignature) pulumi.StringOutput { return v.DkimPendingHost }).(pulumi.StringOutput)
}

func (o SenderSignatureOutput) DkimPendingTextValue() pulumi.StringOutput {
	return o.ApplyT(func(v *SenderSignature) pulumi.StringOutput { return v.DkimPendingTextValue }).(pulumi.StringOutput)
}

func (o SenderSignatureOutput) DkimTextValue() pulumi.StringOutput {
	return o.ApplyT(func(v *SenderSignature) pulumi.StringOutput { return v.DkimTextValue }).(pulumi.StringOutput)
}

func (o SenderSignatureOutput) DkimVerified() pulumi.BoolOutput {
	return o.ApplyT(func(v *SenderSignature) pulumi.BoolOutput { return v.DkimVerified }).(pulumi.BoolOutput)
}

func (o SenderSignatureOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v *SenderSignature) pulumi.StringOutput { return v.Domain }).(pulumi.StringOutput)
}

func (o SenderSignatureOutput) EmailAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *SenderSignature) pulumi.StringOutput { return v.EmailAddress }).(pulumi.StringOutput)
}

// The email address to sign. Immutable — changing it replaces the signature.
func (o SenderSignatureOutput) FromEmail() pulumi.StringOutput {
	return o.ApplyT(func(v *SenderSignature) pulumi.StringOutput { return v.FromEmail }).(pulumi.StringOutput)
}

// From name associated with the signature.
func (o SenderSignatureOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *SenderSignature) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Optional Reply-To email address.
func (o SenderSignatureOutput) ReplyToEmail() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SenderSignature) pulumi.StringPtrOutput { return v.ReplyToEmail }).(pulumi.StringPtrOutput)
}

// Optional custom Return-Path subdomain of the From address's domain.
func (o SenderSignatureOutput) ReturnPathDomain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SenderSignature) pulumi.StringPtrOutput { return v.ReturnPathDomain }).(pulumi.StringPtrOutput)
}

func (o SenderSignatureOutput) ReturnPathDomainCnameValue() pulumi.StringOutput {
	return o.ApplyT(func(v *SenderSignature) pulumi.StringOutput { return v.ReturnPathDomainCnameValue }).(pulumi.StringOutput)
}

func (o SenderSignatureOutput) ReturnPathDomainVerified() pulumi.BoolOutput {
	return o.ApplyT(func(v *SenderSignature) pulumi.BoolOutput { return v.ReturnPathDomainVerified }).(pulumi.BoolOutput)
}

func (o SenderSignatureOutput) SignatureId() pulumi.IntOutput {
	return o.ApplyT(func(v *SenderSignature) pulumi.IntOutput { return v.SignatureId }).(pulumi.IntOutput)
}

// Arbitrary value; change it to resend the confirmation email on the next update.
func (o SenderSignatureOutput) TriggerResend() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *SenderSignature) pulumi.StringPtrOutput { return v.TriggerResend }).(pulumi.StringPtrOutput)
}

type SenderSignatureArrayOutput struct{ *pulumi.OutputState }

func (SenderSignatureArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SenderSignature)(nil)).Elem()
}

func (o SenderSignatureArrayOutput) ToSenderSignatureArrayOutput() SenderSignatureArrayOutput {
	return o
}

func (o SenderSignatureArrayOutput) ToSenderSignatureArrayOutputWithContext(ctx context.Context) SenderSignatureArrayOutput {
	return o
}

func (o SenderSignatureArrayOutput) Index(i pulumi.IntInput) SenderSignatureOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SenderSignature {
		return vs[0].([]*SenderSignature)[vs[1].(int)]
	}).(SenderSignatureOutput)
}

type SenderSignatureMapOutput struct{ *pulumi.OutputState }

func (SenderSignatureMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SenderSignature)(nil)).Elem()
}

func (o SenderSignatureMapOutput) ToSenderSignatureMapOutput() SenderSignatureMapOutput {
	return o
}

func (o SenderSignatureMapOutput) ToSenderSignatureMapOutputWithContext(ctx context.Context) SenderSignatureMapOutput {
	return o
}

func (o SenderSignatureMapOutput) MapIndex(k pulumi.StringInput) SenderSignatureOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SenderSignature {
		return vs[0].(map[string]*SenderSignature)[vs[1].(string)]
	}).(SenderSignatureOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SenderSignatureInput)(nil)).Elem(), &SenderSignature{})
	pulumi.RegisterInputType(reflect.TypeOf((*SenderSignatureArrayInput)(nil)).Elem(), SenderSignatureArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SenderSignatureMapInput)(nil)).Elem(), SenderSignatureMap{})
	pulumi.RegisterOutputType(SenderSignatureOutput{})
	pulumi.RegisterOutputType(SenderSignatureArrayOutput{})
	pulumi.RegisterOutputType(SenderSignatureMapOutput{})
}
