// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package postmark

import (
	"context"
	"reflect"

	"errors"
	"github.com/hummingbird-me/pulumi-postmark/sdk/go/postmark/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Domain struct {
	pulumi.CustomResourceState

	// Hostname of the currently-active DKIM record (populated after verification).
	DkimHost pulumi.StringOutput `pulumi:"dkimHost"`
	// Hostname for the DKIM TXT record to publish (publish this first).
	DkimPendingHost pulumi.StringOutput `pulumi:"dkimPendingHost"`
	// Value for the DKIM TXT record to publish.
	DkimPendingTextValue pulumi.StringOutput `pulumi:"dkimPendingTextValue"`
	DkimRevokedHost      pulumi.StringOutput `pulumi:"dkimRevokedHost"`
	DkimRevokedTextValue pulumi.StringOutput `pulumi:"dkimRevokedTextValue"`
	// Value of the currently-active DKIM record.
	DkimTextValue    pulumi.StringOutput `pulumi:"dkimTextValue"`
	DkimUpdateStatus pulumi.StringOutput `pulumi:"dkimUpdateStatus"`
	// Whether DKIM has been verified by Postmark.
	DkimVerified pulumi.BoolOutput `pulumi:"dkimVerified"`
	DomainId     pulumi.IntOutput  `pulumi:"domainId"`
	// The domain name to send from (e.g. `example.com`). Immutable — changing it replaces the domain.
	Name pulumi.StringOutput `pulumi:"name"`
	// Custom Return-Path subdomain (e.g. `pm-bounces.example.com`). Must be a subdomain of `name` and have a CNAME pointing at the value of `returnPathDomainCnameValue`.
	ReturnPathDomain pulumi.StringPtrOutput `pulumi:"returnPathDomain"`
	// CNAME target for the Return-Path record (typically `pm.mtasv.net`).
	ReturnPathDomainCnameValue pulumi.StringOutput `pulumi:"returnPathDomainCnameValue"`
	// Whether the Return-Path CNAME has been verified by Postmark.
	ReturnPathDomainVerified      pulumi.BoolOutput   `pulumi:"returnPathDomainVerified"`
	SafeToRemoveRevokedKeyFromDns pulumi.BoolOutput   `pulumi:"safeToRemoveRevokedKeyFromDns"`
	SpfHost                       pulumi.StringOutput `pulumi:"spfHost"`
	SpfTextValue                  pulumi.StringOutput `pulumi:"spfTextValue"`
	SpfVerified                   pulumi.BoolOutput   `pulumi:"spfVerified"`
	WeakDkim                      pulumi.BoolOutput   `pulumi:"weakDkim"`
}

// NewDomain registers a new resource with the given unique name, arguments, and options.
func NewDomain(ctx *pulumi.Context,
	name string, args *DomainArgs, opts ...pulumi.ResourceOption) (*Domain, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"name",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Domain
	err := ctx.RegisterResource("postmark:index:Domain", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDomain gets an existing Domain resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDomain(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DomainState, opts ...pulumi.ResourceOption) (*Domain, error) {
	var resource Domain
	err := ctx.ReadResource("postmark:index:Domain", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Domain resources.
type domainState struct {
}

type DomainState struct {
}

func (DomainState) ElementType() reflect.Type {
	return reflect.TypeOf((*domainState)(nil)).Elem()
}

type domainArgs struct {
	// The domain name to send from (e.g. `example.com`). Immutable — changing it replaces the domain.
	Name string `pulumi:"name"`
	// Custom Return-Path subdomain (e.g. `pm-bounces.example.com`). Must be a subdomain of `name` and have a CNAME pointing at the value of `returnPathDomainCnameValue`.
	ReturnPathDomain *string `pulumi:"returnPathDomain"`
}

// The set of arguments for constructing a Domain resource.
type DomainArgs struct {
	// The domain name to send from (e.g. `example.com`). Immutable — changing it replaces the domain.
	Name pulumi.StringInput
	// Custom Return-Path subdomain (e.g. `pm-bounces.example.com`). Must be a subdomain of `name` and have a CNAME pointing at the value of `returnPathDomainCnameValue`.
	ReturnPathDomain pulumi.StringPtrInput
}

func (DomainArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*domainArgs)(nil)).Elem()
}

type DomainInput interface {
	pulumi.Input

	ToDomainOutput() DomainOutput
	ToDomainOutputWithContext(ctx context.Context) DomainOutput
}

func (*Domain) ElementType() reflect.Type {
	return reflect.TypeOf((**Domain)(nil)).Elem()
}

func (i *Domain) ToDomainOutput() DomainOutput {
	return i.ToDomainOutputWithContext(context.Background())
}

func (i *Domain) ToDomainOutputWithContext(ctx context.Context) DomainOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainOutput)
}

// DomainArrayInput is an input type that accepts DomainArray and DomainArrayOutput values.
// You can construct a concrete instance of `DomainArrayInput` via:
//
//	DomainArray{ DomainArgs{...} }
type DomainArrayInput interface {
	pulumi.Input

	ToDomainArrayOutput() DomainArrayOutput
	ToDomainArrayOutputWithContext(context.Context) DomainArrayOutput
}

type DomainArray []DomainInput

func (DomainArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Domain)(nil)).Elem()
}

func (i DomainArray) ToDomainArrayOutput() DomainArrayOutput {
	return i.ToDomainArrayOutputWithContext(context.Background())
}

func (i DomainArray) ToDomainArrayOutputWithContext(ctx context.Context) DomainArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainArrayOutput)
}

// DomainMapInput is an input type that accepts DomainMap and DomainMapOutput values.
// You can construct a concrete instance of `DomainMapInput` via:
//
//	DomainMap{ "key": DomainArgs{...} }
type DomainMapInput interface {
	pulumi.Input

	ToDomainMapOutput() DomainMapOutput
	ToDomainMapOutputWithContext(context.Context) DomainMapOutput
}

type DomainMap map[string]DomainInput

func (DomainMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Domain)(nil)).Elem()
}

func (i DomainMap) ToDomainMapOutput() DomainMapOutput {
	return i.ToDomainMapOutputWithContext(context.Background())
}

func (i DomainMap) ToDomainMapOutputWithContext(ctx context.Context) DomainMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainMapOutput)
}

type DomainOutput struct{ *pulumi.OutputState }

func (DomainOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Domain)(nil)).Elem()
}

func (o DomainOutput) ToDomainOutput() DomainOutput {
	return o
}

func (o DomainOutput) ToDomainOutputWithContext(ctx context.Context) DomainOutput {
	return o
}

// Hostname of the currently-active DKIM record (populated after verification).
func (o DomainOutput) DkimHost() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.DkimHost }).(pulumi.StringOutput)
}

// Hostname for the DKIM TXT record to publish (publish this first).
func (o DomainOutput) DkimPendingHost() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.DkimPendingHost }).(pulumi.StringOutput)
}

// Value for the DKIM TXT record to publish.
func (o DomainOutput) DkimPendingTextValue() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.DkimPendingTextValue }).(pulumi.StringOutput)
}

func (o DomainOutput) DkimRevokedHost() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.DkimRevokedHost }).(pulumi.StringOutput)
}

func (o DomainOutput) DkimRevokedTextValue() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.DkimRevokedTextValue }).(pulumi.StringOutput)
}

// Value of the currently-active DKIM record.
func (o DomainOutput) DkimTextValue() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.DkimTextValue }).(pulumi.StringOutput)
}

func (o DomainOutput) DkimUpdateStatus() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.DkimUpdateStatus }).(pulumi.StringOutput)
}

// Whether DKIM has been verified by Postmark.
func (o DomainOutput) DkimVerified() pulumi.BoolOutput {
	return o.ApplyT(func(v *Domain) pulumi.BoolOutput { return v.DkimVerified }).(pulumi.BoolOutput)
}

func (o DomainOutput) DomainId() pulumi.IntOutput {
	return o.ApplyT(func(v *Domain) pulumi.IntOutput { return v.DomainId }).(pulumi.IntOutput)
}

// The domain name to send from (e.g. `example.com`). Immutable — changing it replaces the domain.
func (o DomainOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Custom Return-Path subdomain (e.g. `pm-bounces.example.com`). Must be a subdomain of `name` and have a CNAME pointing at the value of `returnPathDomainCnameValue`.
func (o DomainOutput) ReturnPathDomain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringPtrOutput { return v.ReturnPathDomain }).(pulumi.StringPtrOutput)
}

// CNAME target for the Return-Path record (typically `pm.mtasv.net`).
func (o DomainOutput) ReturnPathDomainCnameValue() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.ReturnPathDomainCnameValue }).(pulumi.StringOutput)
}

// Whether the Return-Path CNAME has been verified by Postmark.
func (o DomainOutput) ReturnPathDomainVerified() pulumi.BoolOutput {
	return o.ApplyT(func(v *Domain) pulumi.BoolOutput { return v.ReturnPathDomainVerified }).(pulumi.BoolOutput)
}

func (o DomainOutput) SafeToRemoveRevokedKeyFromDns() pulumi.BoolOutput {
	return o.ApplyT(func(v *Domain) pulumi.BoolOutput { return v.SafeToRemoveRevokedKeyFromDns }).(pulumi.BoolOutput)
}

func (o DomainOutput) SpfHost() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.SpfHost }).(pulumi.StringOutput)
}

func (o DomainOutput) SpfTextValue() pulumi.StringOutput {
	return o.ApplyT(func(v *Domain) pulumi.StringOutput { return v.SpfTextValue }).(pulumi.StringOutput)
}

func (o DomainOutput) SpfVerified() pulumi.BoolOutput {
	return o.ApplyT(func(v *Domain) pulumi.BoolOutput { return v.SpfVerified }).(pulumi.BoolOutput)
}

func (o DomainOutput) WeakDkim() pulumi.BoolOutput {
	return o.ApplyT(func(v *Domain) pulumi.BoolOutput { return v.WeakDkim }).(pulumi.BoolOutput)
}

type DomainArrayOutput struct{ *pulumi.OutputState }

func (DomainArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Domain)(nil)).Elem()
}

func (o DomainArrayOutput) ToDomainArrayOutput() DomainArrayOutput {
	return o
}

func (o DomainArrayOutput) ToDomainArrayOutputWithContext(ctx context.Context) DomainArrayOutput {
	return o
}

func (o DomainArrayOutput) Index(i pulumi.IntInput) DomainOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Domain {
		return vs[0].([]*Domain)[vs[1].(int)]
	}).(DomainOutput)
}

type DomainMapOutput struct{ *pulumi.OutputState }

func (DomainMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Domain)(nil)).Elem()
}

func (o DomainMapOutput) ToDomainMapOutput() DomainMapOutput {
	return o
}

func (o DomainMapOutput) ToDomainMapOutputWithContext(ctx context.Context) DomainMapOutput {
	return o
}

func (o DomainMapOutput) MapIndex(k pulumi.StringInput) DomainOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Domain {
		return vs[0].(map[string]*Domain)[vs[1].(string)]
	}).(DomainOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DomainInput)(nil)).Elem(), &Domain{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainArrayInput)(nil)).Elem(), DomainArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainMapInput)(nil)).Elem(), DomainMap{})
	pulumi.RegisterOutputType(DomainOutput{})
	pulumi.RegisterOutputType(DomainArrayOutput{})
	pulumi.RegisterOutputType(DomainMapOutput{})
}
