// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package postmark

import (
	"context"
	"reflect"

	"errors"
	"github.com/hummingbird-me/pulumi-postmark/sdk/go/postmark/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Server struct {
	pulumi.CustomResourceState

	ApiTokens pulumi.StringArrayOutput `pulumi:"apiTokens"`
	// Color of the server in the Postmark UI server list. One of: Purple, Blue, Turquoise, Green, Red, Yellow, Grey, Orange. Defaults to Blue.
	Color pulumi.StringPtrOutput `pulumi:"color"`
	// Environment type: `Live` or `Sandbox`. Immutable after creation — changing it replaces the server. Defaults to `Live`.
	DeliveryType            pulumi.StringPtrOutput `pulumi:"deliveryType"`
	EnableSmtpApiErrorHooks pulumi.BoolPtrOutput   `pulumi:"enableSmtpApiErrorHooks"`
	InboundAddress          pulumi.StringOutput    `pulumi:"inboundAddress"`
	// Inbound domain for MX setup. Point an MX record for this domain at `inbound.postmarkapp.com` to receive mail.
	InboundDomain pulumi.StringPtrOutput `pulumi:"inboundDomain"`
	InboundHash   pulumi.StringOutput    `pulumi:"inboundHash"`
	// URL Postmark POSTs to for every inbound email event.
	InboundHookUrl pulumi.StringPtrOutput `pulumi:"inboundHookUrl"`
	// Maximum spam score before an inbound message is blocked.
	InboundSpamThreshold       pulumi.IntPtrOutput  `pulumi:"inboundSpamThreshold"`
	IncludeBounceContentInHook pulumi.BoolPtrOutput `pulumi:"includeBounceContentInHook"`
	// Friendly name of the server.
	Name              pulumi.StringOutput  `pulumi:"name"`
	PostFirstOpenOnly pulumi.BoolPtrOutput `pulumi:"postFirstOpenOnly"`
	RawEmailEnabled   pulumi.BoolPtrOutput `pulumi:"rawEmailEnabled"`
	ServerId          pulumi.IntOutput     `pulumi:"serverId"`
	ServerLink        pulumi.StringOutput  `pulumi:"serverLink"`
	SmtpApiActivated  pulumi.BoolPtrOutput `pulumi:"smtpApiActivated"`
	// Link tracking mode: None, HtmlAndText, HtmlOnly or TextOnly. Defaults to None.
	TrackLinks pulumi.StringPtrOutput `pulumi:"trackLinks"`
	// Enable open tracking for messages by default.
	TrackOpens pulumi.BoolPtrOutput `pulumi:"trackOpens"`
}

// NewServer registers a new resource with the given unique name, arguments, and options.
func NewServer(ctx *pulumi.Context,
	name string, args *ServerArgs, opts ...pulumi.ResourceOption) (*Server, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiTokens",
	})
	opts = append(opts, secrets)
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"deliveryType",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Server
	err := ctx.RegisterResource("postmark:index:Server", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetServer gets an existing Server resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetServer(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ServerState, opts ...pulumi.ResourceOption) (*Server, error) {
	var resource Server
	err := ctx.ReadResource("postmark:index:Server", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Server resources.
type serverState struct {
}

type ServerState struct {
}

func (ServerState) ElementType() reflect.Type {
	return reflect.TypeOf((*serverState)(nil)).Elem()
}

type serverArgs struct {
	// Color of the server in the Postmark UI server list. One of: Purple, Blue, Turquoise, Green, Red, Yellow, Grey, Orange. Defaults to Blue.
	Color *string `pulumi:"color"`
	// Environment type: `Live` or `Sandbox`. Immutable after creation — changing it replaces the server. Defaults to `Live`.
	DeliveryType            *string `pulumi:"deliveryType"`
	EnableSmtpApiErrorHooks *bool   `pulumi:"enableSmtpApiErrorHooks"`
	// Inbound domain for MX setup. Point an MX record for this domain at `inbound.postmarkapp.com` to receive mail.
	InboundDomain *string `pulumi:"inboundDomain"`
	// URL Postmark POSTs to for every inbound email event.
	InboundHookUrl *string `pulumi:"inboundHookUrl"`
	// Maximum spam score before an inbound message is blocked.
	InboundSpamThreshold       *int  `pulumi:"inboundSpamThreshold"`
	IncludeBounceContentInHook *bool `pulumi:"includeBounceContentInHook"`
	// Friendly name of the server.
	Name              string `pulumi:"name"`
	PostFirstOpenOnly *bool  `pulumi:"postFirstOpenOnly"`
	RawEmailEnabled   *bool  `pulumi:"rawEmailEnabled"`
	SmtpApiActivated  *bool  `pulumi:"smtpApiActivated"`
	// Link tracking mode: None, HtmlAndText, HtmlOnly or TextOnly. Defaults to None.
	TrackLinks *string `pulumi:"trackLinks"`
	// Enable open tracking for messages by default.
	TrackOpens *bool `pulumi:"trackOpens"`
}

// The set of arguments for constructing a Server resource.
type ServerArgs struct {
	// Color of the server in the Postmark UI server list. One of: Purple, Blue, Turquoise, Green, Red, Yellow, Grey, Orange. Defaults to Blue.
	Color pulumi.StringPtrInput
	// Environment type: `Live` or `Sandbox`. Immutable after creation — changing it replaces the server. Defaults to `Live`.
	DeliveryType            pulumi.StringPtrInput
	EnableSmtpApiErrorHooks pulumi.BoolPtrInput
	// Inbound domain for MX setup. Point an MX record for this domain at `inbound.postmarkapp.com` to receive mail.
	InboundDomain pulumi.StringPtrInput
	// URL Postmark POSTs to for every inbound email event.
	InboundHookUrl pulumi.StringPtrInput
	// Maximum spam score before an inbound message is blocked.
	InboundSpamThreshold       pulumi.IntPtrInput
	IncludeBounceContentInHook pulumi.BoolPtrInput
	// Friendly name of the server.
	Name              pulumi.StringInput
	PostFirstOpenOnly pulumi.BoolPtrInput
	RawEmailEnabled   pulumi.BoolPtrInput
	SmtpApiActivated  pulumi.BoolPtrInput
	// Link tracking mode: None, HtmlAndText, HtmlOnly or TextOnly. Defaults to None.
	TrackLinks pulumi.StringPtrInput
	// Enable open tracking for messages by default.
	TrackOpens pulumi.BoolPtrInput
}

func (ServerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*serverArgs)(nil)).Elem()
}

type ServerInput interface {
	pulumi.Input

	ToServerOutput() ServerOutput
	ToServerOutputWithContext(ctx context.Context) ServerOutput
}

func (*Server) ElementType() reflect.Type {
	return reflect.TypeOf((**Server)(nil)).Elem()
}

func (i *Server) ToServerOutput() ServerOutput {
	return i.ToServerOutputWithContext(context.Background())
}

func (i *Server) ToServerOutputWithContext(ctx context.Context) ServerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerOutput)
}

// ServerArrayInput is an input type that accepts ServerArray and ServerArrayOutput values.
// You can construct a concrete instance of `ServerArrayInput` via:
//
//	ServerArray{ ServerArgs{...} }
type ServerArrayInput interface {
	pulumi.Input

	ToServerArrayOutput() ServerArrayOutput
	ToServerArrayOutputWithContext(context.Context) ServerArrayOutput
}

type ServerArray []ServerInput

func (ServerArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Server)(nil)).Elem()
}

func (i ServerArray) ToServerArrayOutput() ServerArrayOutput {
	return i.ToServerArrayOutputWithContext(context.Background())
}

func (i ServerArray) ToServerArrayOutputWithContext(ctx context.Context) ServerArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerArrayOutput)
}

// ServerMapInput is an input type that accepts ServerMap and ServerMapOutput values.
// You can construct a concrete instance of `ServerMapInput` via:
//
//	ServerMap{ "key": ServerArgs{...} }
type ServerMapInput interface {
	pulumi.Input

	ToServerMapOutput() ServerMapOutput
	ToServerMapOutputWithContext(context.Context) ServerMapOutput
}

type ServerMap map[string]ServerInput

func (ServerMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Server)(nil)).Elem()
}

func (i ServerMap) ToServerMapOutput() ServerMapOutput {
	return i.ToServerMapOutputWithContext(context.Background())
}

func (i ServerMap) ToServerMapOutputWithContext(ctx context.Context) ServerMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerMapOutput)
}

type ServerOutput struct{ *pulumi.OutputState }

func (ServerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Server)(nil)).Elem()
}

func (o ServerOutput) ToServerOutput() ServerOutput {
	return o
}

func (o ServerOutput) ToServerOutputWithContext(ctx context.Context) ServerOutput {
	return o
}

func (o ServerOutput) ApiTokens() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Server) pulumi.StringArrayOutput { return v.ApiTokens }).(pulumi.StringArrayOutput)
}

// Color of the server in the Postmark UI server list. One of: Purple, Blue, Turquoise, Green, Red, Yellow, Grey, Orange. Defaults to Blue.
func (o ServerOutput) Color() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.StringPtrOutput { return v.Color }).(pulumi.StringPtrOutput)
}

// Environment type: `Live` or `Sandbox`. Immutable after creation — changing it replaces the server. Defaults to `Live`.
func (o ServerOutput) DeliveryType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.StringPtrOutput { return v.DeliveryType }).(pulumi.StringPtrOutput)
}

func (o ServerOutput) EnableSmtpApiErrorHooks() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.BoolPtrOutput { return v.EnableSmtpApiErrorHooks }).(pulumi.BoolPtrOutput)
}

func (o ServerOutput) InboundAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *Server) pulumi.StringOutput { return v.InboundAddress }).(pulumi.StringOutput)
}

// Inbound domain for MX setup. Point an MX record for this domain at `inbound.postmarkapp.com` to receive mail.
func (o ServerOutput) InboundDomain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.StringPtrOutput { return v.InboundDomain }).(pulumi.StringPtrOutput)
}

func (o ServerOutput) InboundHash() pulumi.StringOutput {
	return o.ApplyT(func(v *Server) pulumi.StringOutput { return v.InboundHash }).(pulumi.StringOutput)
}

// URL Postmark POSTs to for every inbound email event.
func (o ServerOutput) InboundHookUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.StringPtrOutput { return v.InboundHookUrl }).(pulumi.StringPtrOutput)
}

// Maximum spam score before an inbound message is blocked.
func (o ServerOutput) InboundSpamThreshold() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.IntPtrOutput { return v.InboundSpamThreshold }).(pulumi.IntPtrOutput)
}

func (o ServerOutput) IncludeBounceContentInHook() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.BoolPtrOutput { return v.IncludeBounceContentInHook }).(pulumi.BoolPtrOutput)
}

// Friendly name of the server.
func (o ServerOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Server) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o ServerOutput) PostFirstOpenOnly() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.BoolPtrOutput { return v.PostFirstOpenOnly }).(pulumi.BoolPtrOutput)
}

func (o ServerOutput) RawEmailEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.BoolPtrOutput { return v.RawEmailEnabled }).(pulumi.BoolPtrOutput)
}

func (o ServerOutput) ServerId() pulumi.IntOutput {
	return o.ApplyT(func(v *Server) pulumi.IntOutput { return v.ServerId }).(pulumi.IntOutput)
}

func (o ServerOutput) ServerLink() pulumi.StringOutput {
	return o.ApplyT(func(v *Server) pulumi.StringOutput { return v.ServerLink }).(pulumi.StringOutput)
}

func (o ServerOutput) SmtpApiActivated() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.BoolPtrOutput { return v.SmtpApiActivated }).(pulumi.BoolPtrOutput)
}

// Link tracking mode: None, HtmlAndText, HtmlOnly or TextOnly. Defaults to None.
func (o ServerOutput) TrackLinks() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.StringPtrOutput { return v.TrackLinks }).(pulumi.StringPtrOutput)
}

// Enable open tracking for messages by default.
func (o ServerOutput) TrackOpens() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Server) pulumi.BoolPtrOutput { return v.TrackOpens }).(pulumi.BoolPtrOutput)
}

type ServerArrayOutput struct{ *pulumi.OutputState }

func (ServerArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Server)(nil)).Elem()
}

func (o ServerArrayOutput) ToServerArrayOutput() ServerArrayOutput {
	return o
}

func (o ServerArrayOutput) ToServerArrayOutputWithContext(ctx context.Context) ServerArrayOutput {
	return o
}

func (o ServerArrayOutput) Index(i pulumi.IntInput) ServerOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Server {
		return vs[0].([]*Server)[vs[1].(int)]
	}).(ServerOutput)
}

type ServerMapOutput struct{ *pulumi.OutputState }

func (ServerMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Server)(nil)).Elem()
}

func (o ServerMapOutput) ToServerMapOutput() ServerMapOutput {
	return o
}

func (o ServerMapOutput) ToServerMapOutputWithContext(ctx context.Context) ServerMapOutput {
	return o
}

func (o ServerMapOutput) MapIndex(k pulumi.StringInput) ServerOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Server {
		return vs[0].(map[string]*Server)[vs[1].(string)]
	}).(ServerOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ServerInput)(nil)).Elem(), &Server{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServerArrayInput)(nil)).Elem(), ServerArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServerMapInput)(nil)).Elem(), ServerMap{})
	pulumi.RegisterOutputType(ServerOutput{})
	pulumi.RegisterOutputType(ServerArrayOutput{})
	pulumi.RegisterOutputType(ServerMapOutput{})
}
