// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package postmark

import (
	"context"
	"reflect"

	"errors"
	"github.com/hummingbird-me/pulumi-postmark/sdk/go/postmark/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Template struct {
	pulumi.CustomResourceState

	Active pulumi.BoolOutput `pulumi:"active"`
	// Optional unique alias (within the server). Must start with a letter; may contain letters, digits, '.', '-' and '_'.
	Alias              pulumi.StringPtrOutput `pulumi:"alias"`
	AssociatedServerId pulumi.IntOutput       `pulumi:"associatedServerId"`
	// HTML body. Required unless `textBody` is set.
	HtmlBody pulumi.StringPtrOutput `pulumi:"htmlBody"`
	// Alias of a Layout to wrap this Standard template (set to "" to disassociate).
	LayoutTemplate pulumi.StringPtrOutput `pulumi:"layoutTemplate"`
	// Name of the template.
	Name pulumi.StringOutput `pulumi:"name"`
	// ID of the server this template belongs to; the provider looks up its token via the account token. Immutable — changing it replaces the template.
	ServerId pulumi.IntPtrOutput `pulumi:"serverId"`
	// Server API token of the server this template belongs to. Wire from `server.apiTokens[0]`. Falls back to `serverId` lookup, then the provider `serverToken` config.
	ServerToken pulumi.StringPtrOutput `pulumi:"serverToken"`
	// Subject line. Required for Standard templates; not allowed for Layouts.
	Subject    pulumi.StringPtrOutput `pulumi:"subject"`
	TemplateId pulumi.IntOutput       `pulumi:"templateId"`
	// `Standard` (default) or `Layout`. Immutable — changing it replaces the template.
	TemplateType pulumi.StringPtrOutput `pulumi:"templateType"`
	// Plain-text body. Required unless `htmlBody` is set.
	TextBody pulumi.StringPtrOutput `pulumi:"textBody"`
}

// NewTemplate registers a new resource with the given unique name, arguments, and options.
func NewTemplate(ctx *pulumi.Context,
	name string, args *TemplateArgs, opts ...pulumi.ResourceOption) (*Template, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.ServerToken != nil {
		args.ServerToken = pulumi.ToSecret(args.ServerToken).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"serverToken",
	})
	opts = append(opts, secrets)
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"serverId",
		"templateType",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Template
	err := ctx.RegisterResource("postmark:index:Template", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetTemplate gets an existing Template resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetTemplate(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *TemplateState, opts ...pulumi.ResourceOption) (*Template, error) {
	var resource Template
	err := ctx.ReadResource("postmark:index:Template", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Template resources.
type templateState struct {
}

type TemplateState struct {
}

func (TemplateState) ElementType() reflect.Type {
	return reflect.TypeOf((*templateState)(nil)).Elem()
}

type templateArgs struct {
	// Optional unique alias (within the server). Must start with a letter; may contain letters, digits, '.', '-' and '_'.
	Alias *string `pulumi:"alias"`
	// HTML body. Required unless `textBody` is set.
	HtmlBody *string `pulumi:"htmlBody"`
	// Alias of a Layout to wrap this Standard template (set to "" to disassociate).
	LayoutTemplate *string `pulumi:"layoutTemplate"`
	// Name of the template.
	Name string `pulumi:"name"`
	// ID of the server this template belongs to; the provider looks up its token via the account token. Immutable — changing it replaces the template.
	ServerId *int `pulumi:"serverId"`
	// Server API token of the server this template belongs to. Wire from `server.apiTokens[0]`. Falls back to `serverId` lookup, then the provider `serverToken` config.
	ServerToken *string `pulumi:"serverToken"`
	// Subject line. Required for Standard templates; not allowed for Layouts.
	Subject *string `pulumi:"subject"`
	// `Standard` (default) or `Layout`. Immutable — changing it replaces the template.
	TemplateType *string `pulumi:"templateType"`
	// Plain-text body. Required unless `htmlBody` is set.
	TextBody *string `pulumi:"textBody"`
}

// The set of arguments for constructing a Template resource.
type TemplateArgs struct {
	// Optional unique alias (within the server). Must start with a letter; may contain letters, digits, '.', '-' and '_'.
	Alias pulumi.StringPtrInput
	// HTML body. Required unless `textBody` is set.
	HtmlBody pulumi.StringPtrInput
	// Alias of a Layout to wrap this Standard template (set to "" to disassociate).
	LayoutTemplate pulumi.StringPtrInput
	// Name of the template.
	Name pulumi.StringInput
	// ID of the server this template belongs to; the provider looks up its token via the account token. Immutable — changing it replaces the template.
	ServerId pulumi.IntPtrInput
	// Server API token of the server this template belongs to. Wire from `server.apiTokens[0]`. Falls back to `serverId` lookup, then the provider `serverToken` config.
	ServerToken pulumi.StringPtrInput
	// Subject line. Required for Standard templates; not allowed for Layouts.
	Subject pulumi.StringPtrInput
	// `Standard` (default) or `Layout`. Immutable — changing it replaces the template.
	TemplateType pulumi.StringPtrInput
	// Plain-text body. Required unless `htmlBody` is set.
	TextBody pulumi.StringPtrInput
}

func (TemplateArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*templateArgs)(nil)).Elem()
}

type TemplateInput interface {
	pulumi.Input

	ToTemplateOutput() TemplateOutput
	ToTemplateOutputWithContext(ctx context.Context) TemplateOutput
}

func (*Template) ElementType() reflect.Type {
	return reflect.TypeOf((**Template)(nil)).Elem()
}

func (i *Template) ToTemplateOutput() TemplateOutput {
	return i.ToTemplateOutputWithContext(context.Background())
}

func (i *Template) ToTemplateOutputWithContext(ctx context.Context) TemplateOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TemplateOutput)
}

// TemplateArrayInput is an input type that accepts TemplateArray and TemplateArrayOutput values.
// You can construct a concrete instance of `TemplateArrayInput` via:
//
//	TemplateArray{ TemplateArgs{...} }
type TemplateArrayInput interface {
	pulumi.Input

	ToTemplateArrayOutput() TemplateArrayOutput
	ToTemplateArrayOutputWithContext(context.Context) TemplateArrayOutput
}

type TemplateArray []TemplateInput

func (TemplateArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Template)(nil)).Elem()
}

func (i TemplateArray) ToTemplateArrayOutput() TemplateArrayOutput {
	return i.ToTemplateArrayOutputWithContext(context.Background())
}

func (i TemplateArray) ToTemplateArrayOutputWithContext(ctx context.Context) TemplateArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TemplateArrayOutput)
}

// TemplateMapInput is an input type that accepts TemplateMap and TemplateMapOutput values.
// You can construct a concrete instance of `TemplateMapInput` via:
//
//	TemplateMap{ "key": TemplateArgs{...} }
type TemplateMapInput interface {
	pulumi.Input

	ToTemplateMapOutput() TemplateMapOutput
	ToTemplateMapOutputWithContext(context.Context) TemplateMapOutput
}

type TemplateMap map[string]TemplateInput

func (TemplateMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Template)(nil)).Elem()
}

func (i TemplateMap) ToTemplateMapOutput() TemplateMapOutput {
	return i.ToTemplateMapOutputWithContext(context.Background())
}

func (i TemplateMap) ToTemplateMapOutputWithContext(ctx context.Context) TemplateMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TemplateMapOutput)
}

type TemplateOutput struct{ *pulumi.OutputState }

func (TemplateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Template)(nil)).Elem()
}

func (o TemplateOutput) ToTemplateOutput() TemplateOutput {
	return o
}

func (o TemplateOutput) ToTemplateOutputWithContext(ctx context.Context) TemplateOutput {
	return o
}

func (o TemplateOutput) Active() pulumi.BoolOutput {
	return o.ApplyT(func(v *Template) pulumi.BoolOutput { return v.Active }).(pulumi.BoolOutput)
}

// Optional unique alias (within the server). Must start with a letter; may contain letters, digits, '.', '-' and '_'.
func (o TemplateOutput) Alias() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.StringPtrOutput { return v.Alias }).(pulumi.StringPtrOutput)
}

func (o TemplateOutput) AssociatedServerId() pulumi.IntOutput {
	return o.ApplyT(func(v *Template) pulumi.IntOutput { return v.AssociatedServerId }).(pulumi.IntOutput)
}

// HTML body. Required unless `textBody` is set.
func (o TemplateOutput) HtmlBody() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.StringPtrOutput { return v.HtmlBody }).(pulumi.StringPtrOutput)
}

// Alias of a Layout to wrap this Standard template (set to "" to disassociate).
func (o TemplateOutput) LayoutTemplate() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.StringPtrOutput { return v.LayoutTemplate }).(pulumi.StringPtrOutput)
}

// Name of the template.
func (o TemplateOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Template) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// ID of the server this template belongs to; the provider looks up its token via the account token. Immutable — changing it replaces the template.
func (o TemplateOutput) ServerId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.IntPtrOutput { return v.ServerId }).(pulumi.IntPtrOutput)
}

// Server API token of the server this template belongs to. Wire from `server.apiTokens[0]`. Falls back to `serverId` lookup, then the provider `serverToken` config.
func (o TemplateOutput) ServerToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.StringPtrOutput { return v.ServerToken }).(pulumi.StringPtrOutput)
}

// Subject line. Required for Standard templates; not allowed for Layouts.
func (o TemplateOutput) Subject() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.StringPtrOutput { return v.Subject }).(pulumi.StringPtrOutput)
}

func (o TemplateOutput) TemplateId() pulumi.IntOutput {
	return o.ApplyT(func(v *Template) pulumi.IntOutput { return v.TemplateId }).(pulumi.IntOutput)
}

// `Standard` (default) or `Layout`. Immutable — changing it replaces the template.
func (o TemplateOutput) TemplateType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.StringPtrOutput { return v.TemplateType }).(pulumi.StringPtrOutput)
}

// Plain-text body. Required unless `htmlBody` is set.
func (o TemplateOutput) TextBody() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Template) pulumi.StringPtrOutput { return v.TextBody }).(pulumi.StringPtrOutput)
}

type TemplateArrayOutput struct{ *pulumi.OutputState }

func (TemplateArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Template)(nil)).Elem()
}

func (o TemplateArrayOutput) ToTemplateArrayOutput() TemplateArrayOutput {
	return o
}

func (o TemplateArrayOutput) ToTemplateArrayOutputWithContext(ctx context.Context) TemplateArrayOutput {
	return o
}

func (o TemplateArrayOutput) Index(i pulumi.IntInput) TemplateOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Template {
		return vs[0].([]*Template)[vs[1].(int)]
	}).(TemplateOutput)
}

type TemplateMapOutput struct{ *pulumi.OutputState }

func (TemplateMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Template)(nil)).Elem()
}

func (o TemplateMapOutput) ToTemplateMapOutput() TemplateMapOutput {
	return o
}

func (o TemplateMapOutput) ToTemplateMapOutputWithContext(ctx context.Context) TemplateMapOutput {
	return o
}

func (o TemplateMapOutput) MapIndex(k pulumi.StringInput) TemplateOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Template {
		return vs[0].(map[string]*Template)[vs[1].(string)]
	}).(TemplateOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TemplateInput)(nil)).Elem(), &Template{})
	pulumi.RegisterInputType(reflect.TypeOf((*TemplateArrayInput)(nil)).Elem(), TemplateArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*TemplateMapInput)(nil)).Elem(), TemplateMap{})
	pulumi.RegisterOutputType(TemplateOutput{})
	pulumi.RegisterOutputType(TemplateArrayOutput{})
	pulumi.RegisterOutputType(TemplateMapOutput{})
}
