// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace HummingbirdMe.Postmark
{
    [PostmarkResourceType("postmark:index:DomainVerification")]
    public partial class DomainVerification : global::Pulumi.CustomResource
    {
        [Output("dkimHost")]
        public Output<string> DkimHost { get; private set; } = null!;

        [Output("dkimTextValue")]
        public Output<string> DkimTextValue { get; private set; } = null!;

        [Output("dkimVerified")]
        public Output<bool> DkimVerified { get; private set; } = null!;

        /// <summary>
        /// ID of the Domain to verify (wire from `domain.domainId`). Immutable.
        /// </summary>
        [Output("domainId")]
        public Output<int> DomainId { get; private set; } = null!;

        /// <summary>
        /// Maximum seconds to poll for verification to succeed while DNS propagates. Defaults to 0 (a single, non-blocking attempt).
        /// </summary>
        [Output("pollTimeoutSeconds")]
        public Output<int?> PollTimeoutSeconds { get; private set; } = null!;

        [Output("returnPathDomainVerified")]
        public Output<bool> ReturnPathDomainVerified { get; private set; } = null!;

        /// <summary>
        /// Arbitrary value; change it to force re-verification on the next update.
        /// </summary>
        [Output("trigger")]
        public Output<string?> Trigger { get; private set; } = null!;

        /// <summary>
        /// Whether to verify DKIM. Defaults to true.
        /// </summary>
        [Output("verifyDkim")]
        public Output<bool?> VerifyDkim { get; private set; } = null!;

        /// <summary>
        /// Whether to verify the Return-Path CNAME. Defaults to true.
        /// </summary>
        [Output("verifyReturnPath")]
        public Output<bool?> VerifyReturnPath { get; private set; } = null!;


        /// <summary>
        /// Create a DomainVerification resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DomainVerification(string name, DomainVerificationArgs args, CustomResourceOptions? options = null)
            : base("postmark:index:DomainVerification", name, args ?? new DomainVerificationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DomainVerification(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("postmark:index:DomainVerification", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/hummingbird-me/pulumi-postmark",
                ReplaceOnChanges =
                {
                    "domainId",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DomainVerification resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DomainVerification Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new DomainVerification(name, id, options);
        }
    }

    public sealed class DomainVerificationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// ID of the Domain to verify (wire from `domain.domainId`). Immutable.
        /// </summary>
        [Input("domainId", required: true)]
        public Input<int> DomainId { get; set; } = null!;

        /// <summary>
        /// Maximum seconds to poll for verification to succeed while DNS propagates. Defaults to 0 (a single, non-blocking attempt).
        /// </summary>
        [Input("pollTimeoutSeconds")]
        public Input<int>? PollTimeoutSeconds { get; set; }

        /// <summary>
        /// Arbitrary value; change it to force re-verification on the next update.
        /// </summary>
        [Input("trigger")]
        public Input<string>? Trigger { get; set; }

        /// <summary>
        /// Whether to verify DKIM. Defaults to true.
        /// </summary>
        [Input("verifyDkim")]
        public Input<bool>? VerifyDkim { get; set; }

        /// <summary>
        /// Whether to verify the Return-Path CNAME. Defaults to true.
        /// </summary>
        [Input("verifyReturnPath")]
        public Input<bool>? VerifyReturnPath { get; set; }

        public DomainVerificationArgs()
        {
        }
        public static new DomainVerificationArgs Empty => new DomainVerificationArgs();
    }
}
