// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace HummingbirdMe.Postmark
{
    [PostmarkResourceType("postmark:index:Domain")]
    public partial class Domain : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Hostname of the currently-active DKIM record (populated after verification).
        /// </summary>
        [Output("dkimHost")]
        public Output<string> DkimHost { get; private set; } = null!;

        /// <summary>
        /// Hostname for the DKIM TXT record to publish (publish this first).
        /// </summary>
        [Output("dkimPendingHost")]
        public Output<string> DkimPendingHost { get; private set; } = null!;

        /// <summary>
        /// Value for the DKIM TXT record to publish.
        /// </summary>
        [Output("dkimPendingTextValue")]
        public Output<string> DkimPendingTextValue { get; private set; } = null!;

        [Output("dkimRevokedHost")]
        public Output<string> DkimRevokedHost { get; private set; } = null!;

        [Output("dkimRevokedTextValue")]
        public Output<string> DkimRevokedTextValue { get; private set; } = null!;

        /// <summary>
        /// Value of the currently-active DKIM record.
        /// </summary>
        [Output("dkimTextValue")]
        public Output<string> DkimTextValue { get; private set; } = null!;

        [Output("dkimUpdateStatus")]
        public Output<string> DkimUpdateStatus { get; private set; } = null!;

        /// <summary>
        /// Whether DKIM has been verified by Postmark.
        /// </summary>
        [Output("dkimVerified")]
        public Output<bool> DkimVerified { get; private set; } = null!;

        [Output("domainId")]
        public Output<int> DomainId { get; private set; } = null!;

        /// <summary>
        /// The domain name to send from (e.g. `example.com`). Immutable — changing it replaces the domain.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Custom Return-Path subdomain (e.g. `pm-bounces.example.com`). Must be a subdomain of `name` and have a CNAME pointing at the value of `returnPathDomainCnameValue`.
        /// </summary>
        [Output("returnPathDomain")]
        public Output<string?> ReturnPathDomain { get; private set; } = null!;

        /// <summary>
        /// CNAME target for the Return-Path record (typically `pm.mtasv.net`).
        /// </summary>
        [Output("returnPathDomainCnameValue")]
        public Output<string> ReturnPathDomainCnameValue { get; private set; } = null!;

        /// <summary>
        /// Whether the Return-Path CNAME has been verified by Postmark.
        /// </summary>
        [Output("returnPathDomainVerified")]
        public Output<bool> ReturnPathDomainVerified { get; private set; } = null!;

        [Output("safeToRemoveRevokedKeyFromDns")]
        public Output<bool> SafeToRemoveRevokedKeyFromDns { get; private set; } = null!;

        [Output("weakDkim")]
        public Output<bool> WeakDkim { get; private set; } = null!;


        /// <summary>
        /// Create a Domain resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Domain(string name, DomainArgs args, CustomResourceOptions? options = null)
            : base("postmark:index:Domain", name, args ?? new DomainArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Domain(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("postmark:index:Domain", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/hummingbird-me/pulumi-postmark",
                ReplaceOnChanges =
                {
                    "name",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Domain resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Domain Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Domain(name, id, options);
        }
    }

    public sealed class DomainArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The domain name to send from (e.g. `example.com`). Immutable — changing it replaces the domain.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Custom Return-Path subdomain (e.g. `pm-bounces.example.com`). Must be a subdomain of `name` and have a CNAME pointing at the value of `returnPathDomainCnameValue`.
        /// </summary>
        [Input("returnPathDomain")]
        public Input<string>? ReturnPathDomain { get; set; }

        public DomainArgs()
        {
        }
        public static new DomainArgs Empty => new DomainArgs();
    }
}
