// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace HummingbirdMe.Postmark
{
    [PostmarkResourceType("pulumi:providers:postmark")]
    public partial class Provider : global::Pulumi.ProviderResource
    {
        /// <summary>
        /// Postmark Account API token (X-Postmark-Account-Token). Required to manage Servers, Domains and Sender Signatures. May also be set via the POSTMARK_ACCOUNT_TOKEN environment variable.
        /// </summary>
        [Output("accountToken")]
        public Output<string?> AccountToken { get; private set; } = null!;

        /// <summary>
        /// Base URL of the Postmark API. Defaults to https://api.postmarkapp.com. May also be set via the POSTMARK_BASE_URL environment variable (useful for testing).
        /// </summary>
        [Output("baseUrl")]
        public Output<string?> BaseUrl { get; private set; } = null!;

        /// <summary>
        /// Default Postmark Server API token (X-Postmark-Server-Token) used for Template operations when a Template does not set its own `serverToken`/`serverId`. Only useful when all Templates live on a single server. May also be set via the POSTMARK_SERVER_TOKEN environment variable.
        /// </summary>
        [Output("serverToken")]
        public Output<string?> ServerToken { get; private set; } = null!;


        /// <summary>
        /// Create a Provider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Provider(string name, ProviderArgs? args = null, CustomResourceOptions? options = null)
            : base("postmark", name, args ?? new ProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/hummingbird-me/pulumi-postmark",
                AdditionalSecretOutputs =
                {
                    "accountToken",
                    "serverToken",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ProviderArgs : global::Pulumi.ResourceArgs
    {
        [Input("accountToken")]
        private Input<string>? _accountToken;

        /// <summary>
        /// Postmark Account API token (X-Postmark-Account-Token). Required to manage Servers, Domains and Sender Signatures. May also be set via the POSTMARK_ACCOUNT_TOKEN environment variable.
        /// </summary>
        public Input<string>? AccountToken
        {
            get => _accountToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _accountToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Base URL of the Postmark API. Defaults to https://api.postmarkapp.com. May also be set via the POSTMARK_BASE_URL environment variable (useful for testing).
        /// </summary>
        [Input("baseUrl")]
        public Input<string>? BaseUrl { get; set; }

        [Input("serverToken")]
        private Input<string>? _serverToken;

        /// <summary>
        /// Default Postmark Server API token (X-Postmark-Server-Token) used for Template operations when a Template does not set its own `serverToken`/`serverId`. Only useful when all Templates live on a single server. May also be set via the POSTMARK_SERVER_TOKEN environment variable.
        /// </summary>
        public Input<string>? ServerToken
        {
            get => _serverToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _serverToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public ProviderArgs()
        {
            AccountToken = Utilities.GetEnv("POSTMARK_ACCOUNT_TOKEN") ?? "";
            BaseUrl = Utilities.GetEnv("POSTMARK_BASE_URL") ?? "https://api.postmarkapp.com";
            ServerToken = Utilities.GetEnv("POSTMARK_SERVER_TOKEN") ?? "";
        }
        public static new ProviderArgs Empty => new ProviderArgs();
    }
}
