// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace HummingbirdMe.Postmark
{
    [PostmarkResourceType("postmark:index:SenderSignature")]
    public partial class SenderSignature : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Optional note (max 400 chars) included in the confirmation email.
        /// </summary>
        [Output("confirmationPersonalNote")]
        public Output<string?> ConfirmationPersonalNote { get; private set; } = null!;

        /// <summary>
        /// Whether the signature has been confirmed. Postmark requires a human to click the confirmation email; run `pulumi refresh` to observe this flipping to true.
        /// </summary>
        [Output("confirmed")]
        public Output<bool> Confirmed { get; private set; } = null!;

        [Output("dkimHost")]
        public Output<string> DkimHost { get; private set; } = null!;

        [Output("dkimPendingHost")]
        public Output<string> DkimPendingHost { get; private set; } = null!;

        [Output("dkimPendingTextValue")]
        public Output<string> DkimPendingTextValue { get; private set; } = null!;

        [Output("dkimTextValue")]
        public Output<string> DkimTextValue { get; private set; } = null!;

        [Output("dkimVerified")]
        public Output<bool> DkimVerified { get; private set; } = null!;

        [Output("domain")]
        public Output<string> Domain { get; private set; } = null!;

        [Output("emailAddress")]
        public Output<string> EmailAddress { get; private set; } = null!;

        /// <summary>
        /// The email address to sign. Immutable — changing it replaces the signature.
        /// </summary>
        [Output("fromEmail")]
        public Output<string> FromEmail { get; private set; } = null!;

        /// <summary>
        /// From name associated with the signature.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Optional Reply-To email address.
        /// </summary>
        [Output("replyToEmail")]
        public Output<string?> ReplyToEmail { get; private set; } = null!;

        /// <summary>
        /// Optional custom Return-Path subdomain of the From address's domain.
        /// </summary>
        [Output("returnPathDomain")]
        public Output<string?> ReturnPathDomain { get; private set; } = null!;

        [Output("returnPathDomainCnameValue")]
        public Output<string> ReturnPathDomainCnameValue { get; private set; } = null!;

        [Output("returnPathDomainVerified")]
        public Output<bool> ReturnPathDomainVerified { get; private set; } = null!;

        [Output("signatureId")]
        public Output<int> SignatureId { get; private set; } = null!;

        /// <summary>
        /// Arbitrary value; change it to resend the confirmation email on the next update.
        /// </summary>
        [Output("triggerResend")]
        public Output<string?> TriggerResend { get; private set; } = null!;


        /// <summary>
        /// Create a SenderSignature resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SenderSignature(string name, SenderSignatureArgs args, CustomResourceOptions? options = null)
            : base("postmark:index:SenderSignature", name, args ?? new SenderSignatureArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SenderSignature(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("postmark:index:SenderSignature", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/hummingbird-me/pulumi-postmark",
                ReplaceOnChanges =
                {
                    "fromEmail",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SenderSignature resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SenderSignature Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new SenderSignature(name, id, options);
        }
    }

    public sealed class SenderSignatureArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Optional note (max 400 chars) included in the confirmation email.
        /// </summary>
        [Input("confirmationPersonalNote")]
        public Input<string>? ConfirmationPersonalNote { get; set; }

        /// <summary>
        /// The email address to sign. Immutable — changing it replaces the signature.
        /// </summary>
        [Input("fromEmail", required: true)]
        public Input<string> FromEmail { get; set; } = null!;

        /// <summary>
        /// From name associated with the signature.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Optional Reply-To email address.
        /// </summary>
        [Input("replyToEmail")]
        public Input<string>? ReplyToEmail { get; set; }

        /// <summary>
        /// Optional custom Return-Path subdomain of the From address's domain.
        /// </summary>
        [Input("returnPathDomain")]
        public Input<string>? ReturnPathDomain { get; set; }

        /// <summary>
        /// Arbitrary value; change it to resend the confirmation email on the next update.
        /// </summary>
        [Input("triggerResend")]
        public Input<string>? TriggerResend { get; set; }

        public SenderSignatureArgs()
        {
        }
        public static new SenderSignatureArgs Empty => new SenderSignatureArgs();
    }
}
