// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace HummingbirdMe.Postmark
{
    [PostmarkResourceType("postmark:index:Server")]
    public partial class Server : global::Pulumi.CustomResource
    {
        [Output("apiTokens")]
        public Output<ImmutableArray<string>> ApiTokens { get; private set; } = null!;

        /// <summary>
        /// Color of the server in the Postmark UI server list. One of: Purple, Blue, Turquoise, Green, Red, Yellow, Grey, Orange. Defaults to Blue.
        /// </summary>
        [Output("color")]
        public Output<string?> Color { get; private set; } = null!;

        /// <summary>
        /// Environment type: `Live` or `Sandbox`. Immutable after creation — changing it replaces the server. Defaults to `Live`.
        /// </summary>
        [Output("deliveryType")]
        public Output<string?> DeliveryType { get; private set; } = null!;

        [Output("enableSmtpApiErrorHooks")]
        public Output<bool?> EnableSmtpApiErrorHooks { get; private set; } = null!;

        [Output("inboundAddress")]
        public Output<string> InboundAddress { get; private set; } = null!;

        /// <summary>
        /// Inbound domain for MX setup. Point an MX record for this domain at `inbound.postmarkapp.com` to receive mail.
        /// </summary>
        [Output("inboundDomain")]
        public Output<string?> InboundDomain { get; private set; } = null!;

        [Output("inboundHash")]
        public Output<string> InboundHash { get; private set; } = null!;

        /// <summary>
        /// URL Postmark POSTs to for every inbound email event.
        /// </summary>
        [Output("inboundHookUrl")]
        public Output<string?> InboundHookUrl { get; private set; } = null!;

        /// <summary>
        /// Maximum spam score before an inbound message is blocked.
        /// </summary>
        [Output("inboundSpamThreshold")]
        public Output<int?> InboundSpamThreshold { get; private set; } = null!;

        [Output("includeBounceContentInHook")]
        public Output<bool?> IncludeBounceContentInHook { get; private set; } = null!;

        /// <summary>
        /// Friendly name of the server.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("postFirstOpenOnly")]
        public Output<bool?> PostFirstOpenOnly { get; private set; } = null!;

        [Output("rawEmailEnabled")]
        public Output<bool?> RawEmailEnabled { get; private set; } = null!;

        [Output("serverId")]
        public Output<int> ServerId { get; private set; } = null!;

        [Output("serverLink")]
        public Output<string> ServerLink { get; private set; } = null!;

        [Output("smtpApiActivated")]
        public Output<bool?> SmtpApiActivated { get; private set; } = null!;

        /// <summary>
        /// Link tracking mode: None, HtmlAndText, HtmlOnly or TextOnly. Defaults to None.
        /// </summary>
        [Output("trackLinks")]
        public Output<string?> TrackLinks { get; private set; } = null!;

        /// <summary>
        /// Enable open tracking for messages by default.
        /// </summary>
        [Output("trackOpens")]
        public Output<bool?> TrackOpens { get; private set; } = null!;


        /// <summary>
        /// Create a Server resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Server(string name, ServerArgs args, CustomResourceOptions? options = null)
            : base("postmark:index:Server", name, args ?? new ServerArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Server(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("postmark:index:Server", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/hummingbird-me/pulumi-postmark",
                AdditionalSecretOutputs =
                {
                    "apiTokens",
                },
                ReplaceOnChanges =
                {
                    "deliveryType",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Server resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Server Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Server(name, id, options);
        }
    }

    public sealed class ServerArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Color of the server in the Postmark UI server list. One of: Purple, Blue, Turquoise, Green, Red, Yellow, Grey, Orange. Defaults to Blue.
        /// </summary>
        [Input("color")]
        public Input<string>? Color { get; set; }

        /// <summary>
        /// Environment type: `Live` or `Sandbox`. Immutable after creation — changing it replaces the server. Defaults to `Live`.
        /// </summary>
        [Input("deliveryType")]
        public Input<string>? DeliveryType { get; set; }

        [Input("enableSmtpApiErrorHooks")]
        public Input<bool>? EnableSmtpApiErrorHooks { get; set; }

        /// <summary>
        /// Inbound domain for MX setup. Point an MX record for this domain at `inbound.postmarkapp.com` to receive mail.
        /// </summary>
        [Input("inboundDomain")]
        public Input<string>? InboundDomain { get; set; }

        /// <summary>
        /// URL Postmark POSTs to for every inbound email event.
        /// </summary>
        [Input("inboundHookUrl")]
        public Input<string>? InboundHookUrl { get; set; }

        /// <summary>
        /// Maximum spam score before an inbound message is blocked.
        /// </summary>
        [Input("inboundSpamThreshold")]
        public Input<int>? InboundSpamThreshold { get; set; }

        [Input("includeBounceContentInHook")]
        public Input<bool>? IncludeBounceContentInHook { get; set; }

        /// <summary>
        /// Friendly name of the server.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("postFirstOpenOnly")]
        public Input<bool>? PostFirstOpenOnly { get; set; }

        [Input("rawEmailEnabled")]
        public Input<bool>? RawEmailEnabled { get; set; }

        [Input("smtpApiActivated")]
        public Input<bool>? SmtpApiActivated { get; set; }

        /// <summary>
        /// Link tracking mode: None, HtmlAndText, HtmlOnly or TextOnly. Defaults to None.
        /// </summary>
        [Input("trackLinks")]
        public Input<string>? TrackLinks { get; set; }

        /// <summary>
        /// Enable open tracking for messages by default.
        /// </summary>
        [Input("trackOpens")]
        public Input<bool>? TrackOpens { get; set; }

        public ServerArgs()
        {
        }
        public static new ServerArgs Empty => new ServerArgs();
    }
}
