// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace HummingbirdMe.Postmark
{
    [PostmarkResourceType("postmark:index:Template")]
    public partial class Template : global::Pulumi.CustomResource
    {
        [Output("active")]
        public Output<bool> Active { get; private set; } = null!;

        /// <summary>
        /// Optional unique alias (within the server). Must start with a letter; may contain letters, digits, '.', '-' and '_'.
        /// </summary>
        [Output("alias")]
        public Output<string?> Alias { get; private set; } = null!;

        [Output("associatedServerId")]
        public Output<int> AssociatedServerId { get; private set; } = null!;

        /// <summary>
        /// HTML body. Required unless `textBody` is set.
        /// </summary>
        [Output("htmlBody")]
        public Output<string?> HtmlBody { get; private set; } = null!;

        /// <summary>
        /// Alias of a Layout to wrap this Standard template (set to "" to disassociate).
        /// </summary>
        [Output("layoutTemplate")]
        public Output<string?> LayoutTemplate { get; private set; } = null!;

        /// <summary>
        /// Name of the template.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// ID of the server this template belongs to; the provider looks up its token via the account token. Immutable — changing it replaces the template.
        /// </summary>
        [Output("serverId")]
        public Output<int?> ServerId { get; private set; } = null!;

        /// <summary>
        /// Server API token of the server this template belongs to. Wire from `server.apiTokens[0]`. Falls back to `serverId` lookup, then the provider `serverToken` config.
        /// </summary>
        [Output("serverToken")]
        public Output<string?> ServerToken { get; private set; } = null!;

        /// <summary>
        /// Subject line. Required for Standard templates; not allowed for Layouts.
        /// </summary>
        [Output("subject")]
        public Output<string?> Subject { get; private set; } = null!;

        [Output("templateId")]
        public Output<int> TemplateId { get; private set; } = null!;

        /// <summary>
        /// `Standard` (default) or `Layout`. Immutable — changing it replaces the template.
        /// </summary>
        [Output("templateType")]
        public Output<string?> TemplateType { get; private set; } = null!;

        /// <summary>
        /// Plain-text body. Required unless `htmlBody` is set.
        /// </summary>
        [Output("textBody")]
        public Output<string?> TextBody { get; private set; } = null!;


        /// <summary>
        /// Create a Template resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Template(string name, TemplateArgs args, CustomResourceOptions? options = null)
            : base("postmark:index:Template", name, args ?? new TemplateArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Template(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("postmark:index:Template", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/hummingbird-me/pulumi-postmark",
                AdditionalSecretOutputs =
                {
                    "serverToken",
                },
                ReplaceOnChanges =
                {
                    "serverId",
                    "templateType",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Template resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Template Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Template(name, id, options);
        }
    }

    public sealed class TemplateArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Optional unique alias (within the server). Must start with a letter; may contain letters, digits, '.', '-' and '_'.
        /// </summary>
        [Input("alias")]
        public Input<string>? Alias { get; set; }

        /// <summary>
        /// HTML body. Required unless `textBody` is set.
        /// </summary>
        [Input("htmlBody")]
        public Input<string>? HtmlBody { get; set; }

        /// <summary>
        /// Alias of a Layout to wrap this Standard template (set to "" to disassociate).
        /// </summary>
        [Input("layoutTemplate")]
        public Input<string>? LayoutTemplate { get; set; }

        /// <summary>
        /// Name of the template.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// ID of the server this template belongs to; the provider looks up its token via the account token. Immutable — changing it replaces the template.
        /// </summary>
        [Input("serverId")]
        public Input<int>? ServerId { get; set; }

        [Input("serverToken")]
        private Input<string>? _serverToken;

        /// <summary>
        /// Server API token of the server this template belongs to. Wire from `server.apiTokens[0]`. Falls back to `serverId` lookup, then the provider `serverToken` config.
        /// </summary>
        public Input<string>? ServerToken
        {
            get => _serverToken;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _serverToken = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Subject line. Required for Standard templates; not allowed for Layouts.
        /// </summary>
        [Input("subject")]
        public Input<string>? Subject { get; set; }

        /// <summary>
        /// `Standard` (default) or `Layout`. Immutable — changing it replaces the template.
        /// </summary>
        [Input("templateType")]
        public Input<string>? TemplateType { get; set; }

        /// <summary>
        /// Plain-text body. Required unless `htmlBody` is set.
        /// </summary>
        [Input("textBody")]
        public Input<string>? TextBody { get; set; }

        public TemplateArgs()
        {
        }
        public static new TemplateArgs Empty => new TemplateArgs();
    }
}
