// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace HummingbirdMe.Postmark
{
    public static class Config
    {
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly global::Pulumi.Config __config = new global::Pulumi.Config("postmark");

        private static readonly __Value<string?> _accountToken = new __Value<string?>(() => __config.Get("accountToken") ?? Utilities.GetEnv("POSTMARK_ACCOUNT_TOKEN") ?? "");
        /// <summary>
        /// Postmark Account API token (X-Postmark-Account-Token). Required to manage Servers, Domains and Sender Signatures. May also be set via the POSTMARK_ACCOUNT_TOKEN environment variable.
        /// </summary>
        public static string? AccountToken
        {
            get => _accountToken.Get();
            set => _accountToken.Set(value);
        }

        private static readonly __Value<string?> _baseUrl = new __Value<string?>(() => __config.Get("baseUrl") ?? Utilities.GetEnv("POSTMARK_BASE_URL") ?? "https://api.postmarkapp.com");
        /// <summary>
        /// Base URL of the Postmark API. Defaults to https://api.postmarkapp.com. May also be set via the POSTMARK_BASE_URL environment variable (useful for testing).
        /// </summary>
        public static string? BaseUrl
        {
            get => _baseUrl.Get();
            set => _baseUrl.Set(value);
        }

        private static readonly __Value<string?> _serverToken = new __Value<string?>(() => __config.Get("serverToken") ?? Utilities.GetEnv("POSTMARK_SERVER_TOKEN") ?? "");
        /// <summary>
        /// Default Postmark Server API token (X-Postmark-Server-Token) used for Template operations when a Template does not set its own `serverToken`/`serverId`. Only useful when all Templates live on a single server. May also be set via the POSTMARK_SERVER_TOKEN environment variable.
        /// </summary>
        public static string? ServerToken
        {
            get => _serverToken.Get();
            set => _serverToken.Set(value);
        }

    }
}
