// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/hummingbird-me/pulumi-postmark/sdk/go/postmark/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Postmark Account API token (X-Postmark-Account-Token). Required to manage Servers, Domains and Sender Signatures. May also be set via the POSTMARK_ACCOUNT_TOKEN environment variable.
func GetAccountToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "postmark:accountToken")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("", nil, "POSTMARK_ACCOUNT_TOKEN"); d != nil {
		value = d.(string)
	}
	return value
}

// Base URL of the Postmark API. Defaults to https://api.postmarkapp.com. May also be set via the POSTMARK_BASE_URL environment variable (useful for testing).
func GetBaseUrl(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "postmark:baseUrl")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("https://api.postmarkapp.com", nil, "POSTMARK_BASE_URL"); d != nil {
		value = d.(string)
	}
	return value
}

// Default Postmark Server API token (X-Postmark-Server-Token) used for Template operations when a Template does not set its own `serverToken`/`serverId`. Only useful when all Templates live on a single server. May also be set via the POSTMARK_SERVER_TOKEN environment variable.
func GetServerToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "postmark:serverToken")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("", nil, "POSTMARK_SERVER_TOKEN"); d != nil {
		value = d.(string)
	}
	return value
}
