# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .domain import *
from .domain_verification import *
from .provider import *
from .sender_signature import *
from .server import *
from .template import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import hummingbird_me_postmark.config as __config
    config = __config
else:
    config = _utilities.lazy_import('hummingbird_me_postmark.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "postmark",
  "mod": "index",
  "fqn": "hummingbird_me_postmark",
  "classes": {
   "postmark:index:Domain": "Domain",
   "postmark:index:DomainVerification": "DomainVerification",
   "postmark:index:SenderSignature": "SenderSignature",
   "postmark:index:Server": "Server",
   "postmark:index:Template": "Template"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "postmark",
  "token": "pulumi:providers:postmark",
  "fqn": "hummingbird_me_postmark",
  "class": "Provider"
 }
]
"""
)
