# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['DomainArgs', 'Domain']

@pulumi.input_type
class DomainArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 return_path_domain: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Domain resource.

        :param pulumi.Input[_builtins.str] name: The domain name to send from (e.g. `example.com`). Immutable — changing it replaces the domain.
        :param pulumi.Input[_builtins.str] return_path_domain: Custom Return-Path subdomain (e.g. `pm-bounces.example.com`). Must be a subdomain of `name` and have a CNAME pointing at the value of `returnPathDomainCnameValue`.
        """
        pulumi.set(__self__, "name", name)
        if return_path_domain is not None:
            pulumi.set(__self__, "return_path_domain", return_path_domain)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        The domain name to send from (e.g. `example.com`). Immutable — changing it replaces the domain.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="returnPathDomain")
    def return_path_domain(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Custom Return-Path subdomain (e.g. `pm-bounces.example.com`). Must be a subdomain of `name` and have a CNAME pointing at the value of `returnPathDomainCnameValue`.
        """
        return pulumi.get(self, "return_path_domain")

    @return_path_domain.setter
    def return_path_domain(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "return_path_domain", value)


@pulumi.type_token("postmark:index:Domain")
class Domain(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 return_path_domain: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Domain resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] name: The domain name to send from (e.g. `example.com`). Immutable — changing it replaces the domain.
        :param pulumi.Input[_builtins.str] return_path_domain: Custom Return-Path subdomain (e.g. `pm-bounces.example.com`). Must be a subdomain of `name` and have a CNAME pointing at the value of `returnPathDomainCnameValue`.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DomainArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Domain resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param DomainArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DomainArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 return_path_domain: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DomainArgs.__new__(DomainArgs)

            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["return_path_domain"] = return_path_domain
            __props__.__dict__["dkim_host"] = None
            __props__.__dict__["dkim_pending_host"] = None
            __props__.__dict__["dkim_pending_text_value"] = None
            __props__.__dict__["dkim_revoked_host"] = None
            __props__.__dict__["dkim_revoked_text_value"] = None
            __props__.__dict__["dkim_text_value"] = None
            __props__.__dict__["dkim_update_status"] = None
            __props__.__dict__["dkim_verified"] = None
            __props__.__dict__["domain_id"] = None
            __props__.__dict__["return_path_domain_cname_value"] = None
            __props__.__dict__["return_path_domain_verified"] = None
            __props__.__dict__["safe_to_remove_revoked_key_from_dns"] = None
            __props__.__dict__["weak_dkim"] = None
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["name"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(Domain, __self__).__init__(
            'postmark:index:Domain',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Domain':
        """
        Get an existing Domain resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = DomainArgs.__new__(DomainArgs)

        __props__.__dict__["dkim_host"] = None
        __props__.__dict__["dkim_pending_host"] = None
        __props__.__dict__["dkim_pending_text_value"] = None
        __props__.__dict__["dkim_revoked_host"] = None
        __props__.__dict__["dkim_revoked_text_value"] = None
        __props__.__dict__["dkim_text_value"] = None
        __props__.__dict__["dkim_update_status"] = None
        __props__.__dict__["dkim_verified"] = None
        __props__.__dict__["domain_id"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["return_path_domain"] = None
        __props__.__dict__["return_path_domain_cname_value"] = None
        __props__.__dict__["return_path_domain_verified"] = None
        __props__.__dict__["safe_to_remove_revoked_key_from_dns"] = None
        __props__.__dict__["weak_dkim"] = None
        return Domain(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="dkimHost")
    def dkim_host(self) -> pulumi.Output[_builtins.str]:
        """
        Hostname of the currently-active DKIM record (populated after verification).
        """
        return pulumi.get(self, "dkim_host")

    @_builtins.property
    @pulumi.getter(name="dkimPendingHost")
    def dkim_pending_host(self) -> pulumi.Output[_builtins.str]:
        """
        Hostname for the DKIM TXT record to publish (publish this first).
        """
        return pulumi.get(self, "dkim_pending_host")

    @_builtins.property
    @pulumi.getter(name="dkimPendingTextValue")
    def dkim_pending_text_value(self) -> pulumi.Output[_builtins.str]:
        """
        Value for the DKIM TXT record to publish.
        """
        return pulumi.get(self, "dkim_pending_text_value")

    @_builtins.property
    @pulumi.getter(name="dkimRevokedHost")
    def dkim_revoked_host(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "dkim_revoked_host")

    @_builtins.property
    @pulumi.getter(name="dkimRevokedTextValue")
    def dkim_revoked_text_value(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "dkim_revoked_text_value")

    @_builtins.property
    @pulumi.getter(name="dkimTextValue")
    def dkim_text_value(self) -> pulumi.Output[_builtins.str]:
        """
        Value of the currently-active DKIM record.
        """
        return pulumi.get(self, "dkim_text_value")

    @_builtins.property
    @pulumi.getter(name="dkimUpdateStatus")
    def dkim_update_status(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "dkim_update_status")

    @_builtins.property
    @pulumi.getter(name="dkimVerified")
    def dkim_verified(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether DKIM has been verified by Postmark.
        """
        return pulumi.get(self, "dkim_verified")

    @_builtins.property
    @pulumi.getter(name="domainId")
    def domain_id(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "domain_id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The domain name to send from (e.g. `example.com`). Immutable — changing it replaces the domain.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="returnPathDomain")
    def return_path_domain(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Custom Return-Path subdomain (e.g. `pm-bounces.example.com`). Must be a subdomain of `name` and have a CNAME pointing at the value of `returnPathDomainCnameValue`.
        """
        return pulumi.get(self, "return_path_domain")

    @_builtins.property
    @pulumi.getter(name="returnPathDomainCnameValue")
    def return_path_domain_cname_value(self) -> pulumi.Output[_builtins.str]:
        """
        CNAME target for the Return-Path record (typically `pm.mtasv.net`).
        """
        return pulumi.get(self, "return_path_domain_cname_value")

    @_builtins.property
    @pulumi.getter(name="returnPathDomainVerified")
    def return_path_domain_verified(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the Return-Path CNAME has been verified by Postmark.
        """
        return pulumi.get(self, "return_path_domain_verified")

    @_builtins.property
    @pulumi.getter(name="safeToRemoveRevokedKeyFromDns")
    def safe_to_remove_revoked_key_from_dns(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "safe_to_remove_revoked_key_from_dns")

    @_builtins.property
    @pulumi.getter(name="weakDkim")
    def weak_dkim(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "weak_dkim")

