# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['DomainVerificationArgs', 'DomainVerification']

@pulumi.input_type
class DomainVerificationArgs:
    def __init__(__self__, *,
                 domain_id: pulumi.Input[_builtins.int],
                 poll_timeout_seconds: Optional[pulumi.Input[_builtins.int]] = None,
                 trigger: Optional[pulumi.Input[_builtins.str]] = None,
                 verify_dkim: Optional[pulumi.Input[_builtins.bool]] = None,
                 verify_return_path: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        The set of arguments for constructing a DomainVerification resource.

        :param pulumi.Input[_builtins.int] domain_id: ID of the Domain to verify (wire from `domain.domainId`). Immutable.
        :param pulumi.Input[_builtins.int] poll_timeout_seconds: Maximum seconds to poll for verification to succeed while DNS propagates. Defaults to 0 (a single, non-blocking attempt).
        :param pulumi.Input[_builtins.str] trigger: Arbitrary value; change it to force re-verification on the next update.
        :param pulumi.Input[_builtins.bool] verify_dkim: Whether to verify DKIM. Defaults to true.
        :param pulumi.Input[_builtins.bool] verify_return_path: Whether to verify the Return-Path CNAME. Defaults to true.
        """
        pulumi.set(__self__, "domain_id", domain_id)
        if poll_timeout_seconds is not None:
            pulumi.set(__self__, "poll_timeout_seconds", poll_timeout_seconds)
        if trigger is not None:
            pulumi.set(__self__, "trigger", trigger)
        if verify_dkim is not None:
            pulumi.set(__self__, "verify_dkim", verify_dkim)
        if verify_return_path is not None:
            pulumi.set(__self__, "verify_return_path", verify_return_path)

    @_builtins.property
    @pulumi.getter(name="domainId")
    def domain_id(self) -> pulumi.Input[_builtins.int]:
        """
        ID of the Domain to verify (wire from `domain.domainId`). Immutable.
        """
        return pulumi.get(self, "domain_id")

    @domain_id.setter
    def domain_id(self, value: pulumi.Input[_builtins.int]):
        pulumi.set(self, "domain_id", value)

    @_builtins.property
    @pulumi.getter(name="pollTimeoutSeconds")
    def poll_timeout_seconds(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Maximum seconds to poll for verification to succeed while DNS propagates. Defaults to 0 (a single, non-blocking attempt).
        """
        return pulumi.get(self, "poll_timeout_seconds")

    @poll_timeout_seconds.setter
    def poll_timeout_seconds(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "poll_timeout_seconds", value)

    @_builtins.property
    @pulumi.getter
    def trigger(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Arbitrary value; change it to force re-verification on the next update.
        """
        return pulumi.get(self, "trigger")

    @trigger.setter
    def trigger(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "trigger", value)

    @_builtins.property
    @pulumi.getter(name="verifyDkim")
    def verify_dkim(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether to verify DKIM. Defaults to true.
        """
        return pulumi.get(self, "verify_dkim")

    @verify_dkim.setter
    def verify_dkim(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "verify_dkim", value)

    @_builtins.property
    @pulumi.getter(name="verifyReturnPath")
    def verify_return_path(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether to verify the Return-Path CNAME. Defaults to true.
        """
        return pulumi.get(self, "verify_return_path")

    @verify_return_path.setter
    def verify_return_path(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "verify_return_path", value)


@pulumi.type_token("postmark:index:DomainVerification")
class DomainVerification(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 domain_id: Optional[pulumi.Input[_builtins.int]] = None,
                 poll_timeout_seconds: Optional[pulumi.Input[_builtins.int]] = None,
                 trigger: Optional[pulumi.Input[_builtins.str]] = None,
                 verify_dkim: Optional[pulumi.Input[_builtins.bool]] = None,
                 verify_return_path: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        """
        Create a DomainVerification resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.int] domain_id: ID of the Domain to verify (wire from `domain.domainId`). Immutable.
        :param pulumi.Input[_builtins.int] poll_timeout_seconds: Maximum seconds to poll for verification to succeed while DNS propagates. Defaults to 0 (a single, non-blocking attempt).
        :param pulumi.Input[_builtins.str] trigger: Arbitrary value; change it to force re-verification on the next update.
        :param pulumi.Input[_builtins.bool] verify_dkim: Whether to verify DKIM. Defaults to true.
        :param pulumi.Input[_builtins.bool] verify_return_path: Whether to verify the Return-Path CNAME. Defaults to true.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DomainVerificationArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a DomainVerification resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param DomainVerificationArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DomainVerificationArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 domain_id: Optional[pulumi.Input[_builtins.int]] = None,
                 poll_timeout_seconds: Optional[pulumi.Input[_builtins.int]] = None,
                 trigger: Optional[pulumi.Input[_builtins.str]] = None,
                 verify_dkim: Optional[pulumi.Input[_builtins.bool]] = None,
                 verify_return_path: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DomainVerificationArgs.__new__(DomainVerificationArgs)

            if domain_id is None and not opts.urn:
                raise TypeError("Missing required property 'domain_id'")
            __props__.__dict__["domain_id"] = domain_id
            __props__.__dict__["poll_timeout_seconds"] = poll_timeout_seconds
            __props__.__dict__["trigger"] = trigger
            __props__.__dict__["verify_dkim"] = verify_dkim
            __props__.__dict__["verify_return_path"] = verify_return_path
            __props__.__dict__["dkim_host"] = None
            __props__.__dict__["dkim_text_value"] = None
            __props__.__dict__["dkim_verified"] = None
            __props__.__dict__["return_path_domain_verified"] = None
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["domainId"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(DomainVerification, __self__).__init__(
            'postmark:index:DomainVerification',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'DomainVerification':
        """
        Get an existing DomainVerification resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = DomainVerificationArgs.__new__(DomainVerificationArgs)

        __props__.__dict__["dkim_host"] = None
        __props__.__dict__["dkim_text_value"] = None
        __props__.__dict__["dkim_verified"] = None
        __props__.__dict__["domain_id"] = None
        __props__.__dict__["poll_timeout_seconds"] = None
        __props__.__dict__["return_path_domain_verified"] = None
        __props__.__dict__["trigger"] = None
        __props__.__dict__["verify_dkim"] = None
        __props__.__dict__["verify_return_path"] = None
        return DomainVerification(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="dkimHost")
    def dkim_host(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "dkim_host")

    @_builtins.property
    @pulumi.getter(name="dkimTextValue")
    def dkim_text_value(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "dkim_text_value")

    @_builtins.property
    @pulumi.getter(name="dkimVerified")
    def dkim_verified(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "dkim_verified")

    @_builtins.property
    @pulumi.getter(name="domainId")
    def domain_id(self) -> pulumi.Output[_builtins.int]:
        """
        ID of the Domain to verify (wire from `domain.domainId`). Immutable.
        """
        return pulumi.get(self, "domain_id")

    @_builtins.property
    @pulumi.getter(name="pollTimeoutSeconds")
    def poll_timeout_seconds(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Maximum seconds to poll for verification to succeed while DNS propagates. Defaults to 0 (a single, non-blocking attempt).
        """
        return pulumi.get(self, "poll_timeout_seconds")

    @_builtins.property
    @pulumi.getter(name="returnPathDomainVerified")
    def return_path_domain_verified(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "return_path_domain_verified")

    @_builtins.property
    @pulumi.getter
    def trigger(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Arbitrary value; change it to force re-verification on the next update.
        """
        return pulumi.get(self, "trigger")

    @_builtins.property
    @pulumi.getter(name="verifyDkim")
    def verify_dkim(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether to verify DKIM. Defaults to true.
        """
        return pulumi.get(self, "verify_dkim")

    @_builtins.property
    @pulumi.getter(name="verifyReturnPath")
    def verify_return_path(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether to verify the Return-Path CNAME. Defaults to true.
        """
        return pulumi.get(self, "verify_return_path")

