# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ProviderArgs', 'Provider']

@pulumi.input_type
class ProviderArgs:
    def __init__(__self__, *,
                 account_token: Optional[pulumi.Input[_builtins.str]] = None,
                 base_url: Optional[pulumi.Input[_builtins.str]] = None,
                 server_token: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Provider resource.

        :param pulumi.Input[_builtins.str] account_token: Postmark Account API token (X-Postmark-Account-Token). Required to manage Servers, Domains and Sender Signatures. May also be set via the POSTMARK_ACCOUNT_TOKEN environment variable.
        :param pulumi.Input[_builtins.str] base_url: Base URL of the Postmark API. Defaults to https://api.postmarkapp.com. May also be set via the POSTMARK_BASE_URL environment variable (useful for testing).
        :param pulumi.Input[_builtins.str] server_token: Default Postmark Server API token (X-Postmark-Server-Token) used for Template operations when a Template does not set its own `serverToken`/`serverId`. Only useful when all Templates live on a single server. May also be set via the POSTMARK_SERVER_TOKEN environment variable.
        """
        if account_token is None:
            account_token = (_utilities.get_env('POSTMARK_ACCOUNT_TOKEN') or '')
        if account_token is not None:
            pulumi.set(__self__, "account_token", account_token)
        if base_url is None:
            base_url = (_utilities.get_env('POSTMARK_BASE_URL') or 'https://api.postmarkapp.com')
        if base_url is not None:
            pulumi.set(__self__, "base_url", base_url)
        if server_token is None:
            server_token = (_utilities.get_env('POSTMARK_SERVER_TOKEN') or '')
        if server_token is not None:
            pulumi.set(__self__, "server_token", server_token)

    @_builtins.property
    @pulumi.getter(name="accountToken")
    def account_token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Postmark Account API token (X-Postmark-Account-Token). Required to manage Servers, Domains and Sender Signatures. May also be set via the POSTMARK_ACCOUNT_TOKEN environment variable.
        """
        return pulumi.get(self, "account_token")

    @account_token.setter
    def account_token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "account_token", value)

    @_builtins.property
    @pulumi.getter(name="baseUrl")
    def base_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Base URL of the Postmark API. Defaults to https://api.postmarkapp.com. May also be set via the POSTMARK_BASE_URL environment variable (useful for testing).
        """
        return pulumi.get(self, "base_url")

    @base_url.setter
    def base_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "base_url", value)

    @_builtins.property
    @pulumi.getter(name="serverToken")
    def server_token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Default Postmark Server API token (X-Postmark-Server-Token) used for Template operations when a Template does not set its own `serverToken`/`serverId`. Only useful when all Templates live on a single server. May also be set via the POSTMARK_SERVER_TOKEN environment variable.
        """
        return pulumi.get(self, "server_token")

    @server_token.setter
    def server_token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "server_token", value)


@pulumi.type_token("pulumi:providers:postmark")
class Provider(pulumi.ProviderResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_token: Optional[pulumi.Input[_builtins.str]] = None,
                 base_url: Optional[pulumi.Input[_builtins.str]] = None,
                 server_token: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Postmark resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] account_token: Postmark Account API token (X-Postmark-Account-Token). Required to manage Servers, Domains and Sender Signatures. May also be set via the POSTMARK_ACCOUNT_TOKEN environment variable.
        :param pulumi.Input[_builtins.str] base_url: Base URL of the Postmark API. Defaults to https://api.postmarkapp.com. May also be set via the POSTMARK_BASE_URL environment variable (useful for testing).
        :param pulumi.Input[_builtins.str] server_token: Default Postmark Server API token (X-Postmark-Server-Token) used for Template operations when a Template does not set its own `serverToken`/`serverId`. Only useful when all Templates live on a single server. May also be set via the POSTMARK_SERVER_TOKEN environment variable.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ProviderArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Postmark resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ProviderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProviderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 account_token: Optional[pulumi.Input[_builtins.str]] = None,
                 base_url: Optional[pulumi.Input[_builtins.str]] = None,
                 server_token: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProviderArgs.__new__(ProviderArgs)

            if account_token is None:
                account_token = (_utilities.get_env('POSTMARK_ACCOUNT_TOKEN') or '')
            __props__.__dict__["account_token"] = None if account_token is None else pulumi.Output.secret(account_token)
            if base_url is None:
                base_url = (_utilities.get_env('POSTMARK_BASE_URL') or 'https://api.postmarkapp.com')
            __props__.__dict__["base_url"] = base_url
            if server_token is None:
                server_token = (_utilities.get_env('POSTMARK_SERVER_TOKEN') or '')
            __props__.__dict__["server_token"] = None if server_token is None else pulumi.Output.secret(server_token)
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["accountToken", "serverToken"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Provider, __self__).__init__(
            'postmark',
            resource_name,
            __props__,
            opts)

    @_builtins.property
    @pulumi.getter(name="accountToken")
    def account_token(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Postmark Account API token (X-Postmark-Account-Token). Required to manage Servers, Domains and Sender Signatures. May also be set via the POSTMARK_ACCOUNT_TOKEN environment variable.
        """
        return pulumi.get(self, "account_token")

    @_builtins.property
    @pulumi.getter(name="baseUrl")
    def base_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Base URL of the Postmark API. Defaults to https://api.postmarkapp.com. May also be set via the POSTMARK_BASE_URL environment variable (useful for testing).
        """
        return pulumi.get(self, "base_url")

    @_builtins.property
    @pulumi.getter(name="serverToken")
    def server_token(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Default Postmark Server API token (X-Postmark-Server-Token) used for Template operations when a Template does not set its own `serverToken`/`serverId`. Only useful when all Templates live on a single server. May also be set via the POSTMARK_SERVER_TOKEN environment variable.
        """
        return pulumi.get(self, "server_token")

