# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['SenderSignatureArgs', 'SenderSignature']

@pulumi.input_type
class SenderSignatureArgs:
    def __init__(__self__, *,
                 from_email: pulumi.Input[_builtins.str],
                 name: pulumi.Input[_builtins.str],
                 confirmation_personal_note: Optional[pulumi.Input[_builtins.str]] = None,
                 reply_to_email: Optional[pulumi.Input[_builtins.str]] = None,
                 return_path_domain: Optional[pulumi.Input[_builtins.str]] = None,
                 trigger_resend: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a SenderSignature resource.

        :param pulumi.Input[_builtins.str] from_email: The email address to sign. Immutable — changing it replaces the signature.
        :param pulumi.Input[_builtins.str] name: From name associated with the signature.
        :param pulumi.Input[_builtins.str] confirmation_personal_note: Optional note (max 400 chars) included in the confirmation email.
        :param pulumi.Input[_builtins.str] reply_to_email: Optional Reply-To email address.
        :param pulumi.Input[_builtins.str] return_path_domain: Optional custom Return-Path subdomain of the From address's domain.
        :param pulumi.Input[_builtins.str] trigger_resend: Arbitrary value; change it to resend the confirmation email on the next update.
        """
        pulumi.set(__self__, "from_email", from_email)
        pulumi.set(__self__, "name", name)
        if confirmation_personal_note is not None:
            pulumi.set(__self__, "confirmation_personal_note", confirmation_personal_note)
        if reply_to_email is not None:
            pulumi.set(__self__, "reply_to_email", reply_to_email)
        if return_path_domain is not None:
            pulumi.set(__self__, "return_path_domain", return_path_domain)
        if trigger_resend is not None:
            pulumi.set(__self__, "trigger_resend", trigger_resend)

    @_builtins.property
    @pulumi.getter(name="fromEmail")
    def from_email(self) -> pulumi.Input[_builtins.str]:
        """
        The email address to sign. Immutable — changing it replaces the signature.
        """
        return pulumi.get(self, "from_email")

    @from_email.setter
    def from_email(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "from_email", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        From name associated with the signature.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="confirmationPersonalNote")
    def confirmation_personal_note(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Optional note (max 400 chars) included in the confirmation email.
        """
        return pulumi.get(self, "confirmation_personal_note")

    @confirmation_personal_note.setter
    def confirmation_personal_note(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "confirmation_personal_note", value)

    @_builtins.property
    @pulumi.getter(name="replyToEmail")
    def reply_to_email(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Optional Reply-To email address.
        """
        return pulumi.get(self, "reply_to_email")

    @reply_to_email.setter
    def reply_to_email(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "reply_to_email", value)

    @_builtins.property
    @pulumi.getter(name="returnPathDomain")
    def return_path_domain(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Optional custom Return-Path subdomain of the From address's domain.
        """
        return pulumi.get(self, "return_path_domain")

    @return_path_domain.setter
    def return_path_domain(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "return_path_domain", value)

    @_builtins.property
    @pulumi.getter(name="triggerResend")
    def trigger_resend(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Arbitrary value; change it to resend the confirmation email on the next update.
        """
        return pulumi.get(self, "trigger_resend")

    @trigger_resend.setter
    def trigger_resend(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "trigger_resend", value)


@pulumi.type_token("postmark:index:SenderSignature")
class SenderSignature(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 confirmation_personal_note: Optional[pulumi.Input[_builtins.str]] = None,
                 from_email: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 reply_to_email: Optional[pulumi.Input[_builtins.str]] = None,
                 return_path_domain: Optional[pulumi.Input[_builtins.str]] = None,
                 trigger_resend: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a SenderSignature resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] confirmation_personal_note: Optional note (max 400 chars) included in the confirmation email.
        :param pulumi.Input[_builtins.str] from_email: The email address to sign. Immutable — changing it replaces the signature.
        :param pulumi.Input[_builtins.str] name: From name associated with the signature.
        :param pulumi.Input[_builtins.str] reply_to_email: Optional Reply-To email address.
        :param pulumi.Input[_builtins.str] return_path_domain: Optional custom Return-Path subdomain of the From address's domain.
        :param pulumi.Input[_builtins.str] trigger_resend: Arbitrary value; change it to resend the confirmation email on the next update.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SenderSignatureArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a SenderSignature resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param SenderSignatureArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SenderSignatureArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 confirmation_personal_note: Optional[pulumi.Input[_builtins.str]] = None,
                 from_email: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 reply_to_email: Optional[pulumi.Input[_builtins.str]] = None,
                 return_path_domain: Optional[pulumi.Input[_builtins.str]] = None,
                 trigger_resend: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SenderSignatureArgs.__new__(SenderSignatureArgs)

            __props__.__dict__["confirmation_personal_note"] = confirmation_personal_note
            if from_email is None and not opts.urn:
                raise TypeError("Missing required property 'from_email'")
            __props__.__dict__["from_email"] = from_email
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["reply_to_email"] = reply_to_email
            __props__.__dict__["return_path_domain"] = return_path_domain
            __props__.__dict__["trigger_resend"] = trigger_resend
            __props__.__dict__["confirmed"] = None
            __props__.__dict__["dkim_host"] = None
            __props__.__dict__["dkim_pending_host"] = None
            __props__.__dict__["dkim_pending_text_value"] = None
            __props__.__dict__["dkim_text_value"] = None
            __props__.__dict__["dkim_verified"] = None
            __props__.__dict__["domain"] = None
            __props__.__dict__["email_address"] = None
            __props__.__dict__["return_path_domain_cname_value"] = None
            __props__.__dict__["return_path_domain_verified"] = None
            __props__.__dict__["signature_id"] = None
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["fromEmail"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(SenderSignature, __self__).__init__(
            'postmark:index:SenderSignature',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'SenderSignature':
        """
        Get an existing SenderSignature resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = SenderSignatureArgs.__new__(SenderSignatureArgs)

        __props__.__dict__["confirmation_personal_note"] = None
        __props__.__dict__["confirmed"] = None
        __props__.__dict__["dkim_host"] = None
        __props__.__dict__["dkim_pending_host"] = None
        __props__.__dict__["dkim_pending_text_value"] = None
        __props__.__dict__["dkim_text_value"] = None
        __props__.__dict__["dkim_verified"] = None
        __props__.__dict__["domain"] = None
        __props__.__dict__["email_address"] = None
        __props__.__dict__["from_email"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["reply_to_email"] = None
        __props__.__dict__["return_path_domain"] = None
        __props__.__dict__["return_path_domain_cname_value"] = None
        __props__.__dict__["return_path_domain_verified"] = None
        __props__.__dict__["signature_id"] = None
        __props__.__dict__["trigger_resend"] = None
        return SenderSignature(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="confirmationPersonalNote")
    def confirmation_personal_note(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Optional note (max 400 chars) included in the confirmation email.
        """
        return pulumi.get(self, "confirmation_personal_note")

    @_builtins.property
    @pulumi.getter
    def confirmed(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the signature has been confirmed. Postmark requires a human to click the confirmation email; run `pulumi refresh` to observe this flipping to true.
        """
        return pulumi.get(self, "confirmed")

    @_builtins.property
    @pulumi.getter(name="dkimHost")
    def dkim_host(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "dkim_host")

    @_builtins.property
    @pulumi.getter(name="dkimPendingHost")
    def dkim_pending_host(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "dkim_pending_host")

    @_builtins.property
    @pulumi.getter(name="dkimPendingTextValue")
    def dkim_pending_text_value(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "dkim_pending_text_value")

    @_builtins.property
    @pulumi.getter(name="dkimTextValue")
    def dkim_text_value(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "dkim_text_value")

    @_builtins.property
    @pulumi.getter(name="dkimVerified")
    def dkim_verified(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "dkim_verified")

    @_builtins.property
    @pulumi.getter
    def domain(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "domain")

    @_builtins.property
    @pulumi.getter(name="emailAddress")
    def email_address(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "email_address")

    @_builtins.property
    @pulumi.getter(name="fromEmail")
    def from_email(self) -> pulumi.Output[_builtins.str]:
        """
        The email address to sign. Immutable — changing it replaces the signature.
        """
        return pulumi.get(self, "from_email")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        From name associated with the signature.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="replyToEmail")
    def reply_to_email(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Optional Reply-To email address.
        """
        return pulumi.get(self, "reply_to_email")

    @_builtins.property
    @pulumi.getter(name="returnPathDomain")
    def return_path_domain(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Optional custom Return-Path subdomain of the From address's domain.
        """
        return pulumi.get(self, "return_path_domain")

    @_builtins.property
    @pulumi.getter(name="returnPathDomainCnameValue")
    def return_path_domain_cname_value(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "return_path_domain_cname_value")

    @_builtins.property
    @pulumi.getter(name="returnPathDomainVerified")
    def return_path_domain_verified(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "return_path_domain_verified")

    @_builtins.property
    @pulumi.getter(name="signatureId")
    def signature_id(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "signature_id")

    @_builtins.property
    @pulumi.getter(name="triggerResend")
    def trigger_resend(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Arbitrary value; change it to resend the confirmation email on the next update.
        """
        return pulumi.get(self, "trigger_resend")

