# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ServerArgs', 'Server']

@pulumi.input_type
class ServerArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 color: Optional[pulumi.Input[_builtins.str]] = None,
                 delivery_type: Optional[pulumi.Input[_builtins.str]] = None,
                 enable_smtp_api_error_hooks: Optional[pulumi.Input[_builtins.bool]] = None,
                 inbound_domain: Optional[pulumi.Input[_builtins.str]] = None,
                 inbound_hook_url: Optional[pulumi.Input[_builtins.str]] = None,
                 inbound_spam_threshold: Optional[pulumi.Input[_builtins.int]] = None,
                 include_bounce_content_in_hook: Optional[pulumi.Input[_builtins.bool]] = None,
                 post_first_open_only: Optional[pulumi.Input[_builtins.bool]] = None,
                 raw_email_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 smtp_api_activated: Optional[pulumi.Input[_builtins.bool]] = None,
                 track_links: Optional[pulumi.Input[_builtins.str]] = None,
                 track_opens: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        The set of arguments for constructing a Server resource.

        :param pulumi.Input[_builtins.str] name: Friendly name of the server.
        :param pulumi.Input[_builtins.str] color: Color of the server in the Postmark UI server list. One of: Purple, Blue, Turquoise, Green, Red, Yellow, Grey, Orange. Defaults to Blue.
        :param pulumi.Input[_builtins.str] delivery_type: Environment type: `Live` or `Sandbox`. Immutable after creation — changing it replaces the server. Defaults to `Live`.
        :param pulumi.Input[_builtins.str] inbound_domain: Inbound domain for MX setup. Point an MX record for this domain at `inbound.postmarkapp.com` to receive mail.
        :param pulumi.Input[_builtins.str] inbound_hook_url: URL Postmark POSTs to for every inbound email event.
        :param pulumi.Input[_builtins.int] inbound_spam_threshold: Maximum spam score before an inbound message is blocked.
        :param pulumi.Input[_builtins.str] track_links: Link tracking mode: None, HtmlAndText, HtmlOnly or TextOnly. Defaults to None.
        :param pulumi.Input[_builtins.bool] track_opens: Enable open tracking for messages by default.
        """
        pulumi.set(__self__, "name", name)
        if color is not None:
            pulumi.set(__self__, "color", color)
        if delivery_type is not None:
            pulumi.set(__self__, "delivery_type", delivery_type)
        if enable_smtp_api_error_hooks is not None:
            pulumi.set(__self__, "enable_smtp_api_error_hooks", enable_smtp_api_error_hooks)
        if inbound_domain is not None:
            pulumi.set(__self__, "inbound_domain", inbound_domain)
        if inbound_hook_url is not None:
            pulumi.set(__self__, "inbound_hook_url", inbound_hook_url)
        if inbound_spam_threshold is not None:
            pulumi.set(__self__, "inbound_spam_threshold", inbound_spam_threshold)
        if include_bounce_content_in_hook is not None:
            pulumi.set(__self__, "include_bounce_content_in_hook", include_bounce_content_in_hook)
        if post_first_open_only is not None:
            pulumi.set(__self__, "post_first_open_only", post_first_open_only)
        if raw_email_enabled is not None:
            pulumi.set(__self__, "raw_email_enabled", raw_email_enabled)
        if smtp_api_activated is not None:
            pulumi.set(__self__, "smtp_api_activated", smtp_api_activated)
        if track_links is not None:
            pulumi.set(__self__, "track_links", track_links)
        if track_opens is not None:
            pulumi.set(__self__, "track_opens", track_opens)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        Friendly name of the server.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def color(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Color of the server in the Postmark UI server list. One of: Purple, Blue, Turquoise, Green, Red, Yellow, Grey, Orange. Defaults to Blue.
        """
        return pulumi.get(self, "color")

    @color.setter
    def color(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "color", value)

    @_builtins.property
    @pulumi.getter(name="deliveryType")
    def delivery_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Environment type: `Live` or `Sandbox`. Immutable after creation — changing it replaces the server. Defaults to `Live`.
        """
        return pulumi.get(self, "delivery_type")

    @delivery_type.setter
    def delivery_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "delivery_type", value)

    @_builtins.property
    @pulumi.getter(name="enableSmtpApiErrorHooks")
    def enable_smtp_api_error_hooks(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "enable_smtp_api_error_hooks")

    @enable_smtp_api_error_hooks.setter
    def enable_smtp_api_error_hooks(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enable_smtp_api_error_hooks", value)

    @_builtins.property
    @pulumi.getter(name="inboundDomain")
    def inbound_domain(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Inbound domain for MX setup. Point an MX record for this domain at `inbound.postmarkapp.com` to receive mail.
        """
        return pulumi.get(self, "inbound_domain")

    @inbound_domain.setter
    def inbound_domain(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "inbound_domain", value)

    @_builtins.property
    @pulumi.getter(name="inboundHookUrl")
    def inbound_hook_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        URL Postmark POSTs to for every inbound email event.
        """
        return pulumi.get(self, "inbound_hook_url")

    @inbound_hook_url.setter
    def inbound_hook_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "inbound_hook_url", value)

    @_builtins.property
    @pulumi.getter(name="inboundSpamThreshold")
    def inbound_spam_threshold(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Maximum spam score before an inbound message is blocked.
        """
        return pulumi.get(self, "inbound_spam_threshold")

    @inbound_spam_threshold.setter
    def inbound_spam_threshold(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "inbound_spam_threshold", value)

    @_builtins.property
    @pulumi.getter(name="includeBounceContentInHook")
    def include_bounce_content_in_hook(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "include_bounce_content_in_hook")

    @include_bounce_content_in_hook.setter
    def include_bounce_content_in_hook(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "include_bounce_content_in_hook", value)

    @_builtins.property
    @pulumi.getter(name="postFirstOpenOnly")
    def post_first_open_only(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "post_first_open_only")

    @post_first_open_only.setter
    def post_first_open_only(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "post_first_open_only", value)

    @_builtins.property
    @pulumi.getter(name="rawEmailEnabled")
    def raw_email_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "raw_email_enabled")

    @raw_email_enabled.setter
    def raw_email_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "raw_email_enabled", value)

    @_builtins.property
    @pulumi.getter(name="smtpApiActivated")
    def smtp_api_activated(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "smtp_api_activated")

    @smtp_api_activated.setter
    def smtp_api_activated(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "smtp_api_activated", value)

    @_builtins.property
    @pulumi.getter(name="trackLinks")
    def track_links(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Link tracking mode: None, HtmlAndText, HtmlOnly or TextOnly. Defaults to None.
        """
        return pulumi.get(self, "track_links")

    @track_links.setter
    def track_links(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "track_links", value)

    @_builtins.property
    @pulumi.getter(name="trackOpens")
    def track_opens(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Enable open tracking for messages by default.
        """
        return pulumi.get(self, "track_opens")

    @track_opens.setter
    def track_opens(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "track_opens", value)


@pulumi.type_token("postmark:index:Server")
class Server(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 color: Optional[pulumi.Input[_builtins.str]] = None,
                 delivery_type: Optional[pulumi.Input[_builtins.str]] = None,
                 enable_smtp_api_error_hooks: Optional[pulumi.Input[_builtins.bool]] = None,
                 inbound_domain: Optional[pulumi.Input[_builtins.str]] = None,
                 inbound_hook_url: Optional[pulumi.Input[_builtins.str]] = None,
                 inbound_spam_threshold: Optional[pulumi.Input[_builtins.int]] = None,
                 include_bounce_content_in_hook: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 post_first_open_only: Optional[pulumi.Input[_builtins.bool]] = None,
                 raw_email_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 smtp_api_activated: Optional[pulumi.Input[_builtins.bool]] = None,
                 track_links: Optional[pulumi.Input[_builtins.str]] = None,
                 track_opens: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        """
        Create a Server resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] color: Color of the server in the Postmark UI server list. One of: Purple, Blue, Turquoise, Green, Red, Yellow, Grey, Orange. Defaults to Blue.
        :param pulumi.Input[_builtins.str] delivery_type: Environment type: `Live` or `Sandbox`. Immutable after creation — changing it replaces the server. Defaults to `Live`.
        :param pulumi.Input[_builtins.str] inbound_domain: Inbound domain for MX setup. Point an MX record for this domain at `inbound.postmarkapp.com` to receive mail.
        :param pulumi.Input[_builtins.str] inbound_hook_url: URL Postmark POSTs to for every inbound email event.
        :param pulumi.Input[_builtins.int] inbound_spam_threshold: Maximum spam score before an inbound message is blocked.
        :param pulumi.Input[_builtins.str] name: Friendly name of the server.
        :param pulumi.Input[_builtins.str] track_links: Link tracking mode: None, HtmlAndText, HtmlOnly or TextOnly. Defaults to None.
        :param pulumi.Input[_builtins.bool] track_opens: Enable open tracking for messages by default.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ServerArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Server resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ServerArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ServerArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 color: Optional[pulumi.Input[_builtins.str]] = None,
                 delivery_type: Optional[pulumi.Input[_builtins.str]] = None,
                 enable_smtp_api_error_hooks: Optional[pulumi.Input[_builtins.bool]] = None,
                 inbound_domain: Optional[pulumi.Input[_builtins.str]] = None,
                 inbound_hook_url: Optional[pulumi.Input[_builtins.str]] = None,
                 inbound_spam_threshold: Optional[pulumi.Input[_builtins.int]] = None,
                 include_bounce_content_in_hook: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 post_first_open_only: Optional[pulumi.Input[_builtins.bool]] = None,
                 raw_email_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 smtp_api_activated: Optional[pulumi.Input[_builtins.bool]] = None,
                 track_links: Optional[pulumi.Input[_builtins.str]] = None,
                 track_opens: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ServerArgs.__new__(ServerArgs)

            __props__.__dict__["color"] = color
            __props__.__dict__["delivery_type"] = delivery_type
            __props__.__dict__["enable_smtp_api_error_hooks"] = enable_smtp_api_error_hooks
            __props__.__dict__["inbound_domain"] = inbound_domain
            __props__.__dict__["inbound_hook_url"] = inbound_hook_url
            __props__.__dict__["inbound_spam_threshold"] = inbound_spam_threshold
            __props__.__dict__["include_bounce_content_in_hook"] = include_bounce_content_in_hook
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["post_first_open_only"] = post_first_open_only
            __props__.__dict__["raw_email_enabled"] = raw_email_enabled
            __props__.__dict__["smtp_api_activated"] = smtp_api_activated
            __props__.__dict__["track_links"] = track_links
            __props__.__dict__["track_opens"] = track_opens
            __props__.__dict__["api_tokens"] = None
            __props__.__dict__["inbound_address"] = None
            __props__.__dict__["inbound_hash"] = None
            __props__.__dict__["server_id"] = None
            __props__.__dict__["server_link"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["apiTokens"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["deliveryType"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(Server, __self__).__init__(
            'postmark:index:Server',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Server':
        """
        Get an existing Server resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ServerArgs.__new__(ServerArgs)

        __props__.__dict__["api_tokens"] = None
        __props__.__dict__["color"] = None
        __props__.__dict__["delivery_type"] = None
        __props__.__dict__["enable_smtp_api_error_hooks"] = None
        __props__.__dict__["inbound_address"] = None
        __props__.__dict__["inbound_domain"] = None
        __props__.__dict__["inbound_hash"] = None
        __props__.__dict__["inbound_hook_url"] = None
        __props__.__dict__["inbound_spam_threshold"] = None
        __props__.__dict__["include_bounce_content_in_hook"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["post_first_open_only"] = None
        __props__.__dict__["raw_email_enabled"] = None
        __props__.__dict__["server_id"] = None
        __props__.__dict__["server_link"] = None
        __props__.__dict__["smtp_api_activated"] = None
        __props__.__dict__["track_links"] = None
        __props__.__dict__["track_opens"] = None
        return Server(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="apiTokens")
    def api_tokens(self) -> pulumi.Output[Sequence[_builtins.str]]:
        return pulumi.get(self, "api_tokens")

    @_builtins.property
    @pulumi.getter
    def color(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Color of the server in the Postmark UI server list. One of: Purple, Blue, Turquoise, Green, Red, Yellow, Grey, Orange. Defaults to Blue.
        """
        return pulumi.get(self, "color")

    @_builtins.property
    @pulumi.getter(name="deliveryType")
    def delivery_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Environment type: `Live` or `Sandbox`. Immutable after creation — changing it replaces the server. Defaults to `Live`.
        """
        return pulumi.get(self, "delivery_type")

    @_builtins.property
    @pulumi.getter(name="enableSmtpApiErrorHooks")
    def enable_smtp_api_error_hooks(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "enable_smtp_api_error_hooks")

    @_builtins.property
    @pulumi.getter(name="inboundAddress")
    def inbound_address(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "inbound_address")

    @_builtins.property
    @pulumi.getter(name="inboundDomain")
    def inbound_domain(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Inbound domain for MX setup. Point an MX record for this domain at `inbound.postmarkapp.com` to receive mail.
        """
        return pulumi.get(self, "inbound_domain")

    @_builtins.property
    @pulumi.getter(name="inboundHash")
    def inbound_hash(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "inbound_hash")

    @_builtins.property
    @pulumi.getter(name="inboundHookUrl")
    def inbound_hook_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        URL Postmark POSTs to for every inbound email event.
        """
        return pulumi.get(self, "inbound_hook_url")

    @_builtins.property
    @pulumi.getter(name="inboundSpamThreshold")
    def inbound_spam_threshold(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Maximum spam score before an inbound message is blocked.
        """
        return pulumi.get(self, "inbound_spam_threshold")

    @_builtins.property
    @pulumi.getter(name="includeBounceContentInHook")
    def include_bounce_content_in_hook(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "include_bounce_content_in_hook")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Friendly name of the server.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="postFirstOpenOnly")
    def post_first_open_only(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "post_first_open_only")

    @_builtins.property
    @pulumi.getter(name="rawEmailEnabled")
    def raw_email_enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "raw_email_enabled")

    @_builtins.property
    @pulumi.getter(name="serverId")
    def server_id(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "server_id")

    @_builtins.property
    @pulumi.getter(name="serverLink")
    def server_link(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "server_link")

    @_builtins.property
    @pulumi.getter(name="smtpApiActivated")
    def smtp_api_activated(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "smtp_api_activated")

    @_builtins.property
    @pulumi.getter(name="trackLinks")
    def track_links(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Link tracking mode: None, HtmlAndText, HtmlOnly or TextOnly. Defaults to None.
        """
        return pulumi.get(self, "track_links")

    @_builtins.property
    @pulumi.getter(name="trackOpens")
    def track_opens(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Enable open tracking for messages by default.
        """
        return pulumi.get(self, "track_opens")

