# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['TemplateArgs', 'Template']

@pulumi.input_type
class TemplateArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 alias: Optional[pulumi.Input[_builtins.str]] = None,
                 html_body: Optional[pulumi.Input[_builtins.str]] = None,
                 layout_template: Optional[pulumi.Input[_builtins.str]] = None,
                 server_id: Optional[pulumi.Input[_builtins.int]] = None,
                 server_token: Optional[pulumi.Input[_builtins.str]] = None,
                 subject: Optional[pulumi.Input[_builtins.str]] = None,
                 template_type: Optional[pulumi.Input[_builtins.str]] = None,
                 text_body: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Template resource.

        :param pulumi.Input[_builtins.str] name: Name of the template.
        :param pulumi.Input[_builtins.str] alias: Optional unique alias (within the server). Must start with a letter; may contain letters, digits, '.', '-' and '_'.
        :param pulumi.Input[_builtins.str] html_body: HTML body. Required unless `textBody` is set.
        :param pulumi.Input[_builtins.str] layout_template: Alias of a Layout to wrap this Standard template (set to "" to disassociate).
        :param pulumi.Input[_builtins.int] server_id: ID of the server this template belongs to; the provider looks up its token via the account token. Immutable — changing it replaces the template.
        :param pulumi.Input[_builtins.str] server_token: Server API token of the server this template belongs to. Wire from `server.apiTokens[0]`. Falls back to `serverId` lookup, then the provider `serverToken` config.
        :param pulumi.Input[_builtins.str] subject: Subject line. Required for Standard templates; not allowed for Layouts.
        :param pulumi.Input[_builtins.str] template_type: `Standard` (default) or `Layout`. Immutable — changing it replaces the template.
        :param pulumi.Input[_builtins.str] text_body: Plain-text body. Required unless `htmlBody` is set.
        """
        pulumi.set(__self__, "name", name)
        if alias is not None:
            pulumi.set(__self__, "alias", alias)
        if html_body is not None:
            pulumi.set(__self__, "html_body", html_body)
        if layout_template is not None:
            pulumi.set(__self__, "layout_template", layout_template)
        if server_id is not None:
            pulumi.set(__self__, "server_id", server_id)
        if server_token is not None:
            pulumi.set(__self__, "server_token", server_token)
        if subject is not None:
            pulumi.set(__self__, "subject", subject)
        if template_type is not None:
            pulumi.set(__self__, "template_type", template_type)
        if text_body is not None:
            pulumi.set(__self__, "text_body", text_body)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        Name of the template.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def alias(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Optional unique alias (within the server). Must start with a letter; may contain letters, digits, '.', '-' and '_'.
        """
        return pulumi.get(self, "alias")

    @alias.setter
    def alias(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "alias", value)

    @_builtins.property
    @pulumi.getter(name="htmlBody")
    def html_body(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        HTML body. Required unless `textBody` is set.
        """
        return pulumi.get(self, "html_body")

    @html_body.setter
    def html_body(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "html_body", value)

    @_builtins.property
    @pulumi.getter(name="layoutTemplate")
    def layout_template(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Alias of a Layout to wrap this Standard template (set to "" to disassociate).
        """
        return pulumi.get(self, "layout_template")

    @layout_template.setter
    def layout_template(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "layout_template", value)

    @_builtins.property
    @pulumi.getter(name="serverId")
    def server_id(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        ID of the server this template belongs to; the provider looks up its token via the account token. Immutable — changing it replaces the template.
        """
        return pulumi.get(self, "server_id")

    @server_id.setter
    def server_id(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "server_id", value)

    @_builtins.property
    @pulumi.getter(name="serverToken")
    def server_token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Server API token of the server this template belongs to. Wire from `server.apiTokens[0]`. Falls back to `serverId` lookup, then the provider `serverToken` config.
        """
        return pulumi.get(self, "server_token")

    @server_token.setter
    def server_token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "server_token", value)

    @_builtins.property
    @pulumi.getter
    def subject(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Subject line. Required for Standard templates; not allowed for Layouts.
        """
        return pulumi.get(self, "subject")

    @subject.setter
    def subject(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "subject", value)

    @_builtins.property
    @pulumi.getter(name="templateType")
    def template_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        `Standard` (default) or `Layout`. Immutable — changing it replaces the template.
        """
        return pulumi.get(self, "template_type")

    @template_type.setter
    def template_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "template_type", value)

    @_builtins.property
    @pulumi.getter(name="textBody")
    def text_body(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Plain-text body. Required unless `htmlBody` is set.
        """
        return pulumi.get(self, "text_body")

    @text_body.setter
    def text_body(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "text_body", value)


@pulumi.type_token("postmark:index:Template")
class Template(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 alias: Optional[pulumi.Input[_builtins.str]] = None,
                 html_body: Optional[pulumi.Input[_builtins.str]] = None,
                 layout_template: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 server_id: Optional[pulumi.Input[_builtins.int]] = None,
                 server_token: Optional[pulumi.Input[_builtins.str]] = None,
                 subject: Optional[pulumi.Input[_builtins.str]] = None,
                 template_type: Optional[pulumi.Input[_builtins.str]] = None,
                 text_body: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Template resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] alias: Optional unique alias (within the server). Must start with a letter; may contain letters, digits, '.', '-' and '_'.
        :param pulumi.Input[_builtins.str] html_body: HTML body. Required unless `textBody` is set.
        :param pulumi.Input[_builtins.str] layout_template: Alias of a Layout to wrap this Standard template (set to "" to disassociate).
        :param pulumi.Input[_builtins.str] name: Name of the template.
        :param pulumi.Input[_builtins.int] server_id: ID of the server this template belongs to; the provider looks up its token via the account token. Immutable — changing it replaces the template.
        :param pulumi.Input[_builtins.str] server_token: Server API token of the server this template belongs to. Wire from `server.apiTokens[0]`. Falls back to `serverId` lookup, then the provider `serverToken` config.
        :param pulumi.Input[_builtins.str] subject: Subject line. Required for Standard templates; not allowed for Layouts.
        :param pulumi.Input[_builtins.str] template_type: `Standard` (default) or `Layout`. Immutable — changing it replaces the template.
        :param pulumi.Input[_builtins.str] text_body: Plain-text body. Required unless `htmlBody` is set.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: TemplateArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Template resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param TemplateArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(TemplateArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 alias: Optional[pulumi.Input[_builtins.str]] = None,
                 html_body: Optional[pulumi.Input[_builtins.str]] = None,
                 layout_template: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 server_id: Optional[pulumi.Input[_builtins.int]] = None,
                 server_token: Optional[pulumi.Input[_builtins.str]] = None,
                 subject: Optional[pulumi.Input[_builtins.str]] = None,
                 template_type: Optional[pulumi.Input[_builtins.str]] = None,
                 text_body: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = TemplateArgs.__new__(TemplateArgs)

            __props__.__dict__["alias"] = alias
            __props__.__dict__["html_body"] = html_body
            __props__.__dict__["layout_template"] = layout_template
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["server_id"] = server_id
            __props__.__dict__["server_token"] = None if server_token is None else pulumi.Output.secret(server_token)
            __props__.__dict__["subject"] = subject
            __props__.__dict__["template_type"] = template_type
            __props__.__dict__["text_body"] = text_body
            __props__.__dict__["active"] = None
            __props__.__dict__["associated_server_id"] = None
            __props__.__dict__["template_id"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["serverToken"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["serverId", "templateType"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(Template, __self__).__init__(
            'postmark:index:Template',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Template':
        """
        Get an existing Template resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = TemplateArgs.__new__(TemplateArgs)

        __props__.__dict__["active"] = None
        __props__.__dict__["alias"] = None
        __props__.__dict__["associated_server_id"] = None
        __props__.__dict__["html_body"] = None
        __props__.__dict__["layout_template"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["server_id"] = None
        __props__.__dict__["server_token"] = None
        __props__.__dict__["subject"] = None
        __props__.__dict__["template_id"] = None
        __props__.__dict__["template_type"] = None
        __props__.__dict__["text_body"] = None
        return Template(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def active(self) -> pulumi.Output[_builtins.bool]:
        return pulumi.get(self, "active")

    @_builtins.property
    @pulumi.getter
    def alias(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Optional unique alias (within the server). Must start with a letter; may contain letters, digits, '.', '-' and '_'.
        """
        return pulumi.get(self, "alias")

    @_builtins.property
    @pulumi.getter(name="associatedServerId")
    def associated_server_id(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "associated_server_id")

    @_builtins.property
    @pulumi.getter(name="htmlBody")
    def html_body(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        HTML body. Required unless `textBody` is set.
        """
        return pulumi.get(self, "html_body")

    @_builtins.property
    @pulumi.getter(name="layoutTemplate")
    def layout_template(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Alias of a Layout to wrap this Standard template (set to "" to disassociate).
        """
        return pulumi.get(self, "layout_template")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Name of the template.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="serverId")
    def server_id(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        ID of the server this template belongs to; the provider looks up its token via the account token. Immutable — changing it replaces the template.
        """
        return pulumi.get(self, "server_id")

    @_builtins.property
    @pulumi.getter(name="serverToken")
    def server_token(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Server API token of the server this template belongs to. Wire from `server.apiTokens[0]`. Falls back to `serverId` lookup, then the provider `serverToken` config.
        """
        return pulumi.get(self, "server_token")

    @_builtins.property
    @pulumi.getter
    def subject(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Subject line. Required for Standard templates; not allowed for Layouts.
        """
        return pulumi.get(self, "subject")

    @_builtins.property
    @pulumi.getter(name="templateId")
    def template_id(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "template_id")

    @_builtins.property
    @pulumi.getter(name="templateType")
    def template_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        `Standard` (default) or `Layout`. Immutable — changing it replaces the template.
        """
        return pulumi.get(self, "template_type")

    @_builtins.property
    @pulumi.getter(name="textBody")
    def text_body(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Plain-text body. Required unless `htmlBody` is set.
        """
        return pulumi.get(self, "text_body")

