// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("postmark");

/**
 * Postmark Account API token (X-Postmark-Account-Token). Required to manage Servers, Domains and Sender Signatures. May also be set via the POSTMARK_ACCOUNT_TOKEN environment variable.
 */
export declare const accountToken: string;
Object.defineProperty(exports, "accountToken", {
    get() {
        return __config.get("accountToken") ?? (utilities.getEnv("POSTMARK_ACCOUNT_TOKEN") || "");
    },
    enumerable: true,
});

/**
 * Base URL of the Postmark API. Defaults to https://api.postmarkapp.com. May also be set via the POSTMARK_BASE_URL environment variable (useful for testing).
 */
export declare const baseUrl: string;
Object.defineProperty(exports, "baseUrl", {
    get() {
        return __config.get("baseUrl") ?? (utilities.getEnv("POSTMARK_BASE_URL") || "https://api.postmarkapp.com");
    },
    enumerable: true,
});

/**
 * Default Postmark Server API token (X-Postmark-Server-Token) used for Template operations when a Template does not set its own `serverToken`/`serverId`. Only useful when all Templates live on a single server. May also be set via the POSTMARK_SERVER_TOKEN environment variable.
 */
export declare const serverToken: string;
Object.defineProperty(exports, "serverToken", {
    get() {
        return __config.get("serverToken") ?? (utilities.getEnv("POSTMARK_SERVER_TOKEN") || "");
    },
    enumerable: true,
});

