# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('postmark')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def account_token(self) -> str:
        """
        Postmark Account API token (X-Postmark-Account-Token). Required to manage Servers, Domains and Sender Signatures. May also be set via the POSTMARK_ACCOUNT_TOKEN environment variable.
        """
        return __config__.get('accountToken') or (_utilities.get_env('POSTMARK_ACCOUNT_TOKEN') or '')

    @_builtins.property
    def base_url(self) -> str:
        """
        Base URL of the Postmark API. Defaults to https://api.postmarkapp.com. May also be set via the POSTMARK_BASE_URL environment variable (useful for testing).
        """
        return __config__.get('baseUrl') or (_utilities.get_env('POSTMARK_BASE_URL') or 'https://api.postmarkapp.com')

    @_builtins.property
    def server_token(self) -> str:
        """
        Default Postmark Server API token (X-Postmark-Server-Token) used for Template operations when a Template does not set its own `serverToken`/`serverId`. Only useful when all Templates live on a single server. May also be set via the POSTMARK_SERVER_TOKEN environment variable.
        """
        return __config__.get('serverToken') or (_utilities.get_env('POSTMARK_SERVER_TOKEN') or '')

