// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.hummingbirdme.postmark;

import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("postmark");
/**
 * Postmark Account API token (X-Postmark-Account-Token). Required to manage Servers, Domains and Sender Signatures. May also be set via the POSTMARK_ACCOUNT_TOKEN environment variable.
 * 
 */
    public Optional<String> accountToken() {
        return Codegen.stringProp("accountToken").config(config).env("POSTMARK_ACCOUNT_TOKEN").def("").get();
    }
/**
 * Base URL of the Postmark API. Defaults to https://api.postmarkapp.com. May also be set via the POSTMARK_BASE_URL environment variable (useful for testing).
 * 
 */
    public Optional<String> baseUrl() {
        return Codegen.stringProp("baseUrl").config(config).env("POSTMARK_BASE_URL").def("https://api.postmarkapp.com").get();
    }
/**
 * Default Postmark Server API token (X-Postmark-Server-Token) used for Template operations when a Template does not set its own `serverToken`/`serverId`. Only useful when all Templates live on a single server. May also be set via the POSTMARK_SERVER_TOKEN environment variable.
 * 
 */
    public Optional<String> serverToken() {
        return Codegen.stringProp("serverToken").config(config).env("POSTMARK_SERVER_TOKEN").def("").get();
    }
}
