// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.hummingbirdme.postmark;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DomainArgs extends com.pulumi.resources.ResourceArgs {

    public static final DomainArgs Empty = new DomainArgs();

    /**
     * The domain name to send from (e.g. `example.com`). Immutable — changing it replaces the domain.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return The domain name to send from (e.g. `example.com`). Immutable — changing it replaces the domain.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * Custom Return-Path subdomain (e.g. `pm-bounces.example.com`). Must be a subdomain of `name` and have a CNAME pointing at the value of `returnPathDomainCnameValue`.
     * 
     */
    @Import(name="returnPathDomain")
    private @Nullable Output<String> returnPathDomain;

    /**
     * @return Custom Return-Path subdomain (e.g. `pm-bounces.example.com`). Must be a subdomain of `name` and have a CNAME pointing at the value of `returnPathDomainCnameValue`.
     * 
     */
    public Optional<Output<String>> returnPathDomain() {
        return Optional.ofNullable(this.returnPathDomain);
    }

    private DomainArgs() {}

    private DomainArgs(DomainArgs $) {
        this.name = $.name;
        this.returnPathDomain = $.returnPathDomain;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DomainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DomainArgs $;

        public Builder() {
            $ = new DomainArgs();
        }

        public Builder(DomainArgs defaults) {
            $ = new DomainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The domain name to send from (e.g. `example.com`). Immutable — changing it replaces the domain.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The domain name to send from (e.g. `example.com`). Immutable — changing it replaces the domain.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param returnPathDomain Custom Return-Path subdomain (e.g. `pm-bounces.example.com`). Must be a subdomain of `name` and have a CNAME pointing at the value of `returnPathDomainCnameValue`.
         * 
         * @return builder
         * 
         */
        public Builder returnPathDomain(@Nullable Output<String> returnPathDomain) {
            $.returnPathDomain = returnPathDomain;
            return this;
        }

        /**
         * @param returnPathDomain Custom Return-Path subdomain (e.g. `pm-bounces.example.com`). Must be a subdomain of `name` and have a CNAME pointing at the value of `returnPathDomainCnameValue`.
         * 
         * @return builder
         * 
         */
        public Builder returnPathDomain(String returnPathDomain) {
            return returnPathDomain(Output.of(returnPathDomain));
        }

        public DomainArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("DomainArgs", "name");
            }
            return $;
        }
    }

}
