// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.hummingbirdme.postmark;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class DomainVerificationArgs extends com.pulumi.resources.ResourceArgs {

    public static final DomainVerificationArgs Empty = new DomainVerificationArgs();

    /**
     * ID of the Domain to verify (wire from `domain.domainId`). Immutable.
     * 
     */
    @Import(name="domainId", required=true)
    private Output<Integer> domainId;

    /**
     * @return ID of the Domain to verify (wire from `domain.domainId`). Immutable.
     * 
     */
    public Output<Integer> domainId() {
        return this.domainId;
    }

    /**
     * Maximum seconds to poll for verification to succeed while DNS propagates. Defaults to 0 (a single, non-blocking attempt).
     * 
     */
    @Import(name="pollTimeoutSeconds")
    private @Nullable Output<Integer> pollTimeoutSeconds;

    /**
     * @return Maximum seconds to poll for verification to succeed while DNS propagates. Defaults to 0 (a single, non-blocking attempt).
     * 
     */
    public Optional<Output<Integer>> pollTimeoutSeconds() {
        return Optional.ofNullable(this.pollTimeoutSeconds);
    }

    /**
     * Arbitrary value; change it to force re-verification on the next update.
     * 
     */
    @Import(name="trigger")
    private @Nullable Output<String> trigger;

    /**
     * @return Arbitrary value; change it to force re-verification on the next update.
     * 
     */
    public Optional<Output<String>> trigger() {
        return Optional.ofNullable(this.trigger);
    }

    /**
     * Whether to verify DKIM. Defaults to true.
     * 
     */
    @Import(name="verifyDkim")
    private @Nullable Output<Boolean> verifyDkim;

    /**
     * @return Whether to verify DKIM. Defaults to true.
     * 
     */
    public Optional<Output<Boolean>> verifyDkim() {
        return Optional.ofNullable(this.verifyDkim);
    }

    /**
     * Whether to verify the Return-Path CNAME. Defaults to true.
     * 
     */
    @Import(name="verifyReturnPath")
    private @Nullable Output<Boolean> verifyReturnPath;

    /**
     * @return Whether to verify the Return-Path CNAME. Defaults to true.
     * 
     */
    public Optional<Output<Boolean>> verifyReturnPath() {
        return Optional.ofNullable(this.verifyReturnPath);
    }

    private DomainVerificationArgs() {}

    private DomainVerificationArgs(DomainVerificationArgs $) {
        this.domainId = $.domainId;
        this.pollTimeoutSeconds = $.pollTimeoutSeconds;
        this.trigger = $.trigger;
        this.verifyDkim = $.verifyDkim;
        this.verifyReturnPath = $.verifyReturnPath;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DomainVerificationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DomainVerificationArgs $;

        public Builder() {
            $ = new DomainVerificationArgs();
        }

        public Builder(DomainVerificationArgs defaults) {
            $ = new DomainVerificationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param domainId ID of the Domain to verify (wire from `domain.domainId`). Immutable.
         * 
         * @return builder
         * 
         */
        public Builder domainId(Output<Integer> domainId) {
            $.domainId = domainId;
            return this;
        }

        /**
         * @param domainId ID of the Domain to verify (wire from `domain.domainId`). Immutable.
         * 
         * @return builder
         * 
         */
        public Builder domainId(Integer domainId) {
            return domainId(Output.of(domainId));
        }

        /**
         * @param pollTimeoutSeconds Maximum seconds to poll for verification to succeed while DNS propagates. Defaults to 0 (a single, non-blocking attempt).
         * 
         * @return builder
         * 
         */
        public Builder pollTimeoutSeconds(@Nullable Output<Integer> pollTimeoutSeconds) {
            $.pollTimeoutSeconds = pollTimeoutSeconds;
            return this;
        }

        /**
         * @param pollTimeoutSeconds Maximum seconds to poll for verification to succeed while DNS propagates. Defaults to 0 (a single, non-blocking attempt).
         * 
         * @return builder
         * 
         */
        public Builder pollTimeoutSeconds(Integer pollTimeoutSeconds) {
            return pollTimeoutSeconds(Output.of(pollTimeoutSeconds));
        }

        /**
         * @param trigger Arbitrary value; change it to force re-verification on the next update.
         * 
         * @return builder
         * 
         */
        public Builder trigger(@Nullable Output<String> trigger) {
            $.trigger = trigger;
            return this;
        }

        /**
         * @param trigger Arbitrary value; change it to force re-verification on the next update.
         * 
         * @return builder
         * 
         */
        public Builder trigger(String trigger) {
            return trigger(Output.of(trigger));
        }

        /**
         * @param verifyDkim Whether to verify DKIM. Defaults to true.
         * 
         * @return builder
         * 
         */
        public Builder verifyDkim(@Nullable Output<Boolean> verifyDkim) {
            $.verifyDkim = verifyDkim;
            return this;
        }

        /**
         * @param verifyDkim Whether to verify DKIM. Defaults to true.
         * 
         * @return builder
         * 
         */
        public Builder verifyDkim(Boolean verifyDkim) {
            return verifyDkim(Output.of(verifyDkim));
        }

        /**
         * @param verifyReturnPath Whether to verify the Return-Path CNAME. Defaults to true.
         * 
         * @return builder
         * 
         */
        public Builder verifyReturnPath(@Nullable Output<Boolean> verifyReturnPath) {
            $.verifyReturnPath = verifyReturnPath;
            return this;
        }

        /**
         * @param verifyReturnPath Whether to verify the Return-Path CNAME. Defaults to true.
         * 
         * @return builder
         * 
         */
        public Builder verifyReturnPath(Boolean verifyReturnPath) {
            return verifyReturnPath(Output.of(verifyReturnPath));
        }

        public DomainVerificationArgs build() {
            if ($.domainId == null) {
                throw new MissingRequiredPropertyException("DomainVerificationArgs", "domainId");
            }
            return $;
        }
    }

}
