// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.hummingbirdme.postmark;

import com.hummingbirdme.postmark.DomainArgs;
import com.hummingbirdme.postmark.Utilities;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="postmark:index:Domain")
public class Domain extends com.pulumi.resources.CustomResource {
    /**
     * Hostname of the currently-active DKIM record (populated after verification).
     * 
     */
    @Export(name="dkimHost", refs={String.class}, tree="[0]")
    private Output<String> dkimHost;

    /**
     * @return Hostname of the currently-active DKIM record (populated after verification).
     * 
     */
    public Output<String> dkimHost() {
        return this.dkimHost;
    }
    /**
     * Hostname for the DKIM TXT record to publish (publish this first).
     * 
     */
    @Export(name="dkimPendingHost", refs={String.class}, tree="[0]")
    private Output<String> dkimPendingHost;

    /**
     * @return Hostname for the DKIM TXT record to publish (publish this first).
     * 
     */
    public Output<String> dkimPendingHost() {
        return this.dkimPendingHost;
    }
    /**
     * Value for the DKIM TXT record to publish.
     * 
     */
    @Export(name="dkimPendingTextValue", refs={String.class}, tree="[0]")
    private Output<String> dkimPendingTextValue;

    /**
     * @return Value for the DKIM TXT record to publish.
     * 
     */
    public Output<String> dkimPendingTextValue() {
        return this.dkimPendingTextValue;
    }
    @Export(name="dkimRevokedHost", refs={String.class}, tree="[0]")
    private Output<String> dkimRevokedHost;

    public Output<String> dkimRevokedHost() {
        return this.dkimRevokedHost;
    }
    @Export(name="dkimRevokedTextValue", refs={String.class}, tree="[0]")
    private Output<String> dkimRevokedTextValue;

    public Output<String> dkimRevokedTextValue() {
        return this.dkimRevokedTextValue;
    }
    /**
     * Value of the currently-active DKIM record.
     * 
     */
    @Export(name="dkimTextValue", refs={String.class}, tree="[0]")
    private Output<String> dkimTextValue;

    /**
     * @return Value of the currently-active DKIM record.
     * 
     */
    public Output<String> dkimTextValue() {
        return this.dkimTextValue;
    }
    @Export(name="dkimUpdateStatus", refs={String.class}, tree="[0]")
    private Output<String> dkimUpdateStatus;

    public Output<String> dkimUpdateStatus() {
        return this.dkimUpdateStatus;
    }
    /**
     * Whether DKIM has been verified by Postmark.
     * 
     */
    @Export(name="dkimVerified", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> dkimVerified;

    /**
     * @return Whether DKIM has been verified by Postmark.
     * 
     */
    public Output<Boolean> dkimVerified() {
        return this.dkimVerified;
    }
    @Export(name="domainId", refs={Integer.class}, tree="[0]")
    private Output<Integer> domainId;

    public Output<Integer> domainId() {
        return this.domainId;
    }
    /**
     * The domain name to send from (e.g. `example.com`). Immutable — changing it replaces the domain.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return The domain name to send from (e.g. `example.com`). Immutable — changing it replaces the domain.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Custom Return-Path subdomain (e.g. `pm-bounces.example.com`). Must be a subdomain of `name` and have a CNAME pointing at the value of `returnPathDomainCnameValue`.
     * 
     */
    @Export(name="returnPathDomain", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> returnPathDomain;

    /**
     * @return Custom Return-Path subdomain (e.g. `pm-bounces.example.com`). Must be a subdomain of `name` and have a CNAME pointing at the value of `returnPathDomainCnameValue`.
     * 
     */
    public Output<Optional<String>> returnPathDomain() {
        return Codegen.optional(this.returnPathDomain);
    }
    /**
     * CNAME target for the Return-Path record (typically `pm.mtasv.net`).
     * 
     */
    @Export(name="returnPathDomainCnameValue", refs={String.class}, tree="[0]")
    private Output<String> returnPathDomainCnameValue;

    /**
     * @return CNAME target for the Return-Path record (typically `pm.mtasv.net`).
     * 
     */
    public Output<String> returnPathDomainCnameValue() {
        return this.returnPathDomainCnameValue;
    }
    /**
     * Whether the Return-Path CNAME has been verified by Postmark.
     * 
     */
    @Export(name="returnPathDomainVerified", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> returnPathDomainVerified;

    /**
     * @return Whether the Return-Path CNAME has been verified by Postmark.
     * 
     */
    public Output<Boolean> returnPathDomainVerified() {
        return this.returnPathDomainVerified;
    }
    @Export(name="safeToRemoveRevokedKeyFromDns", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> safeToRemoveRevokedKeyFromDns;

    public Output<Boolean> safeToRemoveRevokedKeyFromDns() {
        return this.safeToRemoveRevokedKeyFromDns;
    }
    @Export(name="spfHost", refs={String.class}, tree="[0]")
    private Output<String> spfHost;

    public Output<String> spfHost() {
        return this.spfHost;
    }
    @Export(name="spfTextValue", refs={String.class}, tree="[0]")
    private Output<String> spfTextValue;

    public Output<String> spfTextValue() {
        return this.spfTextValue;
    }
    @Export(name="spfVerified", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> spfVerified;

    public Output<Boolean> spfVerified() {
        return this.spfVerified;
    }
    @Export(name="weakDkim", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> weakDkim;

    public Output<Boolean> weakDkim() {
        return this.weakDkim;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Domain(java.lang.String name) {
        this(name, DomainArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Domain(java.lang.String name, DomainArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Domain(java.lang.String name, DomainArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("postmark:index:Domain", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Domain(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("postmark:index:Domain", name, null, makeResourceOptions(options, id), false);
    }

    private static DomainArgs makeArgs(DomainArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? DomainArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/hummingbird-me/pulumi-postmark")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Domain get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Domain(name, id, options);
    }
}
