// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.hummingbirdme.postmark;

import com.hummingbirdme.postmark.DomainVerificationArgs;
import com.hummingbirdme.postmark.Utilities;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="postmark:index:DomainVerification")
public class DomainVerification extends com.pulumi.resources.CustomResource {
    @Export(name="dkimHost", refs={String.class}, tree="[0]")
    private Output<String> dkimHost;

    public Output<String> dkimHost() {
        return this.dkimHost;
    }
    @Export(name="dkimTextValue", refs={String.class}, tree="[0]")
    private Output<String> dkimTextValue;

    public Output<String> dkimTextValue() {
        return this.dkimTextValue;
    }
    @Export(name="dkimVerified", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> dkimVerified;

    public Output<Boolean> dkimVerified() {
        return this.dkimVerified;
    }
    /**
     * ID of the Domain to verify (wire from `domain.domainId`). Immutable.
     * 
     */
    @Export(name="domainId", refs={Integer.class}, tree="[0]")
    private Output<Integer> domainId;

    /**
     * @return ID of the Domain to verify (wire from `domain.domainId`). Immutable.
     * 
     */
    public Output<Integer> domainId() {
        return this.domainId;
    }
    /**
     * Maximum seconds to poll for verification to succeed while DNS propagates. Defaults to 0 (a single, non-blocking attempt).
     * 
     */
    @Export(name="pollTimeoutSeconds", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> pollTimeoutSeconds;

    /**
     * @return Maximum seconds to poll for verification to succeed while DNS propagates. Defaults to 0 (a single, non-blocking attempt).
     * 
     */
    public Output<Optional<Integer>> pollTimeoutSeconds() {
        return Codegen.optional(this.pollTimeoutSeconds);
    }
    @Export(name="returnPathDomainVerified", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> returnPathDomainVerified;

    public Output<Boolean> returnPathDomainVerified() {
        return this.returnPathDomainVerified;
    }
    /**
     * Arbitrary value; change it to force re-verification on the next update.
     * 
     */
    @Export(name="trigger", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> trigger;

    /**
     * @return Arbitrary value; change it to force re-verification on the next update.
     * 
     */
    public Output<Optional<String>> trigger() {
        return Codegen.optional(this.trigger);
    }
    /**
     * Whether to verify DKIM. Defaults to true.
     * 
     */
    @Export(name="verifyDkim", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> verifyDkim;

    /**
     * @return Whether to verify DKIM. Defaults to true.
     * 
     */
    public Output<Optional<Boolean>> verifyDkim() {
        return Codegen.optional(this.verifyDkim);
    }
    /**
     * Whether to verify the Return-Path CNAME. Defaults to true.
     * 
     */
    @Export(name="verifyReturnPath", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> verifyReturnPath;

    /**
     * @return Whether to verify the Return-Path CNAME. Defaults to true.
     * 
     */
    public Output<Optional<Boolean>> verifyReturnPath() {
        return Codegen.optional(this.verifyReturnPath);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public DomainVerification(java.lang.String name) {
        this(name, DomainVerificationArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public DomainVerification(java.lang.String name, DomainVerificationArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public DomainVerification(java.lang.String name, DomainVerificationArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("postmark:index:DomainVerification", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private DomainVerification(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("postmark:index:DomainVerification", name, null, makeResourceOptions(options, id), false);
    }

    private static DomainVerificationArgs makeArgs(DomainVerificationArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? DomainVerificationArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/hummingbird-me/pulumi-postmark")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static DomainVerification get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new DomainVerification(name, id, options);
    }
}
