// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.hummingbirdme.postmark;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProviderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProviderArgs Empty = new ProviderArgs();

    /**
     * Postmark Account API token (X-Postmark-Account-Token). Required to manage Servers, Domains and Sender Signatures. May also be set via the POSTMARK_ACCOUNT_TOKEN environment variable.
     * 
     */
    @Import(name="accountToken")
    private @Nullable Output<String> accountToken;

    /**
     * @return Postmark Account API token (X-Postmark-Account-Token). Required to manage Servers, Domains and Sender Signatures. May also be set via the POSTMARK_ACCOUNT_TOKEN environment variable.
     * 
     */
    public Optional<Output<String>> accountToken() {
        return Optional.ofNullable(this.accountToken);
    }

    /**
     * Base URL of the Postmark API. Defaults to https://api.postmarkapp.com. May also be set via the POSTMARK_BASE_URL environment variable (useful for testing).
     * 
     */
    @Import(name="baseUrl")
    private @Nullable Output<String> baseUrl;

    /**
     * @return Base URL of the Postmark API. Defaults to https://api.postmarkapp.com. May also be set via the POSTMARK_BASE_URL environment variable (useful for testing).
     * 
     */
    public Optional<Output<String>> baseUrl() {
        return Optional.ofNullable(this.baseUrl);
    }

    /**
     * Default Postmark Server API token (X-Postmark-Server-Token) used for Template operations when a Template does not set its own `serverToken`/`serverId`. Only useful when all Templates live on a single server. May also be set via the POSTMARK_SERVER_TOKEN environment variable.
     * 
     */
    @Import(name="serverToken")
    private @Nullable Output<String> serverToken;

    /**
     * @return Default Postmark Server API token (X-Postmark-Server-Token) used for Template operations when a Template does not set its own `serverToken`/`serverId`. Only useful when all Templates live on a single server. May also be set via the POSTMARK_SERVER_TOKEN environment variable.
     * 
     */
    public Optional<Output<String>> serverToken() {
        return Optional.ofNullable(this.serverToken);
    }

    private ProviderArgs() {}

    private ProviderArgs(ProviderArgs $) {
        this.accountToken = $.accountToken;
        this.baseUrl = $.baseUrl;
        this.serverToken = $.serverToken;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProviderArgs $;

        public Builder() {
            $ = new ProviderArgs();
        }

        public Builder(ProviderArgs defaults) {
            $ = new ProviderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accountToken Postmark Account API token (X-Postmark-Account-Token). Required to manage Servers, Domains and Sender Signatures. May also be set via the POSTMARK_ACCOUNT_TOKEN environment variable.
         * 
         * @return builder
         * 
         */
        public Builder accountToken(@Nullable Output<String> accountToken) {
            $.accountToken = accountToken;
            return this;
        }

        /**
         * @param accountToken Postmark Account API token (X-Postmark-Account-Token). Required to manage Servers, Domains and Sender Signatures. May also be set via the POSTMARK_ACCOUNT_TOKEN environment variable.
         * 
         * @return builder
         * 
         */
        public Builder accountToken(String accountToken) {
            return accountToken(Output.of(accountToken));
        }

        /**
         * @param baseUrl Base URL of the Postmark API. Defaults to https://api.postmarkapp.com. May also be set via the POSTMARK_BASE_URL environment variable (useful for testing).
         * 
         * @return builder
         * 
         */
        public Builder baseUrl(@Nullable Output<String> baseUrl) {
            $.baseUrl = baseUrl;
            return this;
        }

        /**
         * @param baseUrl Base URL of the Postmark API. Defaults to https://api.postmarkapp.com. May also be set via the POSTMARK_BASE_URL environment variable (useful for testing).
         * 
         * @return builder
         * 
         */
        public Builder baseUrl(String baseUrl) {
            return baseUrl(Output.of(baseUrl));
        }

        /**
         * @param serverToken Default Postmark Server API token (X-Postmark-Server-Token) used for Template operations when a Template does not set its own `serverToken`/`serverId`. Only useful when all Templates live on a single server. May also be set via the POSTMARK_SERVER_TOKEN environment variable.
         * 
         * @return builder
         * 
         */
        public Builder serverToken(@Nullable Output<String> serverToken) {
            $.serverToken = serverToken;
            return this;
        }

        /**
         * @param serverToken Default Postmark Server API token (X-Postmark-Server-Token) used for Template operations when a Template does not set its own `serverToken`/`serverId`. Only useful when all Templates live on a single server. May also be set via the POSTMARK_SERVER_TOKEN environment variable.
         * 
         * @return builder
         * 
         */
        public Builder serverToken(String serverToken) {
            return serverToken(Output.of(serverToken));
        }

        public ProviderArgs build() {
            $.accountToken = Codegen.stringProp("accountToken").secret().arg($.accountToken).env("POSTMARK_ACCOUNT_TOKEN").def("").getNullable();
            $.baseUrl = Codegen.stringProp("baseUrl").output().arg($.baseUrl).env("POSTMARK_BASE_URL").def("https://api.postmarkapp.com").getNullable();
            $.serverToken = Codegen.stringProp("serverToken").secret().arg($.serverToken).env("POSTMARK_SERVER_TOKEN").def("").getNullable();
            return $;
        }
    }

}
