// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.hummingbirdme.postmark;

import com.hummingbirdme.postmark.SenderSignatureArgs;
import com.hummingbirdme.postmark.Utilities;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="postmark:index:SenderSignature")
public class SenderSignature extends com.pulumi.resources.CustomResource {
    /**
     * Optional note (max 400 chars) included in the confirmation email.
     * 
     */
    @Export(name="confirmationPersonalNote", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> confirmationPersonalNote;

    /**
     * @return Optional note (max 400 chars) included in the confirmation email.
     * 
     */
    public Output<Optional<String>> confirmationPersonalNote() {
        return Codegen.optional(this.confirmationPersonalNote);
    }
    /**
     * Whether the signature has been confirmed. Postmark requires a human to click the confirmation email; run `pulumi refresh` to observe this flipping to true.
     * 
     */
    @Export(name="confirmed", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> confirmed;

    /**
     * @return Whether the signature has been confirmed. Postmark requires a human to click the confirmation email; run `pulumi refresh` to observe this flipping to true.
     * 
     */
    public Output<Boolean> confirmed() {
        return this.confirmed;
    }
    @Export(name="dkimHost", refs={String.class}, tree="[0]")
    private Output<String> dkimHost;

    public Output<String> dkimHost() {
        return this.dkimHost;
    }
    @Export(name="dkimPendingHost", refs={String.class}, tree="[0]")
    private Output<String> dkimPendingHost;

    public Output<String> dkimPendingHost() {
        return this.dkimPendingHost;
    }
    @Export(name="dkimPendingTextValue", refs={String.class}, tree="[0]")
    private Output<String> dkimPendingTextValue;

    public Output<String> dkimPendingTextValue() {
        return this.dkimPendingTextValue;
    }
    @Export(name="dkimTextValue", refs={String.class}, tree="[0]")
    private Output<String> dkimTextValue;

    public Output<String> dkimTextValue() {
        return this.dkimTextValue;
    }
    @Export(name="dkimVerified", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> dkimVerified;

    public Output<Boolean> dkimVerified() {
        return this.dkimVerified;
    }
    @Export(name="domain", refs={String.class}, tree="[0]")
    private Output<String> domain;

    public Output<String> domain() {
        return this.domain;
    }
    @Export(name="emailAddress", refs={String.class}, tree="[0]")
    private Output<String> emailAddress;

    public Output<String> emailAddress() {
        return this.emailAddress;
    }
    /**
     * The email address to sign. Immutable — changing it replaces the signature.
     * 
     */
    @Export(name="fromEmail", refs={String.class}, tree="[0]")
    private Output<String> fromEmail;

    /**
     * @return The email address to sign. Immutable — changing it replaces the signature.
     * 
     */
    public Output<String> fromEmail() {
        return this.fromEmail;
    }
    /**
     * From name associated with the signature.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return From name associated with the signature.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Optional Reply-To email address.
     * 
     */
    @Export(name="replyToEmail", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> replyToEmail;

    /**
     * @return Optional Reply-To email address.
     * 
     */
    public Output<Optional<String>> replyToEmail() {
        return Codegen.optional(this.replyToEmail);
    }
    /**
     * Optional custom Return-Path subdomain of the From address&#39;s domain.
     * 
     */
    @Export(name="returnPathDomain", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> returnPathDomain;

    /**
     * @return Optional custom Return-Path subdomain of the From address&#39;s domain.
     * 
     */
    public Output<Optional<String>> returnPathDomain() {
        return Codegen.optional(this.returnPathDomain);
    }
    @Export(name="returnPathDomainCnameValue", refs={String.class}, tree="[0]")
    private Output<String> returnPathDomainCnameValue;

    public Output<String> returnPathDomainCnameValue() {
        return this.returnPathDomainCnameValue;
    }
    @Export(name="returnPathDomainVerified", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> returnPathDomainVerified;

    public Output<Boolean> returnPathDomainVerified() {
        return this.returnPathDomainVerified;
    }
    @Export(name="signatureId", refs={Integer.class}, tree="[0]")
    private Output<Integer> signatureId;

    public Output<Integer> signatureId() {
        return this.signatureId;
    }
    /**
     * Arbitrary value; change it to resend the confirmation email on the next update.
     * 
     */
    @Export(name="triggerResend", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> triggerResend;

    /**
     * @return Arbitrary value; change it to resend the confirmation email on the next update.
     * 
     */
    public Output<Optional<String>> triggerResend() {
        return Codegen.optional(this.triggerResend);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public SenderSignature(java.lang.String name) {
        this(name, SenderSignatureArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public SenderSignature(java.lang.String name, SenderSignatureArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public SenderSignature(java.lang.String name, SenderSignatureArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("postmark:index:SenderSignature", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private SenderSignature(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("postmark:index:SenderSignature", name, null, makeResourceOptions(options, id), false);
    }

    private static SenderSignatureArgs makeArgs(SenderSignatureArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? SenderSignatureArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/hummingbird-me/pulumi-postmark")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static SenderSignature get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new SenderSignature(name, id, options);
    }
}
