// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.hummingbirdme.postmark;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SenderSignatureArgs extends com.pulumi.resources.ResourceArgs {

    public static final SenderSignatureArgs Empty = new SenderSignatureArgs();

    /**
     * Optional note (max 400 chars) included in the confirmation email.
     * 
     */
    @Import(name="confirmationPersonalNote")
    private @Nullable Output<String> confirmationPersonalNote;

    /**
     * @return Optional note (max 400 chars) included in the confirmation email.
     * 
     */
    public Optional<Output<String>> confirmationPersonalNote() {
        return Optional.ofNullable(this.confirmationPersonalNote);
    }

    /**
     * The email address to sign. Immutable — changing it replaces the signature.
     * 
     */
    @Import(name="fromEmail", required=true)
    private Output<String> fromEmail;

    /**
     * @return The email address to sign. Immutable — changing it replaces the signature.
     * 
     */
    public Output<String> fromEmail() {
        return this.fromEmail;
    }

    /**
     * From name associated with the signature.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return From name associated with the signature.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * Optional Reply-To email address.
     * 
     */
    @Import(name="replyToEmail")
    private @Nullable Output<String> replyToEmail;

    /**
     * @return Optional Reply-To email address.
     * 
     */
    public Optional<Output<String>> replyToEmail() {
        return Optional.ofNullable(this.replyToEmail);
    }

    /**
     * Optional custom Return-Path subdomain of the From address&#39;s domain.
     * 
     */
    @Import(name="returnPathDomain")
    private @Nullable Output<String> returnPathDomain;

    /**
     * @return Optional custom Return-Path subdomain of the From address&#39;s domain.
     * 
     */
    public Optional<Output<String>> returnPathDomain() {
        return Optional.ofNullable(this.returnPathDomain);
    }

    /**
     * Arbitrary value; change it to resend the confirmation email on the next update.
     * 
     */
    @Import(name="triggerResend")
    private @Nullable Output<String> triggerResend;

    /**
     * @return Arbitrary value; change it to resend the confirmation email on the next update.
     * 
     */
    public Optional<Output<String>> triggerResend() {
        return Optional.ofNullable(this.triggerResend);
    }

    private SenderSignatureArgs() {}

    private SenderSignatureArgs(SenderSignatureArgs $) {
        this.confirmationPersonalNote = $.confirmationPersonalNote;
        this.fromEmail = $.fromEmail;
        this.name = $.name;
        this.replyToEmail = $.replyToEmail;
        this.returnPathDomain = $.returnPathDomain;
        this.triggerResend = $.triggerResend;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SenderSignatureArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SenderSignatureArgs $;

        public Builder() {
            $ = new SenderSignatureArgs();
        }

        public Builder(SenderSignatureArgs defaults) {
            $ = new SenderSignatureArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param confirmationPersonalNote Optional note (max 400 chars) included in the confirmation email.
         * 
         * @return builder
         * 
         */
        public Builder confirmationPersonalNote(@Nullable Output<String> confirmationPersonalNote) {
            $.confirmationPersonalNote = confirmationPersonalNote;
            return this;
        }

        /**
         * @param confirmationPersonalNote Optional note (max 400 chars) included in the confirmation email.
         * 
         * @return builder
         * 
         */
        public Builder confirmationPersonalNote(String confirmationPersonalNote) {
            return confirmationPersonalNote(Output.of(confirmationPersonalNote));
        }

        /**
         * @param fromEmail The email address to sign. Immutable — changing it replaces the signature.
         * 
         * @return builder
         * 
         */
        public Builder fromEmail(Output<String> fromEmail) {
            $.fromEmail = fromEmail;
            return this;
        }

        /**
         * @param fromEmail The email address to sign. Immutable — changing it replaces the signature.
         * 
         * @return builder
         * 
         */
        public Builder fromEmail(String fromEmail) {
            return fromEmail(Output.of(fromEmail));
        }

        /**
         * @param name From name associated with the signature.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name From name associated with the signature.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param replyToEmail Optional Reply-To email address.
         * 
         * @return builder
         * 
         */
        public Builder replyToEmail(@Nullable Output<String> replyToEmail) {
            $.replyToEmail = replyToEmail;
            return this;
        }

        /**
         * @param replyToEmail Optional Reply-To email address.
         * 
         * @return builder
         * 
         */
        public Builder replyToEmail(String replyToEmail) {
            return replyToEmail(Output.of(replyToEmail));
        }

        /**
         * @param returnPathDomain Optional custom Return-Path subdomain of the From address&#39;s domain.
         * 
         * @return builder
         * 
         */
        public Builder returnPathDomain(@Nullable Output<String> returnPathDomain) {
            $.returnPathDomain = returnPathDomain;
            return this;
        }

        /**
         * @param returnPathDomain Optional custom Return-Path subdomain of the From address&#39;s domain.
         * 
         * @return builder
         * 
         */
        public Builder returnPathDomain(String returnPathDomain) {
            return returnPathDomain(Output.of(returnPathDomain));
        }

        /**
         * @param triggerResend Arbitrary value; change it to resend the confirmation email on the next update.
         * 
         * @return builder
         * 
         */
        public Builder triggerResend(@Nullable Output<String> triggerResend) {
            $.triggerResend = triggerResend;
            return this;
        }

        /**
         * @param triggerResend Arbitrary value; change it to resend the confirmation email on the next update.
         * 
         * @return builder
         * 
         */
        public Builder triggerResend(String triggerResend) {
            return triggerResend(Output.of(triggerResend));
        }

        public SenderSignatureArgs build() {
            if ($.fromEmail == null) {
                throw new MissingRequiredPropertyException("SenderSignatureArgs", "fromEmail");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("SenderSignatureArgs", "name");
            }
            return $;
        }
    }

}
