// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.hummingbirdme.postmark;

import com.hummingbirdme.postmark.ServerArgs;
import com.hummingbirdme.postmark.Utilities;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="postmark:index:Server")
public class Server extends com.pulumi.resources.CustomResource {
    @Export(name="apiTokens", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> apiTokens;

    public Output<List<String>> apiTokens() {
        return this.apiTokens;
    }
    /**
     * Color of the server in the Postmark UI server list. One of: Purple, Blue, Turquoise, Green, Red, Yellow, Grey, Orange. Defaults to Blue.
     * 
     */
    @Export(name="color", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> color;

    /**
     * @return Color of the server in the Postmark UI server list. One of: Purple, Blue, Turquoise, Green, Red, Yellow, Grey, Orange. Defaults to Blue.
     * 
     */
    public Output<Optional<String>> color() {
        return Codegen.optional(this.color);
    }
    /**
     * Environment type: `Live` or `Sandbox`. Immutable after creation — changing it replaces the server. Defaults to `Live`.
     * 
     */
    @Export(name="deliveryType", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> deliveryType;

    /**
     * @return Environment type: `Live` or `Sandbox`. Immutable after creation — changing it replaces the server. Defaults to `Live`.
     * 
     */
    public Output<Optional<String>> deliveryType() {
        return Codegen.optional(this.deliveryType);
    }
    @Export(name="enableSmtpApiErrorHooks", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> enableSmtpApiErrorHooks;

    public Output<Optional<Boolean>> enableSmtpApiErrorHooks() {
        return Codegen.optional(this.enableSmtpApiErrorHooks);
    }
    @Export(name="inboundAddress", refs={String.class}, tree="[0]")
    private Output<String> inboundAddress;

    public Output<String> inboundAddress() {
        return this.inboundAddress;
    }
    /**
     * Inbound domain for MX setup. Point an MX record for this domain at `inbound.postmarkapp.com` to receive mail.
     * 
     */
    @Export(name="inboundDomain", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> inboundDomain;

    /**
     * @return Inbound domain for MX setup. Point an MX record for this domain at `inbound.postmarkapp.com` to receive mail.
     * 
     */
    public Output<Optional<String>> inboundDomain() {
        return Codegen.optional(this.inboundDomain);
    }
    @Export(name="inboundHash", refs={String.class}, tree="[0]")
    private Output<String> inboundHash;

    public Output<String> inboundHash() {
        return this.inboundHash;
    }
    /**
     * URL Postmark POSTs to for every inbound email event.
     * 
     */
    @Export(name="inboundHookUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> inboundHookUrl;

    /**
     * @return URL Postmark POSTs to for every inbound email event.
     * 
     */
    public Output<Optional<String>> inboundHookUrl() {
        return Codegen.optional(this.inboundHookUrl);
    }
    /**
     * Maximum spam score before an inbound message is blocked.
     * 
     */
    @Export(name="inboundSpamThreshold", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> inboundSpamThreshold;

    /**
     * @return Maximum spam score before an inbound message is blocked.
     * 
     */
    public Output<Optional<Integer>> inboundSpamThreshold() {
        return Codegen.optional(this.inboundSpamThreshold);
    }
    @Export(name="includeBounceContentInHook", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> includeBounceContentInHook;

    public Output<Optional<Boolean>> includeBounceContentInHook() {
        return Codegen.optional(this.includeBounceContentInHook);
    }
    /**
     * Friendly name of the server.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Friendly name of the server.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    @Export(name="postFirstOpenOnly", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> postFirstOpenOnly;

    public Output<Optional<Boolean>> postFirstOpenOnly() {
        return Codegen.optional(this.postFirstOpenOnly);
    }
    @Export(name="rawEmailEnabled", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> rawEmailEnabled;

    public Output<Optional<Boolean>> rawEmailEnabled() {
        return Codegen.optional(this.rawEmailEnabled);
    }
    @Export(name="serverId", refs={Integer.class}, tree="[0]")
    private Output<Integer> serverId;

    public Output<Integer> serverId() {
        return this.serverId;
    }
    @Export(name="serverLink", refs={String.class}, tree="[0]")
    private Output<String> serverLink;

    public Output<String> serverLink() {
        return this.serverLink;
    }
    @Export(name="smtpApiActivated", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> smtpApiActivated;

    public Output<Optional<Boolean>> smtpApiActivated() {
        return Codegen.optional(this.smtpApiActivated);
    }
    /**
     * Link tracking mode: None, HtmlAndText, HtmlOnly or TextOnly. Defaults to None.
     * 
     */
    @Export(name="trackLinks", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> trackLinks;

    /**
     * @return Link tracking mode: None, HtmlAndText, HtmlOnly or TextOnly. Defaults to None.
     * 
     */
    public Output<Optional<String>> trackLinks() {
        return Codegen.optional(this.trackLinks);
    }
    /**
     * Enable open tracking for messages by default.
     * 
     */
    @Export(name="trackOpens", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> trackOpens;

    /**
     * @return Enable open tracking for messages by default.
     * 
     */
    public Output<Optional<Boolean>> trackOpens() {
        return Codegen.optional(this.trackOpens);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Server(java.lang.String name) {
        this(name, ServerArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Server(java.lang.String name, ServerArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Server(java.lang.String name, ServerArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("postmark:index:Server", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Server(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("postmark:index:Server", name, null, makeResourceOptions(options, id), false);
    }

    private static ServerArgs makeArgs(ServerArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ServerArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/hummingbird-me/pulumi-postmark")
            .additionalSecretOutputs(List.of(
                "apiTokens"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Server get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Server(name, id, options);
    }
}
