// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.hummingbirdme.postmark;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ServerArgs extends com.pulumi.resources.ResourceArgs {

    public static final ServerArgs Empty = new ServerArgs();

    /**
     * Color of the server in the Postmark UI server list. One of: Purple, Blue, Turquoise, Green, Red, Yellow, Grey, Orange.
     * 
     */
    @Import(name="color")
    private @Nullable Output<String> color;

    /**
     * @return Color of the server in the Postmark UI server list. One of: Purple, Blue, Turquoise, Green, Red, Yellow, Grey, Orange.
     * 
     */
    public Optional<Output<String>> color() {
        return Optional.ofNullable(this.color);
    }

    /**
     * Environment type: `Live` or `Sandbox`. Immutable after creation — changing it replaces the server. Defaults to `Live`.
     * 
     */
    @Import(name="deliveryType")
    private @Nullable Output<String> deliveryType;

    /**
     * @return Environment type: `Live` or `Sandbox`. Immutable after creation — changing it replaces the server. Defaults to `Live`.
     * 
     */
    public Optional<Output<String>> deliveryType() {
        return Optional.ofNullable(this.deliveryType);
    }

    @Import(name="enableSmtpApiErrorHooks")
    private @Nullable Output<Boolean> enableSmtpApiErrorHooks;

    public Optional<Output<Boolean>> enableSmtpApiErrorHooks() {
        return Optional.ofNullable(this.enableSmtpApiErrorHooks);
    }

    /**
     * Inbound domain for MX setup. Point an MX record for this domain at `inbound.postmarkapp.com` to receive mail.
     * 
     */
    @Import(name="inboundDomain")
    private @Nullable Output<String> inboundDomain;

    /**
     * @return Inbound domain for MX setup. Point an MX record for this domain at `inbound.postmarkapp.com` to receive mail.
     * 
     */
    public Optional<Output<String>> inboundDomain() {
        return Optional.ofNullable(this.inboundDomain);
    }

    /**
     * URL Postmark POSTs to for every inbound email event.
     * 
     */
    @Import(name="inboundHookUrl")
    private @Nullable Output<String> inboundHookUrl;

    /**
     * @return URL Postmark POSTs to for every inbound email event.
     * 
     */
    public Optional<Output<String>> inboundHookUrl() {
        return Optional.ofNullable(this.inboundHookUrl);
    }

    /**
     * Maximum spam score before an inbound message is blocked.
     * 
     */
    @Import(name="inboundSpamThreshold")
    private @Nullable Output<Integer> inboundSpamThreshold;

    /**
     * @return Maximum spam score before an inbound message is blocked.
     * 
     */
    public Optional<Output<Integer>> inboundSpamThreshold() {
        return Optional.ofNullable(this.inboundSpamThreshold);
    }

    @Import(name="includeBounceContentInHook")
    private @Nullable Output<Boolean> includeBounceContentInHook;

    public Optional<Output<Boolean>> includeBounceContentInHook() {
        return Optional.ofNullable(this.includeBounceContentInHook);
    }

    /**
     * Friendly name of the server.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Friendly name of the server.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    @Import(name="postFirstOpenOnly")
    private @Nullable Output<Boolean> postFirstOpenOnly;

    public Optional<Output<Boolean>> postFirstOpenOnly() {
        return Optional.ofNullable(this.postFirstOpenOnly);
    }

    @Import(name="rawEmailEnabled")
    private @Nullable Output<Boolean> rawEmailEnabled;

    public Optional<Output<Boolean>> rawEmailEnabled() {
        return Optional.ofNullable(this.rawEmailEnabled);
    }

    @Import(name="smtpApiActivated")
    private @Nullable Output<Boolean> smtpApiActivated;

    public Optional<Output<Boolean>> smtpApiActivated() {
        return Optional.ofNullable(this.smtpApiActivated);
    }

    /**
     * Link tracking mode: None, HtmlAndText, HtmlOnly or TextOnly.
     * 
     */
    @Import(name="trackLinks")
    private @Nullable Output<String> trackLinks;

    /**
     * @return Link tracking mode: None, HtmlAndText, HtmlOnly or TextOnly.
     * 
     */
    public Optional<Output<String>> trackLinks() {
        return Optional.ofNullable(this.trackLinks);
    }

    /**
     * Enable open tracking for messages by default.
     * 
     */
    @Import(name="trackOpens")
    private @Nullable Output<Boolean> trackOpens;

    /**
     * @return Enable open tracking for messages by default.
     * 
     */
    public Optional<Output<Boolean>> trackOpens() {
        return Optional.ofNullable(this.trackOpens);
    }

    private ServerArgs() {}

    private ServerArgs(ServerArgs $) {
        this.color = $.color;
        this.deliveryType = $.deliveryType;
        this.enableSmtpApiErrorHooks = $.enableSmtpApiErrorHooks;
        this.inboundDomain = $.inboundDomain;
        this.inboundHookUrl = $.inboundHookUrl;
        this.inboundSpamThreshold = $.inboundSpamThreshold;
        this.includeBounceContentInHook = $.includeBounceContentInHook;
        this.name = $.name;
        this.postFirstOpenOnly = $.postFirstOpenOnly;
        this.rawEmailEnabled = $.rawEmailEnabled;
        this.smtpApiActivated = $.smtpApiActivated;
        this.trackLinks = $.trackLinks;
        this.trackOpens = $.trackOpens;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ServerArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ServerArgs $;

        public Builder() {
            $ = new ServerArgs();
        }

        public Builder(ServerArgs defaults) {
            $ = new ServerArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param color Color of the server in the Postmark UI server list. One of: Purple, Blue, Turquoise, Green, Red, Yellow, Grey, Orange.
         * 
         * @return builder
         * 
         */
        public Builder color(@Nullable Output<String> color) {
            $.color = color;
            return this;
        }

        /**
         * @param color Color of the server in the Postmark UI server list. One of: Purple, Blue, Turquoise, Green, Red, Yellow, Grey, Orange.
         * 
         * @return builder
         * 
         */
        public Builder color(String color) {
            return color(Output.of(color));
        }

        /**
         * @param deliveryType Environment type: `Live` or `Sandbox`. Immutable after creation — changing it replaces the server. Defaults to `Live`.
         * 
         * @return builder
         * 
         */
        public Builder deliveryType(@Nullable Output<String> deliveryType) {
            $.deliveryType = deliveryType;
            return this;
        }

        /**
         * @param deliveryType Environment type: `Live` or `Sandbox`. Immutable after creation — changing it replaces the server. Defaults to `Live`.
         * 
         * @return builder
         * 
         */
        public Builder deliveryType(String deliveryType) {
            return deliveryType(Output.of(deliveryType));
        }

        public Builder enableSmtpApiErrorHooks(@Nullable Output<Boolean> enableSmtpApiErrorHooks) {
            $.enableSmtpApiErrorHooks = enableSmtpApiErrorHooks;
            return this;
        }

        public Builder enableSmtpApiErrorHooks(Boolean enableSmtpApiErrorHooks) {
            return enableSmtpApiErrorHooks(Output.of(enableSmtpApiErrorHooks));
        }

        /**
         * @param inboundDomain Inbound domain for MX setup. Point an MX record for this domain at `inbound.postmarkapp.com` to receive mail.
         * 
         * @return builder
         * 
         */
        public Builder inboundDomain(@Nullable Output<String> inboundDomain) {
            $.inboundDomain = inboundDomain;
            return this;
        }

        /**
         * @param inboundDomain Inbound domain for MX setup. Point an MX record for this domain at `inbound.postmarkapp.com` to receive mail.
         * 
         * @return builder
         * 
         */
        public Builder inboundDomain(String inboundDomain) {
            return inboundDomain(Output.of(inboundDomain));
        }

        /**
         * @param inboundHookUrl URL Postmark POSTs to for every inbound email event.
         * 
         * @return builder
         * 
         */
        public Builder inboundHookUrl(@Nullable Output<String> inboundHookUrl) {
            $.inboundHookUrl = inboundHookUrl;
            return this;
        }

        /**
         * @param inboundHookUrl URL Postmark POSTs to for every inbound email event.
         * 
         * @return builder
         * 
         */
        public Builder inboundHookUrl(String inboundHookUrl) {
            return inboundHookUrl(Output.of(inboundHookUrl));
        }

        /**
         * @param inboundSpamThreshold Maximum spam score before an inbound message is blocked.
         * 
         * @return builder
         * 
         */
        public Builder inboundSpamThreshold(@Nullable Output<Integer> inboundSpamThreshold) {
            $.inboundSpamThreshold = inboundSpamThreshold;
            return this;
        }

        /**
         * @param inboundSpamThreshold Maximum spam score before an inbound message is blocked.
         * 
         * @return builder
         * 
         */
        public Builder inboundSpamThreshold(Integer inboundSpamThreshold) {
            return inboundSpamThreshold(Output.of(inboundSpamThreshold));
        }

        public Builder includeBounceContentInHook(@Nullable Output<Boolean> includeBounceContentInHook) {
            $.includeBounceContentInHook = includeBounceContentInHook;
            return this;
        }

        public Builder includeBounceContentInHook(Boolean includeBounceContentInHook) {
            return includeBounceContentInHook(Output.of(includeBounceContentInHook));
        }

        /**
         * @param name Friendly name of the server.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Friendly name of the server.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public Builder postFirstOpenOnly(@Nullable Output<Boolean> postFirstOpenOnly) {
            $.postFirstOpenOnly = postFirstOpenOnly;
            return this;
        }

        public Builder postFirstOpenOnly(Boolean postFirstOpenOnly) {
            return postFirstOpenOnly(Output.of(postFirstOpenOnly));
        }

        public Builder rawEmailEnabled(@Nullable Output<Boolean> rawEmailEnabled) {
            $.rawEmailEnabled = rawEmailEnabled;
            return this;
        }

        public Builder rawEmailEnabled(Boolean rawEmailEnabled) {
            return rawEmailEnabled(Output.of(rawEmailEnabled));
        }

        public Builder smtpApiActivated(@Nullable Output<Boolean> smtpApiActivated) {
            $.smtpApiActivated = smtpApiActivated;
            return this;
        }

        public Builder smtpApiActivated(Boolean smtpApiActivated) {
            return smtpApiActivated(Output.of(smtpApiActivated));
        }

        /**
         * @param trackLinks Link tracking mode: None, HtmlAndText, HtmlOnly or TextOnly.
         * 
         * @return builder
         * 
         */
        public Builder trackLinks(@Nullable Output<String> trackLinks) {
            $.trackLinks = trackLinks;
            return this;
        }

        /**
         * @param trackLinks Link tracking mode: None, HtmlAndText, HtmlOnly or TextOnly.
         * 
         * @return builder
         * 
         */
        public Builder trackLinks(String trackLinks) {
            return trackLinks(Output.of(trackLinks));
        }

        /**
         * @param trackOpens Enable open tracking for messages by default.
         * 
         * @return builder
         * 
         */
        public Builder trackOpens(@Nullable Output<Boolean> trackOpens) {
            $.trackOpens = trackOpens;
            return this;
        }

        /**
         * @param trackOpens Enable open tracking for messages by default.
         * 
         * @return builder
         * 
         */
        public Builder trackOpens(Boolean trackOpens) {
            return trackOpens(Output.of(trackOpens));
        }

        public ServerArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("ServerArgs", "name");
            }
            return $;
        }
    }

}
