// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.hummingbirdme.postmark;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class TemplateArgs extends com.pulumi.resources.ResourceArgs {

    public static final TemplateArgs Empty = new TemplateArgs();

    /**
     * Optional unique alias (within the server). Must start with a letter; may contain letters, digits, &#39;.&#39;, &#39;-&#39; and &#39;_&#39;.
     * 
     */
    @Import(name="alias")
    private @Nullable Output<String> alias;

    /**
     * @return Optional unique alias (within the server). Must start with a letter; may contain letters, digits, &#39;.&#39;, &#39;-&#39; and &#39;_&#39;.
     * 
     */
    public Optional<Output<String>> alias() {
        return Optional.ofNullable(this.alias);
    }

    /**
     * HTML body. Required unless `textBody` is set.
     * 
     */
    @Import(name="htmlBody")
    private @Nullable Output<String> htmlBody;

    /**
     * @return HTML body. Required unless `textBody` is set.
     * 
     */
    public Optional<Output<String>> htmlBody() {
        return Optional.ofNullable(this.htmlBody);
    }

    /**
     * Alias of a Layout to wrap this Standard template (set to &#34;&#34; to disassociate).
     * 
     */
    @Import(name="layoutTemplate")
    private @Nullable Output<String> layoutTemplate;

    /**
     * @return Alias of a Layout to wrap this Standard template (set to &#34;&#34; to disassociate).
     * 
     */
    public Optional<Output<String>> layoutTemplate() {
        return Optional.ofNullable(this.layoutTemplate);
    }

    /**
     * Name of the template.
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return Name of the template.
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * ID of the server this template belongs to; the provider looks up its token via the account token. Immutable — changing it replaces the template.
     * 
     */
    @Import(name="serverId")
    private @Nullable Output<Integer> serverId;

    /**
     * @return ID of the server this template belongs to; the provider looks up its token via the account token. Immutable — changing it replaces the template.
     * 
     */
    public Optional<Output<Integer>> serverId() {
        return Optional.ofNullable(this.serverId);
    }

    /**
     * Server API token of the server this template belongs to. Wire from `server.apiTokens[0]`. Falls back to `serverId` lookup, then the provider `serverToken` config.
     * 
     */
    @Import(name="serverToken")
    private @Nullable Output<String> serverToken;

    /**
     * @return Server API token of the server this template belongs to. Wire from `server.apiTokens[0]`. Falls back to `serverId` lookup, then the provider `serverToken` config.
     * 
     */
    public Optional<Output<String>> serverToken() {
        return Optional.ofNullable(this.serverToken);
    }

    /**
     * Subject line. Required for Standard templates; not allowed for Layouts.
     * 
     */
    @Import(name="subject")
    private @Nullable Output<String> subject;

    /**
     * @return Subject line. Required for Standard templates; not allowed for Layouts.
     * 
     */
    public Optional<Output<String>> subject() {
        return Optional.ofNullable(this.subject);
    }

    /**
     * `Standard` (default) or `Layout`. Immutable — changing it replaces the template.
     * 
     */
    @Import(name="templateType")
    private @Nullable Output<String> templateType;

    /**
     * @return `Standard` (default) or `Layout`. Immutable — changing it replaces the template.
     * 
     */
    public Optional<Output<String>> templateType() {
        return Optional.ofNullable(this.templateType);
    }

    /**
     * Plain-text body. Required unless `htmlBody` is set.
     * 
     */
    @Import(name="textBody")
    private @Nullable Output<String> textBody;

    /**
     * @return Plain-text body. Required unless `htmlBody` is set.
     * 
     */
    public Optional<Output<String>> textBody() {
        return Optional.ofNullable(this.textBody);
    }

    private TemplateArgs() {}

    private TemplateArgs(TemplateArgs $) {
        this.alias = $.alias;
        this.htmlBody = $.htmlBody;
        this.layoutTemplate = $.layoutTemplate;
        this.name = $.name;
        this.serverId = $.serverId;
        this.serverToken = $.serverToken;
        this.subject = $.subject;
        this.templateType = $.templateType;
        this.textBody = $.textBody;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TemplateArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TemplateArgs $;

        public Builder() {
            $ = new TemplateArgs();
        }

        public Builder(TemplateArgs defaults) {
            $ = new TemplateArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param alias Optional unique alias (within the server). Must start with a letter; may contain letters, digits, &#39;.&#39;, &#39;-&#39; and &#39;_&#39;.
         * 
         * @return builder
         * 
         */
        public Builder alias(@Nullable Output<String> alias) {
            $.alias = alias;
            return this;
        }

        /**
         * @param alias Optional unique alias (within the server). Must start with a letter; may contain letters, digits, &#39;.&#39;, &#39;-&#39; and &#39;_&#39;.
         * 
         * @return builder
         * 
         */
        public Builder alias(String alias) {
            return alias(Output.of(alias));
        }

        /**
         * @param htmlBody HTML body. Required unless `textBody` is set.
         * 
         * @return builder
         * 
         */
        public Builder htmlBody(@Nullable Output<String> htmlBody) {
            $.htmlBody = htmlBody;
            return this;
        }

        /**
         * @param htmlBody HTML body. Required unless `textBody` is set.
         * 
         * @return builder
         * 
         */
        public Builder htmlBody(String htmlBody) {
            return htmlBody(Output.of(htmlBody));
        }

        /**
         * @param layoutTemplate Alias of a Layout to wrap this Standard template (set to &#34;&#34; to disassociate).
         * 
         * @return builder
         * 
         */
        public Builder layoutTemplate(@Nullable Output<String> layoutTemplate) {
            $.layoutTemplate = layoutTemplate;
            return this;
        }

        /**
         * @param layoutTemplate Alias of a Layout to wrap this Standard template (set to &#34;&#34; to disassociate).
         * 
         * @return builder
         * 
         */
        public Builder layoutTemplate(String layoutTemplate) {
            return layoutTemplate(Output.of(layoutTemplate));
        }

        /**
         * @param name Name of the template.
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name of the template.
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param serverId ID of the server this template belongs to; the provider looks up its token via the account token. Immutable — changing it replaces the template.
         * 
         * @return builder
         * 
         */
        public Builder serverId(@Nullable Output<Integer> serverId) {
            $.serverId = serverId;
            return this;
        }

        /**
         * @param serverId ID of the server this template belongs to; the provider looks up its token via the account token. Immutable — changing it replaces the template.
         * 
         * @return builder
         * 
         */
        public Builder serverId(Integer serverId) {
            return serverId(Output.of(serverId));
        }

        /**
         * @param serverToken Server API token of the server this template belongs to. Wire from `server.apiTokens[0]`. Falls back to `serverId` lookup, then the provider `serverToken` config.
         * 
         * @return builder
         * 
         */
        public Builder serverToken(@Nullable Output<String> serverToken) {
            $.serverToken = serverToken;
            return this;
        }

        /**
         * @param serverToken Server API token of the server this template belongs to. Wire from `server.apiTokens[0]`. Falls back to `serverId` lookup, then the provider `serverToken` config.
         * 
         * @return builder
         * 
         */
        public Builder serverToken(String serverToken) {
            return serverToken(Output.of(serverToken));
        }

        /**
         * @param subject Subject line. Required for Standard templates; not allowed for Layouts.
         * 
         * @return builder
         * 
         */
        public Builder subject(@Nullable Output<String> subject) {
            $.subject = subject;
            return this;
        }

        /**
         * @param subject Subject line. Required for Standard templates; not allowed for Layouts.
         * 
         * @return builder
         * 
         */
        public Builder subject(String subject) {
            return subject(Output.of(subject));
        }

        /**
         * @param templateType `Standard` (default) or `Layout`. Immutable — changing it replaces the template.
         * 
         * @return builder
         * 
         */
        public Builder templateType(@Nullable Output<String> templateType) {
            $.templateType = templateType;
            return this;
        }

        /**
         * @param templateType `Standard` (default) or `Layout`. Immutable — changing it replaces the template.
         * 
         * @return builder
         * 
         */
        public Builder templateType(String templateType) {
            return templateType(Output.of(templateType));
        }

        /**
         * @param textBody Plain-text body. Required unless `htmlBody` is set.
         * 
         * @return builder
         * 
         */
        public Builder textBody(@Nullable Output<String> textBody) {
            $.textBody = textBody;
            return this;
        }

        /**
         * @param textBody Plain-text body. Required unless `htmlBody` is set.
         * 
         * @return builder
         * 
         */
        public Builder textBody(String textBody) {
            return textBody(Output.of(textBody));
        }

        public TemplateArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("TemplateArgs", "name");
            }
            return $;
        }
    }

}
