// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.hummingbirdme.postmark;

import com.hummingbirdme.postmark.TemplateArgs;
import com.hummingbirdme.postmark.Utilities;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

@ResourceType(type="postmark:index:Template")
public class Template extends com.pulumi.resources.CustomResource {
    @Export(name="active", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> active;

    public Output<Boolean> active() {
        return this.active;
    }
    /**
     * Optional unique alias (within the server). Must start with a letter; may contain letters, digits, &#39;.&#39;, &#39;-&#39; and &#39;_&#39;.
     * 
     */
    @Export(name="alias", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> alias;

    /**
     * @return Optional unique alias (within the server). Must start with a letter; may contain letters, digits, &#39;.&#39;, &#39;-&#39; and &#39;_&#39;.
     * 
     */
    public Output<Optional<String>> alias() {
        return Codegen.optional(this.alias);
    }
    @Export(name="associatedServerId", refs={Integer.class}, tree="[0]")
    private Output<Integer> associatedServerId;

    public Output<Integer> associatedServerId() {
        return this.associatedServerId;
    }
    /**
     * HTML body. Required unless `textBody` is set.
     * 
     */
    @Export(name="htmlBody", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> htmlBody;

    /**
     * @return HTML body. Required unless `textBody` is set.
     * 
     */
    public Output<Optional<String>> htmlBody() {
        return Codegen.optional(this.htmlBody);
    }
    /**
     * Alias of a Layout to wrap this Standard template (set to &#34;&#34; to disassociate).
     * 
     */
    @Export(name="layoutTemplate", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> layoutTemplate;

    /**
     * @return Alias of a Layout to wrap this Standard template (set to &#34;&#34; to disassociate).
     * 
     */
    public Output<Optional<String>> layoutTemplate() {
        return Codegen.optional(this.layoutTemplate);
    }
    /**
     * Name of the template.
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Name of the template.
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * ID of the server this template belongs to; the provider looks up its token via the account token. Immutable — changing it replaces the template.
     * 
     */
    @Export(name="serverId", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> serverId;

    /**
     * @return ID of the server this template belongs to; the provider looks up its token via the account token. Immutable — changing it replaces the template.
     * 
     */
    public Output<Optional<Integer>> serverId() {
        return Codegen.optional(this.serverId);
    }
    /**
     * Server API token of the server this template belongs to. Wire from `server.apiTokens[0]`. Falls back to `serverId` lookup, then the provider `serverToken` config.
     * 
     */
    @Export(name="serverToken", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> serverToken;

    /**
     * @return Server API token of the server this template belongs to. Wire from `server.apiTokens[0]`. Falls back to `serverId` lookup, then the provider `serverToken` config.
     * 
     */
    public Output<Optional<String>> serverToken() {
        return Codegen.optional(this.serverToken);
    }
    /**
     * Subject line. Required for Standard templates; not allowed for Layouts.
     * 
     */
    @Export(name="subject", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> subject;

    /**
     * @return Subject line. Required for Standard templates; not allowed for Layouts.
     * 
     */
    public Output<Optional<String>> subject() {
        return Codegen.optional(this.subject);
    }
    @Export(name="templateId", refs={Integer.class}, tree="[0]")
    private Output<Integer> templateId;

    public Output<Integer> templateId() {
        return this.templateId;
    }
    /**
     * `Standard` (default) or `Layout`. Immutable — changing it replaces the template.
     * 
     */
    @Export(name="templateType", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> templateType;

    /**
     * @return `Standard` (default) or `Layout`. Immutable — changing it replaces the template.
     * 
     */
    public Output<Optional<String>> templateType() {
        return Codegen.optional(this.templateType);
    }
    /**
     * Plain-text body. Required unless `htmlBody` is set.
     * 
     */
    @Export(name="textBody", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> textBody;

    /**
     * @return Plain-text body. Required unless `htmlBody` is set.
     * 
     */
    public Output<Optional<String>> textBody() {
        return Codegen.optional(this.textBody);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public Template(java.lang.String name) {
        this(name, TemplateArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public Template(java.lang.String name, TemplateArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public Template(java.lang.String name, TemplateArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("postmark:index:Template", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private Template(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("postmark:index:Template", name, null, makeResourceOptions(options, id), false);
    }

    private static TemplateArgs makeArgs(TemplateArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? TemplateArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/hummingbird-me/pulumi-postmark")
            .additionalSecretOutputs(List.of(
                "serverToken"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static Template get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new Template(name, id, options);
    }
}
