// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DomainVerification extends pulumi.CustomResource {
    /**
     * Get an existing DomainVerification resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): DomainVerification {
        return new DomainVerification(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'postmark:index:DomainVerification';

    /**
     * Returns true if the given object is an instance of DomainVerification.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DomainVerification {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DomainVerification.__pulumiType;
    }

    declare public /*out*/ readonly dkimHost: pulumi.Output<string>;
    declare public /*out*/ readonly dkimTextValue: pulumi.Output<string>;
    declare public /*out*/ readonly dkimVerified: pulumi.Output<boolean>;
    /**
     * ID of the Domain to verify (wire from `domain.domainId`). Immutable.
     */
    declare public readonly domainId: pulumi.Output<number>;
    /**
     * Maximum seconds to poll for verification to succeed while DNS propagates. Defaults to 0 (a single, non-blocking attempt).
     */
    declare public readonly pollTimeoutSeconds: pulumi.Output<number | undefined>;
    declare public /*out*/ readonly returnPathDomainVerified: pulumi.Output<boolean>;
    /**
     * Arbitrary value; change it to force re-verification on the next update.
     */
    declare public readonly trigger: pulumi.Output<string | undefined>;
    /**
     * Whether to verify DKIM. Defaults to true.
     */
    declare public readonly verifyDkim: pulumi.Output<boolean | undefined>;
    /**
     * Whether to verify the Return-Path CNAME. Defaults to true.
     */
    declare public readonly verifyReturnPath: pulumi.Output<boolean | undefined>;

    /**
     * Create a DomainVerification resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DomainVerificationArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.domainId === undefined && !opts.urn) {
                throw new Error("Missing required property 'domainId'");
            }
            resourceInputs["domainId"] = args?.domainId;
            resourceInputs["pollTimeoutSeconds"] = args?.pollTimeoutSeconds;
            resourceInputs["trigger"] = args?.trigger;
            resourceInputs["verifyDkim"] = args?.verifyDkim;
            resourceInputs["verifyReturnPath"] = args?.verifyReturnPath;
            resourceInputs["dkimHost"] = undefined /*out*/;
            resourceInputs["dkimTextValue"] = undefined /*out*/;
            resourceInputs["dkimVerified"] = undefined /*out*/;
            resourceInputs["returnPathDomainVerified"] = undefined /*out*/;
        } else {
            resourceInputs["dkimHost"] = undefined /*out*/;
            resourceInputs["dkimTextValue"] = undefined /*out*/;
            resourceInputs["dkimVerified"] = undefined /*out*/;
            resourceInputs["domainId"] = undefined /*out*/;
            resourceInputs["pollTimeoutSeconds"] = undefined /*out*/;
            resourceInputs["returnPathDomainVerified"] = undefined /*out*/;
            resourceInputs["trigger"] = undefined /*out*/;
            resourceInputs["verifyDkim"] = undefined /*out*/;
            resourceInputs["verifyReturnPath"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["domainId"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(DomainVerification.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a DomainVerification resource.
 */
export interface DomainVerificationArgs {
    /**
     * ID of the Domain to verify (wire from `domain.domainId`). Immutable.
     */
    domainId: pulumi.Input<number>;
    /**
     * Maximum seconds to poll for verification to succeed while DNS propagates. Defaults to 0 (a single, non-blocking attempt).
     */
    pollTimeoutSeconds?: pulumi.Input<number>;
    /**
     * Arbitrary value; change it to force re-verification on the next update.
     */
    trigger?: pulumi.Input<string>;
    /**
     * Whether to verify DKIM. Defaults to true.
     */
    verifyDkim?: pulumi.Input<boolean>;
    /**
     * Whether to verify the Return-Path CNAME. Defaults to true.
     */
    verifyReturnPath?: pulumi.Input<boolean>;
}
