// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Domain extends pulumi.CustomResource {
    /**
     * Get an existing Domain resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Domain {
        return new Domain(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'postmark:index:Domain';

    /**
     * Returns true if the given object is an instance of Domain.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Domain {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Domain.__pulumiType;
    }

    /**
     * Hostname of the currently-active DKIM record (populated after verification).
     */
    declare public /*out*/ readonly dkimHost: pulumi.Output<string>;
    /**
     * Hostname for the DKIM TXT record to publish (publish this first).
     */
    declare public /*out*/ readonly dkimPendingHost: pulumi.Output<string>;
    /**
     * Value for the DKIM TXT record to publish.
     */
    declare public /*out*/ readonly dkimPendingTextValue: pulumi.Output<string>;
    declare public /*out*/ readonly dkimRevokedHost: pulumi.Output<string>;
    declare public /*out*/ readonly dkimRevokedTextValue: pulumi.Output<string>;
    /**
     * Value of the currently-active DKIM record.
     */
    declare public /*out*/ readonly dkimTextValue: pulumi.Output<string>;
    declare public /*out*/ readonly dkimUpdateStatus: pulumi.Output<string>;
    /**
     * Whether DKIM has been verified by Postmark.
     */
    declare public /*out*/ readonly dkimVerified: pulumi.Output<boolean>;
    declare public /*out*/ readonly domainId: pulumi.Output<number>;
    /**
     * The domain name to send from (e.g. `example.com`). Immutable — changing it replaces the domain.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Custom Return-Path subdomain (e.g. `pm-bounces.example.com`). Must be a subdomain of `name` and have a CNAME pointing at the value of `returnPathDomainCnameValue`.
     */
    declare public readonly returnPathDomain: pulumi.Output<string | undefined>;
    /**
     * CNAME target for the Return-Path record (typically `pm.mtasv.net`).
     */
    declare public /*out*/ readonly returnPathDomainCnameValue: pulumi.Output<string>;
    /**
     * Whether the Return-Path CNAME has been verified by Postmark.
     */
    declare public /*out*/ readonly returnPathDomainVerified: pulumi.Output<boolean>;
    declare public /*out*/ readonly safeToRemoveRevokedKeyFromDns: pulumi.Output<boolean>;
    declare public /*out*/ readonly spfHost: pulumi.Output<string>;
    declare public /*out*/ readonly spfTextValue: pulumi.Output<string>;
    declare public /*out*/ readonly spfVerified: pulumi.Output<boolean>;
    declare public /*out*/ readonly weakDkim: pulumi.Output<boolean>;

    /**
     * Create a Domain resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DomainArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["returnPathDomain"] = args?.returnPathDomain;
            resourceInputs["dkimHost"] = undefined /*out*/;
            resourceInputs["dkimPendingHost"] = undefined /*out*/;
            resourceInputs["dkimPendingTextValue"] = undefined /*out*/;
            resourceInputs["dkimRevokedHost"] = undefined /*out*/;
            resourceInputs["dkimRevokedTextValue"] = undefined /*out*/;
            resourceInputs["dkimTextValue"] = undefined /*out*/;
            resourceInputs["dkimUpdateStatus"] = undefined /*out*/;
            resourceInputs["dkimVerified"] = undefined /*out*/;
            resourceInputs["domainId"] = undefined /*out*/;
            resourceInputs["returnPathDomainCnameValue"] = undefined /*out*/;
            resourceInputs["returnPathDomainVerified"] = undefined /*out*/;
            resourceInputs["safeToRemoveRevokedKeyFromDns"] = undefined /*out*/;
            resourceInputs["spfHost"] = undefined /*out*/;
            resourceInputs["spfTextValue"] = undefined /*out*/;
            resourceInputs["spfVerified"] = undefined /*out*/;
            resourceInputs["weakDkim"] = undefined /*out*/;
        } else {
            resourceInputs["dkimHost"] = undefined /*out*/;
            resourceInputs["dkimPendingHost"] = undefined /*out*/;
            resourceInputs["dkimPendingTextValue"] = undefined /*out*/;
            resourceInputs["dkimRevokedHost"] = undefined /*out*/;
            resourceInputs["dkimRevokedTextValue"] = undefined /*out*/;
            resourceInputs["dkimTextValue"] = undefined /*out*/;
            resourceInputs["dkimUpdateStatus"] = undefined /*out*/;
            resourceInputs["dkimVerified"] = undefined /*out*/;
            resourceInputs["domainId"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["returnPathDomain"] = undefined /*out*/;
            resourceInputs["returnPathDomainCnameValue"] = undefined /*out*/;
            resourceInputs["returnPathDomainVerified"] = undefined /*out*/;
            resourceInputs["safeToRemoveRevokedKeyFromDns"] = undefined /*out*/;
            resourceInputs["spfHost"] = undefined /*out*/;
            resourceInputs["spfTextValue"] = undefined /*out*/;
            resourceInputs["spfVerified"] = undefined /*out*/;
            resourceInputs["weakDkim"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["name"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Domain.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Domain resource.
 */
export interface DomainArgs {
    /**
     * The domain name to send from (e.g. `example.com`). Immutable — changing it replaces the domain.
     */
    name: pulumi.Input<string>;
    /**
     * Custom Return-Path subdomain (e.g. `pm-bounces.example.com`). Must be a subdomain of `name` and have a CNAME pointing at the value of `returnPathDomainCnameValue`.
     */
    returnPathDomain?: pulumi.Input<string>;
}
