// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { DomainArgs } from "./domain";
export type Domain = import("./domain").Domain;
export const Domain: typeof import("./domain").Domain = null as any;
utilities.lazyLoad(exports, ["Domain"], () => require("./domain"));

export { DomainVerificationArgs } from "./domainVerification";
export type DomainVerification = import("./domainVerification").DomainVerification;
export const DomainVerification: typeof import("./domainVerification").DomainVerification = null as any;
utilities.lazyLoad(exports, ["DomainVerification"], () => require("./domainVerification"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { SenderSignatureArgs } from "./senderSignature";
export type SenderSignature = import("./senderSignature").SenderSignature;
export const SenderSignature: typeof import("./senderSignature").SenderSignature = null as any;
utilities.lazyLoad(exports, ["SenderSignature"], () => require("./senderSignature"));

export { ServerArgs } from "./server";
export type Server = import("./server").Server;
export const Server: typeof import("./server").Server = null as any;
utilities.lazyLoad(exports, ["Server"], () => require("./server"));

export { TemplateArgs } from "./template";
export type Template = import("./template").Template;
export const Template: typeof import("./template").Template = null as any;
utilities.lazyLoad(exports, ["Template"], () => require("./template"));


// Export sub-modules:
import * as config from "./config";

export {
    config,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "postmark:index:Domain":
                return new Domain(name, <any>undefined, { urn })
            case "postmark:index:DomainVerification":
                return new DomainVerification(name, <any>undefined, { urn })
            case "postmark:index:SenderSignature":
                return new SenderSignature(name, <any>undefined, { urn })
            case "postmark:index:Server":
                return new Server(name, <any>undefined, { urn })
            case "postmark:index:Template":
                return new Template(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("postmark", "index", _module)
pulumi.runtime.registerResourcePackage("postmark", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:postmark") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
