// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SenderSignature extends pulumi.CustomResource {
    /**
     * Get an existing SenderSignature resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): SenderSignature {
        return new SenderSignature(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'postmark:index:SenderSignature';

    /**
     * Returns true if the given object is an instance of SenderSignature.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SenderSignature {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SenderSignature.__pulumiType;
    }

    /**
     * Optional note (max 400 chars) included in the confirmation email.
     */
    declare public readonly confirmationPersonalNote: pulumi.Output<string | undefined>;
    /**
     * Whether the signature has been confirmed. Postmark requires a human to click the confirmation email; run `pulumi refresh` to observe this flipping to true.
     */
    declare public /*out*/ readonly confirmed: pulumi.Output<boolean>;
    declare public /*out*/ readonly dkimHost: pulumi.Output<string>;
    declare public /*out*/ readonly dkimPendingHost: pulumi.Output<string>;
    declare public /*out*/ readonly dkimPendingTextValue: pulumi.Output<string>;
    declare public /*out*/ readonly dkimTextValue: pulumi.Output<string>;
    declare public /*out*/ readonly dkimVerified: pulumi.Output<boolean>;
    declare public /*out*/ readonly domain: pulumi.Output<string>;
    declare public /*out*/ readonly emailAddress: pulumi.Output<string>;
    /**
     * The email address to sign. Immutable — changing it replaces the signature.
     */
    declare public readonly fromEmail: pulumi.Output<string>;
    /**
     * From name associated with the signature.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Optional Reply-To email address.
     */
    declare public readonly replyToEmail: pulumi.Output<string | undefined>;
    /**
     * Optional custom Return-Path subdomain of the From address's domain.
     */
    declare public readonly returnPathDomain: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly returnPathDomainCnameValue: pulumi.Output<string>;
    declare public /*out*/ readonly returnPathDomainVerified: pulumi.Output<boolean>;
    declare public /*out*/ readonly signatureId: pulumi.Output<number>;
    declare public /*out*/ readonly spfHost: pulumi.Output<string>;
    declare public /*out*/ readonly spfTextValue: pulumi.Output<string>;
    declare public /*out*/ readonly spfVerified: pulumi.Output<boolean>;
    /**
     * Arbitrary value; change it to resend the confirmation email on the next update.
     */
    declare public readonly triggerResend: pulumi.Output<string | undefined>;

    /**
     * Create a SenderSignature resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SenderSignatureArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.fromEmail === undefined && !opts.urn) {
                throw new Error("Missing required property 'fromEmail'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["confirmationPersonalNote"] = args?.confirmationPersonalNote;
            resourceInputs["fromEmail"] = args?.fromEmail;
            resourceInputs["name"] = args?.name;
            resourceInputs["replyToEmail"] = args?.replyToEmail;
            resourceInputs["returnPathDomain"] = args?.returnPathDomain;
            resourceInputs["triggerResend"] = args?.triggerResend;
            resourceInputs["confirmed"] = undefined /*out*/;
            resourceInputs["dkimHost"] = undefined /*out*/;
            resourceInputs["dkimPendingHost"] = undefined /*out*/;
            resourceInputs["dkimPendingTextValue"] = undefined /*out*/;
            resourceInputs["dkimTextValue"] = undefined /*out*/;
            resourceInputs["dkimVerified"] = undefined /*out*/;
            resourceInputs["domain"] = undefined /*out*/;
            resourceInputs["emailAddress"] = undefined /*out*/;
            resourceInputs["returnPathDomainCnameValue"] = undefined /*out*/;
            resourceInputs["returnPathDomainVerified"] = undefined /*out*/;
            resourceInputs["signatureId"] = undefined /*out*/;
            resourceInputs["spfHost"] = undefined /*out*/;
            resourceInputs["spfTextValue"] = undefined /*out*/;
            resourceInputs["spfVerified"] = undefined /*out*/;
        } else {
            resourceInputs["confirmationPersonalNote"] = undefined /*out*/;
            resourceInputs["confirmed"] = undefined /*out*/;
            resourceInputs["dkimHost"] = undefined /*out*/;
            resourceInputs["dkimPendingHost"] = undefined /*out*/;
            resourceInputs["dkimPendingTextValue"] = undefined /*out*/;
            resourceInputs["dkimTextValue"] = undefined /*out*/;
            resourceInputs["dkimVerified"] = undefined /*out*/;
            resourceInputs["domain"] = undefined /*out*/;
            resourceInputs["emailAddress"] = undefined /*out*/;
            resourceInputs["fromEmail"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["replyToEmail"] = undefined /*out*/;
            resourceInputs["returnPathDomain"] = undefined /*out*/;
            resourceInputs["returnPathDomainCnameValue"] = undefined /*out*/;
            resourceInputs["returnPathDomainVerified"] = undefined /*out*/;
            resourceInputs["signatureId"] = undefined /*out*/;
            resourceInputs["spfHost"] = undefined /*out*/;
            resourceInputs["spfTextValue"] = undefined /*out*/;
            resourceInputs["spfVerified"] = undefined /*out*/;
            resourceInputs["triggerResend"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["fromEmail"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(SenderSignature.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a SenderSignature resource.
 */
export interface SenderSignatureArgs {
    /**
     * Optional note (max 400 chars) included in the confirmation email.
     */
    confirmationPersonalNote?: pulumi.Input<string>;
    /**
     * The email address to sign. Immutable — changing it replaces the signature.
     */
    fromEmail: pulumi.Input<string>;
    /**
     * From name associated with the signature.
     */
    name: pulumi.Input<string>;
    /**
     * Optional Reply-To email address.
     */
    replyToEmail?: pulumi.Input<string>;
    /**
     * Optional custom Return-Path subdomain of the From address's domain.
     */
    returnPathDomain?: pulumi.Input<string>;
    /**
     * Arbitrary value; change it to resend the confirmation email on the next update.
     */
    triggerResend?: pulumi.Input<string>;
}
