// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Server extends pulumi.CustomResource {
    /**
     * Get an existing Server resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Server {
        return new Server(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'postmark:index:Server';

    /**
     * Returns true if the given object is an instance of Server.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Server {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Server.__pulumiType;
    }

    declare public /*out*/ readonly apiTokens: pulumi.Output<string[]>;
    /**
     * Color of the server in the Postmark UI server list. One of: Purple, Blue, Turquoise, Green, Red, Yellow, Grey, Orange. Defaults to Blue.
     */
    declare public readonly color: pulumi.Output<string | undefined>;
    /**
     * Environment type: `Live` or `Sandbox`. Immutable after creation — changing it replaces the server. Defaults to `Live`.
     */
    declare public readonly deliveryType: pulumi.Output<string | undefined>;
    declare public readonly enableSmtpApiErrorHooks: pulumi.Output<boolean | undefined>;
    declare public /*out*/ readonly inboundAddress: pulumi.Output<string>;
    /**
     * Inbound domain for MX setup. Point an MX record for this domain at `inbound.postmarkapp.com` to receive mail.
     */
    declare public readonly inboundDomain: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly inboundHash: pulumi.Output<string>;
    /**
     * URL Postmark POSTs to for every inbound email event.
     */
    declare public readonly inboundHookUrl: pulumi.Output<string | undefined>;
    /**
     * Maximum spam score before an inbound message is blocked.
     */
    declare public readonly inboundSpamThreshold: pulumi.Output<number | undefined>;
    declare public readonly includeBounceContentInHook: pulumi.Output<boolean | undefined>;
    /**
     * Friendly name of the server.
     */
    declare public readonly name: pulumi.Output<string>;
    declare public readonly postFirstOpenOnly: pulumi.Output<boolean | undefined>;
    declare public readonly rawEmailEnabled: pulumi.Output<boolean | undefined>;
    declare public /*out*/ readonly serverId: pulumi.Output<number>;
    declare public /*out*/ readonly serverLink: pulumi.Output<string>;
    declare public readonly smtpApiActivated: pulumi.Output<boolean | undefined>;
    /**
     * Link tracking mode: None, HtmlAndText, HtmlOnly or TextOnly. Defaults to None.
     */
    declare public readonly trackLinks: pulumi.Output<string | undefined>;
    /**
     * Enable open tracking for messages by default.
     */
    declare public readonly trackOpens: pulumi.Output<boolean | undefined>;

    /**
     * Create a Server resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ServerArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["color"] = args?.color;
            resourceInputs["deliveryType"] = args?.deliveryType;
            resourceInputs["enableSmtpApiErrorHooks"] = args?.enableSmtpApiErrorHooks;
            resourceInputs["inboundDomain"] = args?.inboundDomain;
            resourceInputs["inboundHookUrl"] = args?.inboundHookUrl;
            resourceInputs["inboundSpamThreshold"] = args?.inboundSpamThreshold;
            resourceInputs["includeBounceContentInHook"] = args?.includeBounceContentInHook;
            resourceInputs["name"] = args?.name;
            resourceInputs["postFirstOpenOnly"] = args?.postFirstOpenOnly;
            resourceInputs["rawEmailEnabled"] = args?.rawEmailEnabled;
            resourceInputs["smtpApiActivated"] = args?.smtpApiActivated;
            resourceInputs["trackLinks"] = args?.trackLinks;
            resourceInputs["trackOpens"] = args?.trackOpens;
            resourceInputs["apiTokens"] = undefined /*out*/;
            resourceInputs["inboundAddress"] = undefined /*out*/;
            resourceInputs["inboundHash"] = undefined /*out*/;
            resourceInputs["serverId"] = undefined /*out*/;
            resourceInputs["serverLink"] = undefined /*out*/;
        } else {
            resourceInputs["apiTokens"] = undefined /*out*/;
            resourceInputs["color"] = undefined /*out*/;
            resourceInputs["deliveryType"] = undefined /*out*/;
            resourceInputs["enableSmtpApiErrorHooks"] = undefined /*out*/;
            resourceInputs["inboundAddress"] = undefined /*out*/;
            resourceInputs["inboundDomain"] = undefined /*out*/;
            resourceInputs["inboundHash"] = undefined /*out*/;
            resourceInputs["inboundHookUrl"] = undefined /*out*/;
            resourceInputs["inboundSpamThreshold"] = undefined /*out*/;
            resourceInputs["includeBounceContentInHook"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["postFirstOpenOnly"] = undefined /*out*/;
            resourceInputs["rawEmailEnabled"] = undefined /*out*/;
            resourceInputs["serverId"] = undefined /*out*/;
            resourceInputs["serverLink"] = undefined /*out*/;
            resourceInputs["smtpApiActivated"] = undefined /*out*/;
            resourceInputs["trackLinks"] = undefined /*out*/;
            resourceInputs["trackOpens"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiTokens"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        const replaceOnChanges = { replaceOnChanges: ["deliveryType"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Server.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Server resource.
 */
export interface ServerArgs {
    /**
     * Color of the server in the Postmark UI server list. One of: Purple, Blue, Turquoise, Green, Red, Yellow, Grey, Orange. Defaults to Blue.
     */
    color?: pulumi.Input<string>;
    /**
     * Environment type: `Live` or `Sandbox`. Immutable after creation — changing it replaces the server. Defaults to `Live`.
     */
    deliveryType?: pulumi.Input<string>;
    enableSmtpApiErrorHooks?: pulumi.Input<boolean>;
    /**
     * Inbound domain for MX setup. Point an MX record for this domain at `inbound.postmarkapp.com` to receive mail.
     */
    inboundDomain?: pulumi.Input<string>;
    /**
     * URL Postmark POSTs to for every inbound email event.
     */
    inboundHookUrl?: pulumi.Input<string>;
    /**
     * Maximum spam score before an inbound message is blocked.
     */
    inboundSpamThreshold?: pulumi.Input<number>;
    includeBounceContentInHook?: pulumi.Input<boolean>;
    /**
     * Friendly name of the server.
     */
    name: pulumi.Input<string>;
    postFirstOpenOnly?: pulumi.Input<boolean>;
    rawEmailEnabled?: pulumi.Input<boolean>;
    smtpApiActivated?: pulumi.Input<boolean>;
    /**
     * Link tracking mode: None, HtmlAndText, HtmlOnly or TextOnly. Defaults to None.
     */
    trackLinks?: pulumi.Input<string>;
    /**
     * Enable open tracking for messages by default.
     */
    trackOpens?: pulumi.Input<boolean>;
}
