// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Template extends pulumi.CustomResource {
    /**
     * Get an existing Template resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Template {
        return new Template(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'postmark:index:Template';

    /**
     * Returns true if the given object is an instance of Template.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Template {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Template.__pulumiType;
    }

    declare public /*out*/ readonly active: pulumi.Output<boolean>;
    /**
     * Optional unique alias (within the server). Must start with a letter; may contain letters, digits, '.', '-' and '_'.
     */
    declare public readonly alias: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly associatedServerId: pulumi.Output<number>;
    /**
     * HTML body. Required unless `textBody` is set.
     */
    declare public readonly htmlBody: pulumi.Output<string | undefined>;
    /**
     * Alias of a Layout to wrap this Standard template (set to "" to disassociate).
     */
    declare public readonly layoutTemplate: pulumi.Output<string | undefined>;
    /**
     * Name of the template.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * ID of the server this template belongs to; the provider looks up its token via the account token. Immutable — changing it replaces the template.
     */
    declare public readonly serverId: pulumi.Output<number | undefined>;
    /**
     * Server API token of the server this template belongs to. Wire from `server.apiTokens[0]`. Falls back to `serverId` lookup, then the provider `serverToken` config.
     */
    declare public readonly serverToken: pulumi.Output<string | undefined>;
    /**
     * Subject line. Required for Standard templates; not allowed for Layouts.
     */
    declare public readonly subject: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly templateId: pulumi.Output<number>;
    /**
     * `Standard` (default) or `Layout`. Immutable — changing it replaces the template.
     */
    declare public readonly templateType: pulumi.Output<string | undefined>;
    /**
     * Plain-text body. Required unless `htmlBody` is set.
     */
    declare public readonly textBody: pulumi.Output<string | undefined>;

    /**
     * Create a Template resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TemplateArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["alias"] = args?.alias;
            resourceInputs["htmlBody"] = args?.htmlBody;
            resourceInputs["layoutTemplate"] = args?.layoutTemplate;
            resourceInputs["name"] = args?.name;
            resourceInputs["serverId"] = args?.serverId;
            resourceInputs["serverToken"] = args?.serverToken ? pulumi.secret(args.serverToken) : undefined;
            resourceInputs["subject"] = args?.subject;
            resourceInputs["templateType"] = args?.templateType;
            resourceInputs["textBody"] = args?.textBody;
            resourceInputs["active"] = undefined /*out*/;
            resourceInputs["associatedServerId"] = undefined /*out*/;
            resourceInputs["templateId"] = undefined /*out*/;
        } else {
            resourceInputs["active"] = undefined /*out*/;
            resourceInputs["alias"] = undefined /*out*/;
            resourceInputs["associatedServerId"] = undefined /*out*/;
            resourceInputs["htmlBody"] = undefined /*out*/;
            resourceInputs["layoutTemplate"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["serverId"] = undefined /*out*/;
            resourceInputs["serverToken"] = undefined /*out*/;
            resourceInputs["subject"] = undefined /*out*/;
            resourceInputs["templateId"] = undefined /*out*/;
            resourceInputs["templateType"] = undefined /*out*/;
            resourceInputs["textBody"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["serverToken"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        const replaceOnChanges = { replaceOnChanges: ["serverId", "templateType"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Template.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Template resource.
 */
export interface TemplateArgs {
    /**
     * Optional unique alias (within the server). Must start with a letter; may contain letters, digits, '.', '-' and '_'.
     */
    alias?: pulumi.Input<string>;
    /**
     * HTML body. Required unless `textBody` is set.
     */
    htmlBody?: pulumi.Input<string>;
    /**
     * Alias of a Layout to wrap this Standard template (set to "" to disassociate).
     */
    layoutTemplate?: pulumi.Input<string>;
    /**
     * Name of the template.
     */
    name: pulumi.Input<string>;
    /**
     * ID of the server this template belongs to; the provider looks up its token via the account token. Immutable — changing it replaces the template.
     */
    serverId?: pulumi.Input<number>;
    /**
     * Server API token of the server this template belongs to. Wire from `server.apiTokens[0]`. Falls back to `serverId` lookup, then the provider `serverToken` config.
     */
    serverToken?: pulumi.Input<string>;
    /**
     * Subject line. Required for Standard templates; not allowed for Layouts.
     */
    subject?: pulumi.Input<string>;
    /**
     * `Standard` (default) or `Layout`. Immutable — changing it replaces the template.
     */
    templateType?: pulumi.Input<string>;
    /**
     * Plain-text body. Required unless `htmlBody` is set.
     */
    textBody?: pulumi.Input<string>;
}
